const LOCAL_CHAT_CONSOLE_ROUTE_V1 = "/chat";
const LOCAL_CHAT_AUTH_CONFIG_ROUTE_V1 = "/v1/local-chat/auth/config";

export interface LocalChatConsoleOptionsV1 {
  readonly enabled: boolean;
  /**
   * Exact HTTPS origin of the Supabase Auth issuer. When supplied, the
   * browser may use it only to obtain a user session; it never receives an
   * administrator or service credential.
   */
  readonly supabaseAuthOrigin?: string;
  /**
   * Browser-safe Supabase publishable key. This is intentionally distinct from
   * the server-only PAI_SUPABASE_SECRET_KEY used by object storage.
   */
  readonly supabasePublishableKey?: string;
}

export function localChatConsoleEnabledFromEnvV1(
  env: Readonly<Record<string, string | undefined>>,
  deploymentEnvironment: string,
): boolean {
  return (
    deploymentEnvironment === "local" &&
    env.PAI_LOCAL_CHAT_CONSOLE_ENABLED === "true"
  );
}

export function localChatConsoleSupabaseAuthOriginFromIssuerV1(
  issuer: string | undefined,
): string | undefined {
  if (issuer === undefined || issuer.length === 0) return undefined;
  let parsed: URL;
  try {
    parsed = new URL(issuer);
  } catch {
    throw new Error("PAI_SUPABASE_ISSUER must be an absolute HTTPS URL");
  }
  if (
    parsed.protocol !== "https:" ||
    parsed.username.length > 0 ||
    parsed.password.length > 0
  ) {
    throw new Error("PAI_SUPABASE_ISSUER must be an absolute HTTPS URL");
  }
  return parsed.origin;
}

export function localChatConsoleSupabasePublishableKeyFromEnvV1(
  value: string | undefined,
): string | undefined {
  if (value === undefined || value.length === 0) return undefined;
  if (!/^sb_publishable_[A-Za-z0-9_-]+$/u.test(value)) {
    throw new Error(
      "PAI_SUPABASE_PUBLISHABLE_KEY must be a Supabase publishable key",
    );
  }
  return value;
}

/**
 * A deliberately thin local client for the public Trigger ingress.  It never
 * receives a service-role credential or workload signing key: the browser
 * keeps a user Supabase access token in sessionStorage and presents it only to
 * the same Trigger Processor origin that verifies it.
 */
export function localChatConsoleHtmlV1(): string {
  return String.raw`<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="referrer" content="no-referrer">
  <title>PAI local chat</title>
  <style>
    :root { color-scheme: dark; --bg:#08110c; --panel:#0d1b12; --line:#23452d; --text:#d8f8d7; --muted:#78a57d; --ok:#59e98a; --warn:#ffcf66; --bad:#ff7777; }
    * { box-sizing:border-box; }
    body { margin:0; min-height:100vh; background:radial-gradient(circle at 15% 0,#153d21 0,transparent 32rem),var(--bg); color:var(--text); font:14px/1.5 ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace; }
    .shell { width:min(1120px,calc(100vw - 32px)); margin:24px auto; border:1px solid var(--line); background:rgba(8,17,12,.92); box-shadow:0 16px 64px #0008; }
    header { display:flex; gap:16px; align-items:center; padding:12px 16px; border-bottom:1px solid var(--line); background:#0a160e; }
    .lights { display:flex; gap:7px; } .light { width:10px;height:10px;border-radius:50%;background:#ff6b6b } .light:nth-child(2){background:#ffc75f}.light:nth-child(3){background:#5ee890}
    h1 { font-size:14px; margin:0; font-weight:600; letter-spacing:.03em; } .badge { margin-left:auto; color:var(--ok); font-size:12px; }
    main { display:grid; grid-template-columns:300px 1fr; min-height:650px; }
    aside { padding:16px; border-right:1px solid var(--line); background:#0a160e; }
    .label { display:block; color:var(--muted); font-size:11px; letter-spacing:.08em; margin:14px 0 5px; text-transform:uppercase; }
    input,textarea,button { font:inherit; } input,textarea { width:100%; border:1px solid var(--line); background:#061008; color:var(--text); padding:9px; outline:none; border-radius:2px; }
    input:focus,textarea:focus { border-color:var(--ok); box-shadow:0 0 0 2px #59e98a20; } textarea { resize:vertical; min-height:86px; }
    .hint { color:var(--muted); font-size:11px; margin:7px 0 0; } .token-row{display:flex;gap:6px}.token-row button{padding:0 9px}
    .scope { border-top:1px solid var(--line); margin-top:20px; padding-top:4px; } .scope div { padding:5px 0; color:var(--muted); font-size:12px; overflow-wrap:anywhere; } .scope b { color:var(--text); font-weight:500; } .process-control { margin-top:18px; } #cancel-confirmation { margin-top:7px; } button.danger { color:#fff; background:#9b3d3d; border-color:#d96161; }
    #research-trace { border-top:1px solid var(--line); margin-top:20px; padding-top:12px; color:var(--muted); font-size:11px; } #research-trace summary { cursor:pointer; color:var(--text); } #research-trace p { margin:8px 0 0; white-space:pre-wrap; overflow-wrap:anywhere; } #research-trace ul { padding-left:18px; margin:8px 0; } #research-trace li { margin:5px 0; overflow-wrap:anywhere; } #research-trace a { color:#b9dbff; }
    .console { display:flex; flex-direction:column; min-width:0; } #transcript { flex:1; overflow:auto; padding:20px; min-height:470px; } .line { margin:0 0 12px; white-space:pre-wrap; overflow-wrap:anywhere; } .time { color:var(--muted); } .system { color:var(--muted); } .you { color:#b9dbff; } .state { color:var(--ok); } .warn { color:var(--warn); } .error { color:var(--bad); }
    .confirmation { margin:0 0 14px; padding:12px; border:1px solid var(--warn); background:#2a210d; color:var(--text); } .confirmation strong { color:var(--warn); display:block; margin-bottom:5px; } .confirmation p { margin:5px 0; white-space:pre-wrap; overflow-wrap:anywhere; } .confirmation .buttons { display:flex; gap:8px; margin-top:10px; } .confirmation .reject { color:var(--text); background:transparent; border-color:#9b5b3f; }
    form { border-top:1px solid var(--line); padding:14px; background:#0a160e; } .prompt { display:flex; align-items:flex-start; gap:9px; } .prompt-mark { color:var(--ok); padding-top:8px; } .prompt textarea { min-height:74px; } .actions { display:flex; gap:8px; justify-content:space-between; align-items:center; margin-top:8px; }
    button { border:1px solid #3a8450; color:#001a09; background:var(--ok); border-radius:2px; padding:7px 12px; cursor:pointer; font-weight:700; } button.secondary { color:var(--text); border-color:var(--line); background:transparent; } button:disabled { cursor:not-allowed; opacity:.5; }
    #connection { color:var(--muted); font-size:12px; }
    @media (max-width:760px) { .shell{width:100%;margin:0;border-width:0}.shell main{grid-template-columns:1fr}.shell aside{border-right:0;border-bottom:1px solid var(--line)} }
  </style>
</head>
<body>
  <div class="shell">
    <header><div class="lights"><i class="light"></i><i class="light"></i><i class="light"></i></div><h1>PAI // LOCAL CHAT CONSOLE</h1><span class="badge">● local only</span></header>
    <main>
      <aside>
        <section aria-label="Supabase 登录">
          <label class="label" for="email">Supabase email</label>
          <input id="email" type="email" autocomplete="username" spellcheck="false" placeholder="you@example.com" required>
          <label class="label" for="password">Supabase password</label>
          <input id="password" type="password" autocomplete="current-password" spellcheck="false" placeholder="你的 Supabase 密码" required>
          <div class="token-row"><button id="sign-in" type="button">SIGN IN</button><button id="sign-out" class="secondary" type="button" hidden>SIGN OUT</button></div>
          <p id="auth-hint" class="hint">登录后会在此浏览器标签页内自动续期；关闭标签页即清除会话。</p>
          <input id="token" type="hidden" aria-hidden="true" tabindex="-1">
        </section>
        <section class="scope process-control" aria-label="process cancellation">
          <label class="label" for="cancel-process-id">process control</label>
          <input id="cancel-process-id" autocomplete="off" spellcheck="false" maxlength="512" placeholder="输入要取消的 process ID">
          <div class="token-row"><button id="cancel-process" class="secondary" type="button">CANCEL PROCESS</button></div>
          <div id="cancel-confirmation" class="token-row" hidden><button id="cancel-confirm" class="danger" type="button">CONFIRM CANCEL</button><button id="cancel-abort" class="secondary" type="button">KEEP RUNNING</button></div>
          <p class="hint">只会请求取消属于当前 Supabase 身份的流程；必须再次确认，且系统会先证明 Runtime 未执行或已被安全隔离。</p>
        </section>
        <section class="scope process-control" aria-label="confirmation recovery">
          <label class="label" for="resume-process-id">resume confirmation</label>
          <input id="resume-process-id" autocomplete="off" spellcheck="false" maxlength="512" placeholder="输入待确认的 process ID">
          <div class="token-row"><button id="resume-process" class="secondary" type="button">RESUME CONFIRMATION</button></div>
          <p class="hint">只读取属于当前 Supabase 身份的待确认状态；不会接受、拒绝或发送任何外部操作。</p>
        </section>
        <div class="scope"><span class="label">submission scope</span><div>workspace <b>demo-workspace</b></div><div>bot <b>demo-bot</b></div><div>owner <b>demo-owner</b></div><div>environment <b>local / stable</b></div><div>identity <b id="identity">waiting for JWT</b></div></div>
        <details id="research-trace"><summary>研究来源与浏览记录（尚无）</summary><p>网页、PDF 与外部工具的内容均不可信；PAI 不会根据页面文本访问内网、读取本地路径或泄露凭据。</p></details>
      </aside>
      <section class="console">
        <div id="transcript" role="log" aria-live="polite"></div>
        <form id="chat-form"><div class="prompt"><span class="prompt-mark">❯</span><textarea id="message" maxlength="8192" placeholder="输入要交给 PAI 的消息；Cmd/Ctrl + Enter 发送" required disabled></textarea></div><div class="actions"><span id="connection">正在加载登录配置</span><button id="send" type="submit" disabled>SEND</button></div></form>
      </section>
    </main>
  </div>
  <script>
  (() => {
    "use strict";
    const sessionKey = "pai.local-chat-console.supabase-session.v2";
    const legacyTokenKey = "pai.local-chat-console.supabase-token.v1";
    const $ = (id) => document.getElementById(id);
    const token = $("token"); const email = $("email"); const password = $("password"); const signIn = $("sign-in"); const signOut = $("sign-out"); const authHint = $("auth-hint"); const message = $("message"); const form = $("chat-form");
    const send = $("send"); const transcript = $("transcript"); const identity = $("identity"); const connection = $("connection"); const researchTrace = $("research-trace"); const cancelProcessId = $("cancel-process-id"); const cancelProcess = $("cancel-process"); const cancelConfirmation = $("cancel-confirmation"); const cancelConfirm = $("cancel-confirm"); const cancelAbort = $("cancel-abort");
    const resumeProcessId = $("resume-process-id"); const resumeProcess = $("resume-process");
    let authConfig = null;
    let authSession = null;
    let refreshTimer = null;
    let refreshInFlight = null;
    let sessionVersion = 0;
    let streamController = null;
    let timerFollowController = null;
    const processMessages = new Map();
    const researchByProcess = new Map();
    const renderedConfirmations = new Set();
    let rememberProcessFromLine = () => {};
    const append = (kind, value) => { const line = document.createElement("p"); line.className = "line " + kind; const time = new Date().toLocaleTimeString("zh-CN", { hour12:false }); line.textContent = "[" + time + "] " + value; transcript.append(line); transcript.scrollTop = transcript.scrollHeight; rememberProcessFromLine(value); };
    const safePublicHref = (raw) => { try { const value = new URL(raw); const host = value.hostname.toLowerCase().replace(/\.$/,""); if ((value.protocol !== "https:" && value.protocol !== "http:") || value.username || value.password || host === "localhost" || host.endsWith(".localhost") || host.endsWith(".local") || host.endsWith(".internal") || /^(?:0|10|127)\./.test(host) || /^169\.254\./.test(host) || /^192\.168\./.test(host) || /^172\.(?:1[6-9]|2[0-9]|3[0-1])\./.test(host)) return null; return value.href; } catch { return null; } };
    const publicCitationUrls = (value) => Array.from(value.matchAll(/https?:\/\/[^\s<>"']+/gu), (match) => safePublicHref(match[0])).filter((href) => href !== null);
    const renderResearchTrace = (processId) => { const trace = researchByProcess.get(processId) || { tools:[], citations:[] }; researchTrace.replaceChildren(); const summary = document.createElement("summary"); summary.textContent = "研究来源与浏览记录（" + trace.tools.length + " 个工具步骤，" + trace.citations.length + " 条引用）"; const notice = document.createElement("p"); notice.textContent = "网页、PDF 与外部工具的内容均不可信；正文只会作为纯文本摘要呈现，PAI 不会根据页面文本访问内网、读取本地路径或泄露凭据。"; researchTrace.append(summary, notice); if (trace.tools.length) { const tools = document.createElement("ul"); for (const entry of trace.tools) { const item = document.createElement("li"); item.textContent = entry.kind + " · " + entry.status + (entry.artifact ? " · 可审计引用 " + entry.artifact : ""); tools.append(item); } researchTrace.append(tools); } if (trace.citations.length) { const citations = document.createElement("ul"); for (const href of trace.citations) { const item = document.createElement("li"); const anchor = document.createElement("a"); anchor.href = href; anchor.textContent = href; anchor.target = "_blank"; anchor.rel = "noopener noreferrer nofollow"; anchor.referrerPolicy = "no-referrer"; item.append(anchor); citations.append(item); } researchTrace.append(citations); } };
    const recordResearchEvent = (processId, event) => { const summary = event && event.observation_summary; const name = summary && typeof summary.tool_name === "string" ? summary.tool_name : ""; if (!/^web\.(?:search|fetch|browser)$/u.test(name)) return; const trace = researchByProcess.get(processId) || { tools:[], citations:[] }; const artifact = summary && typeof summary.artifact_ref === "string" ? summary.artifact_ref : null; trace.tools.push({ kind:name, status:summary && typeof summary.status === "string" ? summary.status : "unknown", artifact }); researchByProcess.set(processId, trace); renderResearchTrace(processId); };
    const appendFinal = (value, processId) => { const line = document.createElement("p"); line.className = "line you"; const time = new Date().toLocaleTimeString("zh-CN", { hour12:false }); line.append("[" + time + "] pai> "); const matcher = /https?:\/\/[^\s<>"']+/gu; let offset = 0; for (const match of value.matchAll(matcher)) { const raw = match[0]; const index = match.index || 0; line.append(value.slice(offset,index)); const href = safePublicHref(raw); if (href === null) line.append(raw); else { const anchor = document.createElement("a"); anchor.href = href; anchor.textContent = raw; anchor.target = "_blank"; anchor.rel = "noopener noreferrer nofollow"; anchor.referrerPolicy = "no-referrer"; line.append(anchor); } offset = index + raw.length; } line.append(value.slice(offset)); transcript.append(line); transcript.scrollTop = transcript.scrollHeight; if (typeof processId === "string") { const trace = researchByProcess.get(processId) || { tools:[], citations:[] }; trace.citations = Array.from(new Set([...trace.citations, ...publicCitationUrls(value)])); researchByProcess.set(processId, trace); renderResearchTrace(processId); } };
    const setConnection = (value, kind) => { connection.textContent = value; connection.className = kind || ""; };
    const authConfigurationError = "本机聊天尚未配置 Supabase Publishable key";
    const isSession = (value) => value && typeof value === "object" && typeof value.access_token === "string" && value.access_token.length > 0 && typeof value.refresh_token === "string" && value.refresh_token.length > 0 && typeof value.expires_at === "number" && Number.isFinite(value.expires_at);
    const sessionExpiry = (value) => Math.floor(value.expires_at * 1000);
    const clearRefreshTimer = () => { if (refreshTimer !== null) { clearTimeout(refreshTimer); refreshTimer = null; } };
    const clearSession = (notice) => { sessionVersion += 1; clearRefreshTimer(); if (streamController) streamController.abort(); if (timerFollowController) timerFollowController.abort(); if (confirmationPollController) confirmationPollController.abort(); authSession = null; token.value = ""; sessionStorage.removeItem(sessionKey); sessionStorage.removeItem("pai.local-chat-console.active-process.v1"); signOut.hidden = true; signIn.hidden = false; signIn.disabled = authConfig === null; email.disabled = authConfig === null; password.disabled = authConfig === null; message.disabled = true; send.disabled = true; identity.textContent = "not signed in"; authHint.textContent = notice || "请使用 Supabase 邮箱和密码登录。"; setConnection(notice || "请先登录", notice ? "warn" : ""); };
    const scheduleRefresh = () => { clearRefreshTimer(); if (!authSession) return; const due = Math.max(15_000, sessionExpiry(authSession) - Date.now() - 120_000); refreshTimer = setTimeout(() => { void refreshSession().catch(() => undefined); }, Math.min(due, 2_147_000_000)); };
    const storeSession = (value) => { if (!isSession(value)) throw new Error("Supabase 未返回完整会话"); sessionVersion += 1; authSession = Object.freeze({ access_token:value.access_token, refresh_token:value.refresh_token, expires_at:value.expires_at }); token.value = authSession.access_token; sessionStorage.setItem(sessionKey, JSON.stringify(authSession)); signOut.hidden = false; signIn.hidden = true; signIn.disabled = false; email.disabled = true; password.disabled = true; message.disabled = false; send.disabled = false; authHint.textContent = "当前标签页已登录；会话会在到期前自动续期。"; scheduleRefresh(); return refreshIdentity(); };
    const authRequest = async (grantType, body) => { if (!authConfig) throw new Error(authConfigurationError); const response = await fetch(authConfig.auth_origin + "/auth/v1/token?grant_type=" + encodeURIComponent(grantType), { method:"POST", headers:{ apikey:authConfig.publishable_key, "content-type":"application/json" }, body:JSON.stringify(body), cache:"no-store" }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof payload.error_description === "string" ? payload.error_description : "Supabase 登录或续期失败 (HTTP " + response.status + ")"); const expiresAt = typeof payload.expires_at === "number" ? payload.expires_at : typeof payload.expires_in === "number" ? Math.floor(Date.now() / 1000) + payload.expires_in : undefined; return { access_token:payload.access_token, refresh_token:payload.refresh_token, expires_at:expiresAt }; };
    const refreshSession = async () => { if (!authSession) throw new Error("请先登录"); if (refreshInFlight !== null) return refreshInFlight; const prior = authSession; const priorVersion = sessionVersion; refreshInFlight = (async () => { try { const next = await authRequest("refresh_token", { refresh_token:prior.refresh_token }); if (sessionVersion !== priorVersion || authSession !== prior) return null; storeSession(next); setConnection("身份已自动续期", "state"); return authSession; } catch (error) { if (sessionVersion === priorVersion && authSession === prior) { clearSession("会话续期失败，请重新登录"); append("warn", "Supabase 会话已结束，请重新登录后重试。"); } throw error; } finally { refreshInFlight = null; } })(); return refreshInFlight; };
    const activeAccessToken = async () => { if (!authSession) throw new Error("请先使用 Supabase 登录"); if (sessionExpiry(authSession) <= Date.now() + 120_000) await refreshSession(); if (!authSession || sessionExpiry(authSession) <= Date.now()) { clearSession("会话已过期，请重新登录"); throw new Error("Supabase 会话已过期"); } return authSession.access_token; };
    const login = async () => { const emailValue = email.value.trim(); const passwordValue = password.value; if (!emailValue || !passwordValue) { authHint.textContent = "请输入 Supabase 邮箱和密码。"; if (!emailValue) email.focus(); else password.focus(); return; } signIn.disabled = true; setConnection("正在登录 Supabase…"); try { const next = await authRequest("password", { email:emailValue, password:passwordValue }); password.value = ""; storeSession(next); append("state", "Supabase 登录成功；身份已载入。"); } catch (error) { password.value = ""; clearSession("Supabase 登录失败，请检查邮箱、密码和配置"); append("error", error instanceof Error ? error.message : "Supabase 登录失败"); } finally { if (authSession) signIn.disabled = false; } };
    const loadAuthConfiguration = async () => { try { const response = await fetch("/v1/local-chat/auth/config", { headers:{ accept:"application/json" }, cache:"no-store" }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof payload.message === "string" ? payload.message : authConfigurationError); if (!payload || typeof payload.auth_origin !== "string" || typeof payload.publishable_key !== "string") throw new Error(authConfigurationError); const parsed = new URL(payload.auth_origin); if (parsed.protocol !== "https:" || parsed.origin !== payload.auth_origin || !/^sb_publishable_[A-Za-z0-9_-]+$/u.test(payload.publishable_key)) throw new Error(authConfigurationError); authConfig = Object.freeze({ auth_origin:parsed.origin, publishable_key:payload.publishable_key }); email.disabled = false; password.disabled = false; signIn.disabled = false; authHint.textContent = "使用 Supabase 邮箱和密码登录；凭据不会保存在此页面。"; const raw = sessionStorage.getItem(sessionKey); if (!raw) { clearSession(); return; } try { const restored = JSON.parse(raw); if (!isSession(restored)) throw new Error("invalid session"); authSession = restored; token.value = authSession.access_token; if (sessionExpiry(authSession) <= Date.now() + 120_000) await refreshSession(); else { storeSession(authSession); setConnection("身份已恢复；会在到期前自动续期", "state"); } } catch { clearSession("已保存的会话无效，请重新登录"); } } catch (error) { authConfig = null; clearSession(error instanceof Error ? error.message : authConfigurationError); append("error", error instanceof Error ? error.message : authConfigurationError); } };
    const decodeClaims = (raw) => { const pieces = raw.split("."); if (pieces.length !== 3) throw new Error("JWT 格式不正确"); const base64 = pieces[1].replace(/-/g,"+").replace(/_/g,"/"); const json = decodeURIComponent(Array.prototype.map.call(atob(base64), (c) => "%" + ("00" + c.charCodeAt(0).toString(16)).slice(-2)).join("")); const claims = JSON.parse(json); if (!claims || typeof claims !== "object") throw new Error("JWT 载荷不正确"); return claims; };
    const clientIdentity = () => { const claims = decodeClaims(token.value.trim()); const app = claims.app_metadata && typeof claims.app_metadata === "object" ? claims.app_metadata : {}; const principalId = typeof app.principal_id === "string" && app.principal_id ? app.principal_id : claims.sub; if (typeof principalId !== "string" || !principalId) throw new Error("JWT 缺少主体标识"); const declared = app.principal_type; const roles = Array.isArray(app.roles) ? app.roles : typeof app.role === "string" ? [app.role] : []; const actorType = declared === "developer" ? "developer" : declared === "bot" ? "agent" : roles.includes("super_user") ? "super_user" : "user"; const confirmationPrincipalType = declared === "developer" ? "developer" : declared === "operator" ? "operator" : "user"; return { principalId, actorType, confirmationPrincipalType, expiresAt: typeof claims.exp === "number" ? claims.exp : null }; };
    const refreshIdentity = () => { const raw = token.value.trim(); if (!raw) { identity.textContent = "not signed in"; return null; } try { const value = clientIdentity(); const expiry = value.expiresAt === null ? "unknown expiry" : new Date(value.expiresAt * 1000).toLocaleString("zh-CN", {hour12:false}); identity.textContent = value.actorType + ":" + value.principalId; if (authSession) setConnection("身份已载入；到期 " + expiry + "，将自动续期", "state"); return value; } catch (error) { identity.textContent = "invalid session"; setConnection(error instanceof Error ? error.message : "会话无效", "error"); return null; } };
    const newId = () => crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36) + Math.random().toString(36).slice(2);
    const resetCancellationConfirmation = () => { cancelConfirmation.hidden = true; cancelConfirm.disabled = false; cancelAbort.disabled = false; };
    const cancelProcessWithConfirmation = async () => { const processId = cancelProcessId.value.trim(); const actor = refreshIdentity(); if (!processId || !actor) { append("error", !processId ? "请先输入 process ID" : "请先登录 Supabase"); if (!processId) cancelProcessId.focus(); else email.focus(); return; } cancelConfirm.disabled = true; cancelAbort.disabled = true; try { const bearer = await activeAccessToken(); const response = await fetch("/v1/trigger-processes/" + encodeURIComponent(processId) + "/cancel", { method:"POST", headers:{ authorization:"Bearer " + bearer, "content-type":"application/json", accept:"application/json" }, body:JSON.stringify({ idempotency_key:newId(), reason:"user_requested" }), cache:"no-store" }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error((body && body.message ? body.message : "取消请求被拒绝") + " (HTTP " + response.status + ")"); resetCancellationConfirmation(); append("state", "cancel: " + (body.code || "accepted") + " — " + processId); setConnection(body.code === "cancel_pending" ? "取消正在由 Runtime 安全处理" : "取消已提交并开始观察", "state"); void streamEvents(processId, bearer); } catch (error) { cancelConfirm.disabled = false; cancelAbort.disabled = false; setConnection(error instanceof Error ? error.message : "取消失败", "error"); append("error", error instanceof Error ? error.message : "取消失败"); } };
    const canonicalJson = (value) => { if (value === null || typeof value === "boolean" || typeof value === "string") return JSON.stringify(value); if (typeof value === "number") { if (!Number.isFinite(value)) throw new Error("确认数据包含非有限数字"); return JSON.stringify(value); } if (Array.isArray(value)) return "[" + value.map(canonicalJson).join(",") + "]"; if (typeof value === "object") { const compare = (left,right) => { const a = Array.from(left); const b = Array.from(right); for (let i=0;i<Math.min(a.length,b.length);i+=1) { const diff=a[i].codePointAt(0)-b[i].codePointAt(0); if(diff) return diff; } return a.length-b.length; }; return "{" + Object.keys(value).sort(compare).map((key) => JSON.stringify(key)+":"+canonicalJson(value[key])).join(",") + "}"; } throw new Error("确认数据无效"); };
    const sha256 = async (value) => { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(canonicalJson(value))); return "sha256:" + Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2,"0")).join(""); };
    const pendingConfirmation = async (processId, bearer) => { const response = await fetch("/v1/trigger-processes/" + encodeURIComponent(processId) + "/confirmations/pending", { headers:{ authorization:"Bearer " + bearer, accept:"application/json" }, cache:"no-store" }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error((body && body.message ? body.message : "确认状态不可读取") + " (HTTP " + response.status + ")"); if (!body || typeof body !== "object" || body.status !== "pending") return null; const preview = body.confirmation_preview; if (!preview || typeof preview !== "object" || Array.isArray(preview)) return body; return { ...body, confirmation_preview:{ ...preview, structured_intent_hash:body.structured_intent_hash } }; };
    const respondToConfirmation = async (processId, challenge, decision, actor, container) => { const buttons = container.querySelectorAll("button"); buttons.forEach((button) => { button.disabled = true; }); try { const bearer = await activeAccessToken(); const responseHash = await sha256({ schema_version:"trigger_confirmation_response_hash_preimage.v1", trigger_process_id:processId, challenge_id:challenge.challenge_id, intent_ref:challenge.intent_ref, intent_version:challenge.intent_version, structured_intent_hash:challenge.structured_intent_hash, policy_input_hash:challenge.policy_input_hash, action_step_ids:challenge.action_step_ids, principal_type:actor.confirmationPrincipalType, principal_id:actor.principalId, decision }); const response = await fetch("/v1/trigger-processes/" + encodeURIComponent(processId) + "/confirmations/" + encodeURIComponent(challenge.challenge_id), { method:"POST", headers:{ authorization:"Bearer " + bearer, "content-type":"application/json", accept:"application/json" }, body:JSON.stringify({ schema_version:"trigger_confirmation_response.v1", decision, expected_intent_version:challenge.intent_version, idempotency_key:newId(), response_hash:responseHash, trace_id:newId() }), cache:"no-store" }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error((body && body.message ? body.message : "确认提交失败") + " (HTTP " + response.status + ")"); container.remove(); append("state", decision === "accept" ? "用户已确认；继续执行" : "用户已拒绝；该操作不会执行"); setConnection(decision === "accept" ? "确认已提交；继续观察" : "已拒绝该操作", decision === "accept" ? "state" : "warn"); if (decision === "accept") void streamEvents(processId, bearer); } catch (error) { buttons.forEach((button) => { button.disabled = false; }); setConnection(error instanceof Error ? error.message : "确认提交失败", "error"); append("error", error instanceof Error ? error.message : "确认提交失败"); } };
    const renderConfirmation = (processId, challenge) => { if (renderedConfirmations.has(challenge.challenge_id)) return; const actor = refreshIdentity(); if (!actor) return; const preview = challenge.confirmation_preview; if (!preview || preview.structured_intent_hash !== challenge.structured_intent_hash || !Array.isArray(preview.action_plan)) { append("error", "确认预览不可验证；操作保持未发送"); setConnection("确认预览不可验证；操作保持未发送", "error"); return; } renderedConfirmations.add(challenge.challenge_id); const card = document.createElement("section"); card.className = "confirmation"; const title = document.createElement("strong"); title.textContent = "需要你的二次确认"; const request = document.createElement("p"); request.textContent = "请求：" + preview.user_need; const plan = document.createElement("ol"); for (const step of preview.action_plan) { if (!step || step.requires_confirmation !== true) continue; const item = document.createElement("li"); const tool = typeof step.candidate_tool === "string" ? " [" + step.candidate_tool + "]" : ""; item.textContent = step.action + tool; plan.append(item); } if (plan.childElementCount === 0) { append("error", "确认预览缺少受确认约束的操作；操作保持未发送"); setConnection("确认预览不可验证；操作保持未发送", "error"); return; } const steps = document.createElement("p"); steps.textContent = "绑定步骤：" + challenge.action_step_ids.join(", ") + "\n到期：" + new Date(challenge.expires_at).toLocaleString("zh-CN", {hour12:false}); const buttons = document.createElement("div"); buttons.className = "buttons"; const accept = document.createElement("button"); accept.type = "button"; accept.textContent = "CONFIRM"; const reject = document.createElement("button"); reject.type = "button"; reject.className = "reject"; reject.textContent = "REJECT"; accept.addEventListener("click", () => { void respondToConfirmation(processId, challenge, "accept", actor, card); }); reject.addEventListener("click", () => { void respondToConfirmation(processId, challenge, "reject", actor, card); }); buttons.append(accept,reject); card.append(title,request,plan,steps,buttons); transcript.append(card); transcript.scrollTop = transcript.scrollHeight; setConnection("等待你的确认；尚未发送或修改任何外部数据", "warn"); };
    const humanEvent = (event) => { const summary = event && event.observation_summary; if (!summary || typeof summary !== "object") return "收到不可解析的事件"; if (event.event_type === "trigger_process.summary") return "process " + summary.phase + "/" + summary.status + (summary.terminal_outcome ? " — " + summary.terminal_outcome : ""); if (event.event_type === "runtime.run.completed") return "runtime completed" + (summary.artifact_ref ? "; final artifact: " + summary.artifact_ref : "; no final artifact"); if (event.event_type === "runtime.run.failed") return "runtime failed" + (summary.error_summary ? ": " + summary.error_summary : ""); if (event.event_type === "trigger_process.outcome_finalized") return "terminal outcome: " + summary.terminal_outcome; if (typeof event.event_type === "string" && event.event_type.startsWith("runtime.tool.")) return "tool trace: " + (summary.tool_name || "unknown") + " — " + (summary.status || event.event_type) + (summary.artifact_ref ? "; durable artifact: " + summary.artifact_ref : ""); return event.event_type + ": " + JSON.stringify(summary); };
    const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
    const fetchFinalResponse = async (processId, bearer, controller) => { let lastError = null; for (let attempt = 0; attempt < 8; attempt += 1) { controller.signal.throwIfAborted(); try { const response = await fetch("/v1/trigger-processes/" + encodeURIComponent(processId) + "/final-response", { headers:{ authorization:"Bearer " + bearer, accept:"application/json" }, signal:controller.signal, cache:"no-store" }); const body = await response.json().catch(() => ({})); if (response.ok && body && body.content_type === "text/plain" && typeof body.content === "string" && body.content) { appendFinal(body.content, processId); setConnection("对话已完成", "state"); return true; } if (response.status !== 409 && response.status !== 503) throw new Error((body && body.message ? body.message : "最终回复不可读取") + " (HTTP " + response.status + ")"); lastError = body && body.message ? body.message : "最终回复仍在准备"; } catch (error) { if (controller.signal.aborted) throw error; lastError = error instanceof Error ? error.message : "最终回复读取失败"; } await wait(Math.min(2_000, 250 * (attempt + 1))); } throw new Error(lastError || "最终回复未在限定时间内就绪"); };
    const followTimerReply = async (originProcessId, bearer) => { if (timerFollowController) timerFollowController.abort(); const controller = new AbortController(); timerFollowController = controller; try { setConnection("提醒已持久化；等待定时任务派发", "state"); for (let attempt = 0; attempt < 3600; attempt += 1) { controller.signal.throwIfAborted(); const response = await fetch("/v1/trigger-processes/" + encodeURIComponent(originProcessId) + "/timer-follow-ups", { headers:{ authorization:"Bearer " + bearer, accept:"application/json" }, signal:controller.signal, cache:"no-store" }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error((body && body.message ? body.message : "定时任务状态不可读取") + " (HTTP " + response.status + ")"); const ids = Array.isArray(body.child_process_ids) ? body.child_process_ids.filter((id) => typeof id === "string" && id) : []; if (ids.length > 0) { const childProcessId = ids[ids.length - 1]; append("pai", "⏰ 提醒已到期，正在按到期时刻查询并整理结果…"); append("system", "timer dispatched; process: " + childProcessId); await streamEvents(childProcessId, bearer); return; } await wait(1000); } throw new Error("等待定时任务派发超时"); } catch (error) { if (controller.signal.aborted) return; setConnection(error instanceof Error ? error.message : "定时任务跟踪失败", "error"); append("error", error instanceof Error ? error.message : "定时任务跟踪失败"); } finally { if (timerFollowController === controller) timerFollowController = null; } };
    const streamEvents = async (processId, bearer) => { if (streamController) streamController.abort(); const controller = new AbortController(); streamController = controller; let after = 0; let finalResultShown = false; let timerReminderRequested = false; try { const response = await fetch("/v1/trigger-processes/" + encodeURIComponent(processId) + "/events?start_after_append_sequence_no=" + after, { headers:{ authorization:"Bearer " + bearer, accept:"text/event-stream" }, signal:controller.signal, cache:"no-store" }); if (!response.ok || !response.body) { const detail = await response.text(); throw new Error("无法订阅运行事件 (" + response.status + "): " + detail.slice(0,300)); } setConnection("正在观察 process " + processId, "state"); const reader = response.body.getReader(); const decoder = new TextDecoder(); let pending = ""; for (;;) { const part = await reader.read(); if (part.done) break; pending += decoder.decode(part.value, {stream:true}); let cut; while ((cut = pending.indexOf("\n\n")) !== -1) { const frame = pending.slice(0, cut); pending = pending.slice(cut + 2); const data = frame.split("\n").filter((line) => line.startsWith("data:")).map((line) => line.slice(5).trim()).join("\n"); if (!data) continue; try { const event = JSON.parse(data); if (Number.isSafeInteger(event.append_sequence_no)) after = event.append_sequence_no; append("state", humanEvent(event)); recordResearchEvent(processId, event); const summary = event && event.observation_summary; if (event.event_type === "runtime.tool.requested" && summary && (summary.tool_name === "timer.remind_after" || summary.tool_name === "timer.remind_at")) timerReminderRequested = true; if (event.event_type === "trigger_process.summary" && summary && summary.status === "waiting") { const challenge = await pendingConfirmation(processId, bearer); if (challenge !== null) { renderConfirmation(processId, challenge); controller.abort(); return; } } const completed = event.event_type === "runtime.run.completed" || (event.event_type === "trigger_process.summary" && summary && summary.status === "completed"); if (completed && !finalResultShown) { finalResultShown = true; await fetchFinalResponse(processId, bearer, controller); if (timerReminderRequested) { append("system", "提醒已创建；将在到期后继续显示 PAI 的回复。"); void followTimerReply(processId, bearer); } controller.abort(); return; } if (event.event_type === "trigger_process.summary" && summary && summary.observation_finalized) { setConnection("流程已完成，但没有可展示的文本回复", "warn"); controller.abort(); return; } } catch (error) { if (controller.signal.aborted) return; append("warn", error instanceof Error ? error.message : "收到未解析事件"); } } } setConnection("事件流已关闭", "warn"); } catch (error) { if (controller.signal.aborted) return; setConnection(error instanceof Error ? error.message : "事件流失败", "error"); append("error", error instanceof Error ? error.message : "事件流失败"); } finally { if (streamController === controller) streamController = null; } };
    form.addEventListener("submit", async (event) => { event.preventDefault(); const text = message.value.trim(); const actor = refreshIdentity(); if (!actor) { append("error", "请先登录 Supabase"); email.focus(); return; } if (!text) return; send.disabled = true; setConnection("提交中…"); append("you", "you> " + text); try { const bearer = await activeAccessToken(); const body = { workspace_id:"demo-workspace", bot_id:"demo-bot", owner_agent_id:"demo-owner", deployment_environment:"local", release_channel:"stable", source:"chat", actor_type:actor.actorType, actor_id:actor.principalId, payload:{message:text}, dedupe_key:"chat:" + newId() }; const response = await fetch("/v1/triggers", { method:"POST", headers:{ authorization:"Bearer " + bearer, "content-type":"application/json", accept:"application/json" }, body:JSON.stringify(body), cache:"no-store" }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error((result && result.message ? result.message : "Trigger 被拒绝") + " (HTTP " + response.status + ")"); const details = result.details || {}; const processId = details.trigger_process_id || details.canonical_process_id; append("state", "admission: " + result.code + (details.reason_code ? " — " + details.reason_code : "")); message.value = ""; if (typeof processId === "string" && processId) { processMessages.set(processId, text); append("system", "process: " + processId); watchPendingConfirmation(processId); void streamEvents(processId, bearer); } else setConnection("已处理，但没有可观察的 process id", "warn"); } catch (error) { append("error", error instanceof Error ? error.message : "提交失败"); setConnection("提交失败", "error"); } finally { send.disabled = authSession === null; message.focus(); } });
    message.addEventListener("keydown", (event) => { if (event.key === "Enter" && (event.metaKey || event.ctrlKey)) { event.preventDefault(); form.requestSubmit(); } });
    signIn.addEventListener("click", () => { void login(); }); password.addEventListener("keydown", (event) => { if (event.key === "Enter") { event.preventDefault(); void login(); } }); signOut.addEventListener("click", () => { const config = authConfig; const bearer = authSession && authSession.access_token; clearSession("已退出；当前标签页的 Supabase 会话已清除"); if (config && bearer) void fetch(config.auth_origin + "/auth/v1/logout", { method:"POST", headers:{ apikey:config.publishable_key, authorization:"Bearer " + bearer }, cache:"no-store" }).then((response) => { if (!response.ok) append("warn", "本机会话已清除；Supabase 端退出需要稍后重试。"); }).catch(() => append("warn", "本机会话已清除；Supabase 端退出暂不可用。")); }); cancelProcess.addEventListener("click", () => { const processId = cancelProcessId.value.trim(); if (!processId) { append("error", "请先输入 process ID"); cancelProcessId.focus(); return; } if (!refreshIdentity()) { append("error", "请先登录 Supabase"); email.focus(); return; } cancelConfirmation.hidden = false; setConnection("请再次确认取消 " + processId, "warn"); }); cancelConfirm.addEventListener("click", () => { void cancelProcessWithConfirmation(); }); cancelAbort.addEventListener("click", () => { resetCancellationConfirmation(); setConnection("已保留当前流程", "state"); });
    resumeProcess.addEventListener("click", () => { const processId = resumeProcessId.value.trim(); if (!processIdPattern.test(processId)) { append("error", "请输入有效的 process ID"); resumeProcessId.focus(); return; } if (!refreshIdentity()) { append("error", "请先登录 Supabase"); email.focus(); return; } setConnection("正在恢复待确认流程", "state"); watchPendingConfirmation(processId); });
    // A confirmation can be persisted before the SSE reader has received its
    // next summary frame (or while a tab is being refreshed).  Keep only the
    // opaque process id in this browser session and poll the same-authorized
    // pending-confirmation endpoint until the card is rendered.  The JWT is
    // never copied out of the page and no external action is performed here.
    const activeProcessKey = "pai.local-chat-console.active-process.v1";
    const processIdPattern = /^[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}$/iu;
    let confirmationPollController = null;
    const watchPendingConfirmation = (processId) => { if (!processIdPattern.test(processId) || !refreshIdentity()) return; sessionStorage.setItem(activeProcessKey, processId); if (confirmationPollController) confirmationPollController.abort(); const controller = new AbortController(); confirmationPollController = controller; void (async () => { let lastError = null; for (let attempt = 0; attempt < 900; attempt += 1) { if (controller.signal.aborted) return; try { const bearer = await activeAccessToken(); const challenge = await pendingConfirmation(processId, bearer); if (challenge !== null) { renderConfirmation(processId, challenge); return; } } catch (error) { lastError = error; } await wait(1_000); } if (!controller.signal.aborted && lastError instanceof Error) append("warn", "确认状态暂不可读取；请刷新页面后重试"); })().finally(() => { if (confirmationPollController === controller) confirmationPollController = null; }); };
    rememberProcessFromLine = (value) => { const match = /\\bprocess: ([0-9a-f-]{36})\\b/iu.exec(value); if (match) watchPendingConfirmation(match[1]); if (/用户已确认；继续执行|用户已拒绝；该操作不会执行|terminal outcome:/u.test(value)) sessionStorage.removeItem(activeProcessKey); };
    new MutationObserver((records) => { for (const record of records) for (const node of record.addedNodes) rememberProcessFromLine(node.textContent || ""); }).observe(transcript, { childList:true });
    const restoredProcessId = sessionStorage.getItem(activeProcessKey); if (restoredProcessId) watchPendingConfirmation(restoredProcessId);
    sessionStorage.removeItem(legacyTokenKey); append("system", "PAI local chat console ready."); append("system", "使用 Supabase 邮箱和密码登录后，消息会作为 chat Trigger 进入完整 PAI 流程。"); void loadAuthConfiguration();
  })();
  </script>
</body>
</html>`;
}

export { LOCAL_CHAT_AUTH_CONFIG_ROUTE_V1, LOCAL_CHAT_CONSOLE_ROUTE_V1 };
