import {
  defineOwnerRepositoryContractV1,
  ownerFunctionSignatureV1,
  type OwnerRepositoryPortV1,
  type OwnerUnitOfWorkPortV1,
} from "@pai/persistence";

export const TIMER_REPOSITORY_CONTRACT_V1 = defineOwnerRepositoryContractV1({
  contract_version: "owner_repository_contract.v1",
  owner_service: "timer_trigger_app",
  schema: "timer",
  app_role: "pai_timer_app",
  fresh_migrations: ["0300_timer"],
  manifest_source: "services/timer-trigger-app/src/db/permission-manifest.v1.ts",
  generated_permission_sql: [
    "pai-infra/supabase/generated/permissions/0300_timer.sql",
  ],
  tables: [
    "timer_schedules",
    "timer_scanner_checkpoints",
    "timer_occurrences",
    "timer_dispatch_attempts",
    "timer_audit_logs",
    "timer_command_requests",
    "timer_query_requests",
    "timer_event_outbox",
    "timer_event_inbox",
    "timer_event_dlq",
    "timer_catch_up_batches",
  ],
    table_permissions: [
    {
      table_name: "timer_schedules",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","name","message","status","schedule_type","rrule","fire_at","timezone","end_time","payload","catch_up","next_fire_at","schedule_version","created_by","created_by_runtime_run_id","created_by_trigger_process_id","client_request_id","idempotency_key","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "pointer_cas",
    },
    {
      table_name: "timer_scanner_checkpoints",
      select_columns: ["id","scanner_name","last_scanned_until","locked_by","locked_until","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "pointer_cas",
    },
    {
      table_name: "timer_occurrences",
      select_columns: ["id","schedule_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","occurrence_key","occurrence_version","scheduled_fire_at","effective_fire_at","local_date","timezone","schedule_end_time","schedule_version","dispatch_payload","dispatch_payload_hash","payload_schema_version","status","trigger_id","trigger_process_id","dedupe_key","error","next_dispatch_at","catch_up_batch_id","is_catch_up","locked_by","locked_until","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "timer_dispatch_attempts",
      select_columns: ["id","occurrence_id","expected_occurrence_version","resulting_occurrence_version","dispatch_generation","claim_token","status","request","response","error","next_retry_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "timer_audit_logs",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","schedule_id","occurrence_id","event_type","actor","reason","source_ref","evidence_refs","previous_state","next_state","schema_version","payload","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "timer_command_requests",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","runtime_run_id","trigger_process_id","method","schedule_id","client_request_id","idempotency_key","request_hash","status","request","response","error","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "timer_query_requests",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","runtime_run_id","method","schedule_id","request_hash","response_hash","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "timer_event_outbox",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","aggregate_id","event_type","schema_version","producer","occurred_at","idempotency_key","trace_id","payload","payload_hash","target","status","next_retry_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "timer_event_inbox",
      select_columns: ["id","source","idempotency_key","payload_hash","processed_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "timer_event_dlq",
      select_columns: ["id","source_event_id","event_type","payload","last_error","failed_at","resolved_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "timer_catch_up_batches",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","status","cursor_occurrence_id","last_occurrence_id","last_trigger_process_id","deadline_at","started_at","completed_at","reason_code","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    ],
  mutable_writers: [
    "cas_timer_schedule_v1",
    "advance_timer_scanner_checkpoint_v1",
    "transition_timer_occurrence_v1",
    "transition_timer_catch_up_batch_v1",
    "claim_timer_event_outbox_v1",
    "ack_timer_event_outbox_v1",
  ],
    function_signatures: [
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "cas_timer_schedule_v1",
      primary_table: "timer_schedules",
      writer_kind: "pointer_cas",
      arguments: [
        ["p_schedule_id", "text"],
        ["p_expected_schedule_version", "bigint"],
        ["p_schedule_patch", "jsonb"],
        ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["timer_schedules"],
      writes_tables: ["timer_schedules", "timer_audit_logs", "timer_event_outbox"],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "advance_timer_scanner_checkpoint_v1",
      primary_table: "timer_scanner_checkpoints",
      writer_kind: "pointer_cas",
      arguments: [
        ["p_scanner_name", "text"],
        ["p_expected_scanned_until", "timestamptz"],
        ["p_next_scanned_until", "timestamptz"],
        ["p_lock_token", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["timer_scanner_checkpoints"],
      writes_tables: ["timer_scanner_checkpoints", "timer_audit_logs"],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "transition_timer_occurrence_v1",
      primary_table: "timer_occurrences",
      writer_kind: "state_transition",
      arguments: [
        ["p_occurrence_id", "text"],
        ["p_expected_occurrence_version", "bigint"],
        ["p_expected_status", "text"],
        ["p_next_status", "text"],
        ["p_dispatch", "jsonb"],
        ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["timer_occurrences", "timer_schedules"],
      writes_tables: [
        "timer_occurrences", "timer_dispatch_attempts", "timer_audit_logs",
        "timer_command_requests", "timer_query_requests", "timer_event_inbox",
        "timer_event_outbox",
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "transition_timer_catch_up_batch_v1",
      primary_table: "timer_catch_up_batches",
      writer_kind: "state_transition",
      arguments: [
        ["p_batch_id", "text"],
        ["p_expected_status", "text"],
        ["p_next_status", "text"],
        ["p_batch_patch", "jsonb"],
        ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["timer_catch_up_batches", "timer_occurrences"],
      writes_tables: ["timer_catch_up_batches", "timer_audit_logs", "timer_event_outbox"],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "claim_timer_event_outbox_v1",
      primary_table: "timer_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [
        ["p_worker_id", "text"], ["p_limit", "integer"],
        ["p_lease_seconds", "integer"], ["p_now", "timestamptz"],
      ],
      reads_tables: ["timer_event_outbox"],
      writes_tables: ["timer_event_outbox"],
      returns: "setof jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "ack_timer_event_outbox_v1",
      primary_table: "timer_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [
        ["p_outbox_id", "text"], ["p_claim_token", "text"],
        ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"],
        ["p_error", "jsonb"], ["p_now", "timestamptz"],
      ],
      reads_tables: ["timer_event_outbox"],
      writes_tables: ["timer_event_outbox", "timer_event_dlq"],
      returns: "jsonb",
    }),
    ],
  append_only_tables: [
    "timer_audit_logs",
    "timer_command_requests",
    "timer_query_requests",
    "timer_event_outbox",
    "timer_event_inbox",
    "timer_event_dlq",
  ],
  outbox_tables: ["timer_event_outbox"],
  inbox_tables: ["timer_event_inbox"],
  dlq_tables: ["timer_event_dlq"],
  object_metadata_tables: [],
} as const);

export interface TimerRepositoryPortV1
  extends OwnerRepositoryPortV1<typeof TIMER_REPOSITORY_CONTRACT_V1> {}

export type TimerUnitOfWorkPortV1 = OwnerUnitOfWorkPortV1<
  "timer_trigger_app",
  Readonly<{ owner: TimerRepositoryPortV1 }>
>;
