import {
  TIMER_DATABASE_COLUMNS_V1,
  TIMER_DATABASE_INDEXES_V1,
  TIMER_DATABASE_CHECKS_V1,
  TIMER_DATABASE_FUNCTIONS_V1,
  TIMER_DATABASE_TRIGGERS_V1,
  TIMER_DATABASE_UNIQUE_CONSTRAINTS_V1,
  TIMER_FOREIGN_KEYS_V1,
} from "./catalog-snapshot.generated.v1.js";
import { TIMER_WRITER_ARTIFACTS_V1 } from "./writer-artifacts.generated.v1.js";
import { OWNER_DURABLE_EVENT_TYPES_V1 } from "@pai/contracts";
import { TIMER_AUDIT_EVENT_TYPES_V1 } from "@pai/contracts/timer/timer-event.v1";
import {
  defineOwnerRepositoryContractV1,
  ownerDlqResolutionContractV1,
  ownerEventingReconciliationContractV1,
  ownerEventingTransportEpochActivationSignatureV1,
  ownerEventingTransportEpochTablePermissionV1,
  ownerFunctionSignatureV1,
  type OwnerRepositoryPortV1,
  type OwnerUnitOfWorkPortV1,
} from "@pai/persistence";

const TIMER_DLQ_RESOLUTION_V1 = ownerDlqResolutionContractV1(
  "timer",
  "timer_event_dlq",
);
const TIMER_EVENT_RECONCILIATION_V1 =
  ownerEventingReconciliationContractV1("timer", "timer_event_outbox");

export const TIMER_REPOSITORY_CONTRACT_V1 = defineOwnerRepositoryContractV1({
  contract_version: "owner_repository_contract.v1",
  owner_service: "timer_trigger_app",
  schema: "timer",
  app_role: "pai_timer_app",
  fresh_migrations: ["0300_timer"],
  manifest_source: "services/timer-trigger-app/src/db/permission-manifest.v1.ts",
  generated_permission_sql: [
    "pai-infra/supabase/generated/permissions/0300_timer.sql",
  ],
  tables: [
    "timer_schedules",
    "timer_scanner_checkpoints",
    "timer_occurrences",
    "timer_dispatch_attempts",
    "timer_audit_logs",
    "timer_command_requests",
    "timer_query_requests",
    "timer_event_outbox",
    "timer_event_inbox",
    "timer_event_dlq",
    TIMER_DLQ_RESOLUTION_V1.resolution_table,
    "timer_catch_up_batches",
    "eventing_transport_epochs",
  ],
    table_permissions: [
    {
      table_name: "timer_schedules",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","name","message","status","schedule_type","rrule","fire_at","timezone","end_time","payload","catch_up","max_catch_up_window_seconds","max_catch_up_occurrences","next_fire_at","schedule_version","created_by","created_by_runtime_run_id","created_by_trigger_process_id","client_request_id","idempotency_key","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "timer_scanner_checkpoints",
      select_columns: ["id","scanner_name","last_scanned_until","locked_by","locked_until","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "pointer_cas",
    },
    {
      table_name: "timer_occurrences",
      select_columns: ["id","schedule_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","occurrence_key","occurrence_version","scheduled_fire_at","effective_fire_at","local_date","local_time","timezone","schedule_end_time","schedule_version","dispatch_payload","dispatch_payload_hash","payload_schema_version","status","attempt_count","dispatch_generation","claim_token","trigger_id","trigger_process_id","dedupe_key","error","next_dispatch_at","cancel_requested_at","catch_up_batch_id","is_catch_up","locked_by","locked_until","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "timer_dispatch_attempts",
      select_columns: ["id","occurrence_id","attempt_no","expected_occurrence_version","resulting_occurrence_version","dispatch_generation","claim_token","status","request","response","error","next_retry_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "timer_audit_logs",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","schedule_id","occurrence_id","event_type","actor","reason","source_ref","evidence_refs","previous_state","next_state","schema_version","payload","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "timer_command_requests",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","runtime_run_id","trigger_process_id","method","schedule_id","client_request_id","idempotency_key","request_hash","status","request","response","error","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "timer_query_requests",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","runtime_run_id","method","schedule_id","request_hash","response_hash","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "timer_event_outbox",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","aggregate_id","event_type","schema_version","producer","occurred_at","idempotency_key","trace_id","payload","payload_hash","target","status","attempt_count","next_retry_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "timer_event_inbox",
      select_columns: ["id","source","event_id","scope_fingerprint","idempotency_key","payload_hash","semantic_hash","processed_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "timer_event_dlq",
      select_columns: ["id","source_event_id","event_type","payload","last_error","failed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    TIMER_DLQ_RESOLUTION_V1.table_permission,
    {
      table_name: "timer_catch_up_batches",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","status","cursor_occurrence_id","last_occurrence_id","last_trigger_process_id","deadline_at","timeout_seconds","policy_snapshot","started_at","completed_at","reason_code","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    ownerEventingTransportEpochTablePermissionV1(),
  ],
  mutable_writers: [
    ...TIMER_DLQ_RESOLUTION_V1.mutable_writers,
    ...TIMER_EVENT_RECONCILIATION_V1.mutable_writers,
    "create_timer_schedule_v1",
    "cas_timer_schedule_v1",
    "advance_timer_scanner_checkpoint_v1",
    "enqueue_timer_occurrence_v1",
    "claim_timer_occurrence_v1",
    "transition_timer_occurrence_v1",
    "record_timer_dispatch_attempt_v1",
    "record_timer_audit_v1",
    "record_timer_command_request_v1",
    "transition_timer_command_request_v1",
    "record_timer_query_request_v1",
    "create_timer_catch_up_batch_v1",
    "transition_timer_catch_up_batch_v1",
    "timeout_timer_catch_up_batch_v1",
    "claim_timer_event_outbox_v1",
    "ack_timer_event_outbox_v1",
    "activate_eventing_transport_epoch_v1",
  ],
  function_signatures: [
    ...TIMER_DLQ_RESOLUTION_V1.function_signatures,
    ...TIMER_EVENT_RECONCILIATION_V1.function_signatures,
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "create_timer_schedule_v1",
      primary_table: "timer_schedules",
      writer_kind: "state_transition",
      arguments: [
        ["p_schedule_id", "text"],
        ["p_command_request_id", "text"],
        ["p_schedule", "jsonb"],
        ["p_command_request", "jsonb"],
        ["p_idempotency_key", "text"],
        ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["timer_schedules", "timer_command_requests"],
      writes_tables: [
        "timer_schedules",
        "timer_command_requests",
        "timer_audit_logs",
        "timer_event_outbox",
      ],
      effects: [
        { table_name: "timer_schedules", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "timer_command_requests", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "timer_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "timer_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "cas_timer_schedule_v1",
      primary_table: "timer_schedules",
      writer_kind: "state_transition",
      arguments: [
        ["p_schedule_id", "text"],
        ["p_expected_schedule_version", "bigint"],
        ["p_schedule_patch", "jsonb"],
        ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["timer_schedules"],
      writes_tables: ["timer_schedules", "timer_audit_logs", "timer_event_outbox"],
      effects: [
        { table_name: "timer_schedules", operation: "transition", concurrency_control: "expected_version" },
        { table_name: "timer_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "timer_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "advance_timer_scanner_checkpoint_v1",
      primary_table: "timer_scanner_checkpoints",
      writer_kind: "pointer_cas",
      arguments: [
        ["p_scanner_checkpoint_id", "text"],
        ["p_scanner_name", "text"],
        ["p_expected_scanned_until", "timestamptz"],
        ["p_next_scanned_until", "timestamptz"],
        ["p_lock_token", "text"],
        ["p_workspace_id", "text"],
        ["p_bot_id", "text"],
        ["p_owner_agent_id", "text"],
        ["p_deployment_environment", "text"],
        ["p_release_channel", "text"],
        ["p_expected_schedule_versions", "jsonb"],
        ["p_schedule_transitions", "jsonb"],
        ["p_occurrences", "jsonb"],
        ["p_catch_up_batches", "jsonb"],
        ["p_idempotency_key", "text"],
        ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: [
        "timer_scanner_checkpoints",
        "timer_schedules",
        "timer_occurrences",
        "timer_catch_up_batches",
      ],
      writes_tables: [
        "timer_scanner_checkpoints",
        "timer_schedules",
        "timer_occurrences",
        "timer_catch_up_batches",
        "timer_audit_logs",
        "timer_event_outbox",
      ],
      effects: [
        { table_name: "timer_scanner_checkpoints", operation: "cas", concurrency_control: "expected_version" },
        { table_name: "timer_schedules", operation: "transition", concurrency_control: "expected_version" },
        { table_name: "timer_occurrences", operation: "enqueue", concurrency_control: "idempotency_key" },
        {
          table_name: "timer_catch_up_batches",
          operation: "append",
          concurrency_control: "database_row_lock",
          lock_table_name: "timer_scanner_checkpoints",
        },
        { table_name: "timer_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "timer_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "enqueue_timer_occurrence_v1",
      primary_table: "timer_occurrences",
      writer_kind: "state_transition",
      arguments: [["p_occurrence_id", "text"], ["p_schedule_id", "text"], ["p_expected_schedule_version", "bigint"], ["p_occurrence", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["timer_schedules", "timer_occurrences"],
      writes_tables: [
        "timer_occurrences",
        "timer_schedules",
        "timer_audit_logs",
        "timer_event_outbox",
      ],
      effects: [
        { table_name: "timer_occurrences", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "timer_schedules", operation: "transition", concurrency_control: "expected_version" },
        { table_name: "timer_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "timer_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "claim_timer_occurrence_v1",
      primary_table: "timer_occurrences",
      writer_kind: "state_transition",
      arguments: [
        ["p_occurrence_id", "text"],
        ["p_expected_occurrence_version", "bigint"],
        ["p_expected_schedule_version", "bigint"],
        ["p_expected_status", "text"],
        ["p_worker_id", "text"],
        ["p_lease_seconds", "integer"],
        ["p_now", "timestamptz"],
        ["p_trace_id", "text"],
      ],
      reads_tables: [
        "timer_occurrences",
        "timer_schedules",
        "timer_catch_up_batches",
      ],
      writes_tables: ["timer_occurrences", "timer_audit_logs"],
      effects: [
        { table_name: "timer_occurrences", operation: "transition", concurrency_control: "lease_fence" },
        { table_name: "timer_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "transition_timer_occurrence_v1",
      primary_table: "timer_occurrences",
      writer_kind: "state_transition",
      arguments: [
        ["p_occurrence_id", "text"],
        ["p_expected_occurrence_version", "bigint"],
        ["p_expected_dispatch_generation", "bigint"],
        ["p_expected_status", "text"],
        ["p_next_status", "text"],
        ["p_dispatch", "jsonb"],
        ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: [
        "timer_occurrences",
        "timer_schedules",
        "timer_catch_up_batches",
      ],
      writes_tables: [
        "timer_occurrences",
        "timer_dispatch_attempts",
        "timer_schedules",
        "timer_catch_up_batches",
        "timer_audit_logs",
        "timer_event_outbox",
      ],
      effects: [
        { table_name: "timer_occurrences", operation: "transition", concurrency_control: "expected_version" },
        { table_name: "timer_dispatch_attempts", operation: "append", concurrency_control: "generation_fence" },
        { table_name: "timer_schedules", operation: "transition", concurrency_control: "database_row_lock" },
        { table_name: "timer_catch_up_batches", operation: "transition", concurrency_control: "database_row_lock" },
        { table_name: "timer_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "timer_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "record_timer_dispatch_attempt_v1",
      primary_table: "timer_dispatch_attempts",
      writer_kind: "immutable_append",
      arguments: [
        ["p_dispatch_attempt_id", "text"],
        ["p_occurrence_id", "text"],
        ["p_expected_occurrence_version", "bigint"],
        ["p_dispatch_generation", "bigint"],
        ["p_claim_token", "text"],
        ["p_attempt", "jsonb"],
        ["p_idempotency_key", "text"],
        ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["timer_occurrences", "timer_dispatch_attempts"],
      writes_tables: ["timer_dispatch_attempts"],
      effects: [
        { table_name: "timer_dispatch_attempts", operation: "append", concurrency_control: "lease_fence" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "record_timer_audit_v1",
      primary_table: "timer_audit_logs",
      writer_kind: "immutable_append",
      arguments: [
        ["p_audit_id", "text"],
        ["p_audit", "jsonb"],
        ["p_idempotency_key", "text"],
        ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["timer_schedules", "timer_occurrences"],
      writes_tables: ["timer_audit_logs"],
      effects: [
        { table_name: "timer_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "record_timer_command_request_v1",
      primary_table: "timer_command_requests",
      writer_kind: "state_transition",
      arguments: [["p_command_request_id", "text"], ["p_command_request", "jsonb"], ["p_source_event", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_payload_hash", "text"], ["p_semantic_hash", "text"], ["p_scope_fingerprint", "text"], ["p_trace_id", "text"]],
      reads_tables: ["timer_command_requests", "timer_schedules", "timer_event_inbox"],
      writes_tables: ["timer_command_requests", "timer_event_inbox", "timer_event_dlq", "timer_audit_logs", "timer_event_outbox"],
      effects: [
        { table_name: "timer_command_requests", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "timer_event_inbox", operation: "append", concurrency_control: "durable_event_identity" },
        { table_name: "timer_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "timer_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "timer_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "transition_timer_command_request_v1",
      primary_table: "timer_command_requests",
      writer_kind: "state_transition",
      arguments: [["p_command_request_id", "text"], ["p_expected_status", "text"], ["p_expected_updated_at", "timestamptz"], ["p_next_status", "text"], ["p_result", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["timer_command_requests"],
      writes_tables: ["timer_command_requests", "timer_audit_logs", "timer_event_outbox"],
      effects: [
        { table_name: "timer_command_requests", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "timer_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "timer_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "record_timer_query_request_v1",
      primary_table: "timer_query_requests",
      writer_kind: "immutable_append",
      arguments: [["p_query_request_id", "text"], ["p_query_request", "jsonb"], ["p_source_event", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_payload_hash", "text"], ["p_semantic_hash", "text"], ["p_scope_fingerprint", "text"], ["p_trace_id", "text"]],
      reads_tables: ["timer_schedules", "timer_event_inbox"],
      writes_tables: ["timer_query_requests", "timer_event_inbox", "timer_event_dlq", "timer_audit_logs", "timer_event_outbox"],
      effects: [
        { table_name: "timer_query_requests", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "timer_event_inbox", operation: "append", concurrency_control: "durable_event_identity" },
        { table_name: "timer_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "timer_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "timer_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "create_timer_catch_up_batch_v1",
      primary_table: "timer_catch_up_batches",
      writer_kind: "state_transition",
      arguments: [
        ["p_scanner_checkpoint_id", "text"],
        ["p_batch_id", "text"],
        ["p_batch", "jsonb"],
        ["p_occurrence_ids", "jsonb"],
        ["p_expected_occurrence_versions", "jsonb"],
        ["p_idempotency_key", "text"],
        ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: [
        "timer_scanner_checkpoints",
        "timer_catch_up_batches",
        "timer_occurrences",
        "timer_schedules",
      ],
      writes_tables: [
        "timer_catch_up_batches",
        "timer_occurrences",
        "timer_audit_logs",
        "timer_event_outbox",
      ],
      effects: [
        {
          table_name: "timer_catch_up_batches",
          operation: "append",
          concurrency_control: "database_row_lock",
          lock_table_name: "timer_scanner_checkpoints",
        },
        { table_name: "timer_occurrences", operation: "transition", concurrency_control: "expected_version" },
        { table_name: "timer_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "timer_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "transition_timer_catch_up_batch_v1",
      primary_table: "timer_catch_up_batches",
      writer_kind: "state_transition",
      arguments: [
        ["p_batch_id", "text"],
        ["p_expected_status", "text"],
        ["p_expected_continuation", "jsonb"],
        ["p_next_status", "text"],
        ["p_batch_patch", "jsonb"],
        ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: [
        "timer_catch_up_batches",
        "timer_occurrences",
        "timer_schedules",
      ],
      writes_tables: [
        "timer_catch_up_batches",
        "timer_occurrences",
        "timer_schedules",
        "timer_audit_logs",
        "timer_event_outbox",
      ],
      effects: [
        { table_name: "timer_catch_up_batches", operation: "transition", concurrency_control: "database_row_lock" },
        { table_name: "timer_occurrences", operation: "transition", concurrency_control: "database_row_lock" },
        { table_name: "timer_schedules", operation: "transition", concurrency_control: "database_row_lock" },
        { table_name: "timer_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "timer_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "timeout_timer_catch_up_batch_v1",
      primary_table: "timer_catch_up_batches",
      writer_kind: "state_transition",
      arguments: [
        ["p_batch_id", "text"],
        ["p_expected_status", "text"],
        ["p_expected_deadline_at", "timestamptz"],
        ["p_timed_out_at", "timestamptz"],
        ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: [
        "timer_catch_up_batches",
        "timer_occurrences",
        "timer_schedules",
      ],
      writes_tables: [
        "timer_catch_up_batches",
        "timer_occurrences",
        "timer_schedules",
        "timer_audit_logs",
      ],
      effects: [
        { table_name: "timer_catch_up_batches", operation: "transition", concurrency_control: "database_row_lock" },
        { table_name: "timer_occurrences", operation: "transition", concurrency_control: "database_row_lock" },
        { table_name: "timer_schedules", operation: "transition", concurrency_control: "database_row_lock" },
        { table_name: "timer_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "claim_timer_event_outbox_v1",
      primary_table: "timer_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [
        ["p_worker_id", "text"], ["p_limit", "integer"],
        ["p_lease_seconds", "integer"], ["p_now", "timestamptz"],
        ["p_current_transport_epoch", "text"],
        ["p_current_transport_generation", "bigint"],
      ],
      reads_tables: ["timer_event_outbox", "eventing_transport_epochs"],
      writes_tables: ["timer_event_outbox"],
      effects: [
        { table_name: "timer_event_outbox", operation: "claim", concurrency_control: "lease_fence" },
      ],
      returns: "setof jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "timer",
      function_name: "ack_timer_event_outbox_v1",
      primary_table: "timer_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [
        ["p_outbox_id", "text"], ["p_claim_token", "text"],
        ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"],
        ["p_error", "jsonb"], ["p_transport_ref", "text"], ["p_transport_epoch", "text"],
        ["p_transport_generation", "bigint"],
        ["p_current_transport_epoch", "text"],
        ["p_current_transport_generation", "bigint"],
        ["p_now", "timestamptz"],
      ],
      reads_tables: ["timer_event_outbox", "eventing_transport_epochs"],
      writes_tables: ["timer_event_outbox", "timer_event_dlq"],
      effects: [
        { table_name: "timer_event_outbox", operation: "ack", concurrency_control: "lease_fence" },
        { table_name: "timer_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerEventingTransportEpochActivationSignatureV1("timer"),
    ],
  // The generator imports this module under an explicit cache-busting
  // `?writer=` URL so it can attest a changed signature before the new
  // artifact exists. Normal application imports never carry that marker
  // and therefore remain fail-closed on exact artifact drift.
  ...(new URL(import.meta.url).searchParams.has("writer")
    ? {}
    : { writer_artifacts: TIMER_WRITER_ARTIFACTS_V1 }),
  database_columns: TIMER_DATABASE_COLUMNS_V1,
  database_checks: TIMER_DATABASE_CHECKS_V1,
  database_functions: TIMER_DATABASE_FUNCTIONS_V1,
  database_triggers: TIMER_DATABASE_TRIGGERS_V1,
  database_unique_constraints: TIMER_DATABASE_UNIQUE_CONSTRAINTS_V1,
  database_indexes: TIMER_DATABASE_INDEXES_V1,
  foreign_key_snapshot: {
    status: "complete",
    source: "Database Design revision 508 / fresh 0300_timer canonical DDL",
  },
  foreign_keys: TIMER_FOREIGN_KEYS_V1,
  append_only_tables: [
    "timer_audit_logs",
    "timer_query_requests",
    "timer_event_outbox",
    "timer_event_inbox",
    "timer_event_dlq",
    TIMER_DLQ_RESOLUTION_V1.resolution_table,
  ],
  outbox_tables: ["timer_event_outbox"],
  inbox_tables: ["timer_event_inbox"],
  dlq_tables: ["timer_event_dlq"],
  dlq_resolutions: [TIMER_DLQ_RESOLUTION_V1.binding],
  object_metadata_tables: [],
} as const);

export interface TimerRepositoryPortV1
  extends OwnerRepositoryPortV1<typeof TIMER_REPOSITORY_CONTRACT_V1> {}

export type TimerUnitOfWorkPortV1 = OwnerUnitOfWorkPortV1<
  "timer_trigger_app",
  Readonly<{ owner: TimerRepositoryPortV1 }>
>;
