import {
  defineOwnerRepositoryContractV1,
  ownerFunctionSignatureV1,
  type OwnerRepositoryPortV1,
  type OwnerUnitOfWorkPortV1,
} from "@pai/persistence";

export const ACTION_RUNTIME_REPOSITORY_CONTRACT_V1 =
  defineOwnerRepositoryContractV1({
    contract_version: "owner_repository_contract.v1",
    owner_service: "action_runtime",
    schema: "action_runtime",
    app_role: "pai_action_runtime_app",
    fresh_migrations: ["0200_action_runtime"],
    manifest_source: "services/action-runtime/src/db/permission-manifest.v1.ts",
    generated_permission_sql: [
      "pai-infra/supabase/generated/permissions/0200_action_runtime.sql",
    ],
    tables: [
      "runtime_runs",
      "runtime_policy_input_artifacts",
      "runtime_start_attempts",
      "runtime_policy_snapshots",
      "runtime_run_leases",
      "runtime_events",
      "runtime_event_outbox",
      "runtime_event_inbox",
      "runtime_event_dlq",
      "tool_invocations",
      "runtime_control_signals",
      "runtime_control_tombstones",
      "runtime_permissions",
      "runtime_artifacts",
      "tool_permission_profile_revisions",
      "tool_permission_profile_current",
      "runtime_start_reservation_validations",
    ],
    table_permissions: [
    {
      table_name: "runtime_runs",
      select_columns: ["id","trigger_process_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","start_fence_generation","status","cancellation_status","runtime_provider","model","intent_ref","intent_version","structured_intent_hash","structured_intent","context_snapshot_ref","policy_snapshot_id","policy_snapshot_hash","cancel_requested_at","started_at","completed_at","cancelled_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "runtime_policy_input_artifacts",
      select_columns: ["policy_input_ref","trigger_process_id","runtime_run_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","expected_catalog_version","catalog_as_of","policy_canonical_bytes","policy_input_hash","intent_policy_snapshot_ref","intent_policy_snapshot_hash","intent_policy_snapshot_canonical_bytes","policy_created_at","policy_expires_at","retention_until","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_start_attempts",
      select_columns: ["id","trigger_process_id","runtime_run_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","request_hash","idempotency_key","start_fence_generation","start_fence_token_hash","reservation_validation_stage","reservation_status_snapshot","policy_input_ref","policy_input_hash","policy_input_created_at","policy_expires_at","requested_catalog_version","effective_catalog_version","result_code","response_payload","trace_id","created_at","completed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "runtime_policy_snapshots",
      select_columns: ["id","runtime_run_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","policy_input_ref","policy_input_hash","policy_input_created_at","policy_input","requested_catalog_version","effective_catalog_version","catalog_as_of","skill_resolution_ids","resolved_skill_digests","resolved_skills","allowed_tools","tool_scopes","resource_scopes","network_scope","filesystem_scope","timer_scope","memory_scope","expires_at","security_revocation_epoch","revocation_policy","policy_snapshot_hash","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_run_leases",
      select_columns: ["runtime_run_id","lease_id","lease_generation","owner_id","lease_expires_at","heartbeat_at","recovery_state","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "lease_fence",
    },
    {
      table_name: "runtime_events",
      select_columns: ["id","runtime_run_id","trigger_process_id","event_type","sequence_no","idempotency_key","envelope","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_event_outbox",
      select_columns: ["id","runtime_run_id","trigger_process_id","source_event_id","source_sequence_no","append_type","payload_ref","payload_hash","idempotency_key","target","status","next_retry_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "runtime_event_inbox",
      select_columns: ["id","source","idempotency_key","payload_hash","processed_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_event_dlq",
      select_columns: ["id","source_event_id","event_type","payload","last_error","failed_at","resolved_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "tool_invocations",
      select_columns: ["id","runtime_run_id","adapter_tool_call_id","tool_name","status","idempotency_key","request_hash","normalized_args_hash","input","output","error","side_effect_status","downstream_idempotency_key","external_response_ref","external_error_ref","reconciled_at","started_at","completed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "runtime_control_signals",
      select_columns: ["runtime_signal_id","trigger_process_id","runtime_run_id","start_fence_generation","signal_type","idempotency_key","request_hash","requested_by","reason_code","control_token_hash","control_valid_until","status","handled_status","target_lease_generation","handled_lease_generation","final_fencing_generation","safe_point_reached","late_events_isolated","last_runtime_sequence_no","isolation_proof_ref","trace_id","requested_at","handled_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "runtime_control_tombstones",
      select_columns: ["runtime_run_id","start_fence_generation","signal_type","runtime_signal_id","request_hash","control_token_hash","control_valid_until","reason_code","status","trace_id","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_permissions",
      select_columns: ["id","runtime_run_id","policy_snapshot_id","capability","scope","expires_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "runtime_artifacts",
      select_columns: ["id","runtime_run_id","bot_id","owner_agent_id","artifact_type","status","artifact_ref","content_hash","size_bytes","media_type","redaction_status","retention_until","error","metadata","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "tool_permission_profile_revisions",
      select_columns: ["profile_ref","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","revision","allowed_tools","tool_arg_constraints","resource_scopes","network_scope","filesystem_scope","timer_scope","memory_scope","policy_epoch","profile_hash","effective_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "tool_permission_profile_current",
      select_columns: ["workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","profile_ref","revision","profile_hash","policy_epoch","pointer_version","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "pointer_cas",
    },
    {
      table_name: "runtime_start_reservation_validations",
      select_columns: ["id","runtime_start_attempt_id","validation_stage","validation_sequence_no","validation_result","reservation_status_snapshot","validated_fence_generation","error_code","details","trace_id","validated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    ],
    mutable_writers: [
      "transition_runtime_run_v1",
      "transition_runtime_start_attempt_v1",
      "cas_runtime_run_lease_v1",
      "cas_tool_permission_profile_current_v1",
      "append_runtime_event_v1",
      "claim_runtime_event_outbox_v1",
      "ack_runtime_event_outbox_v1",
    ],
    function_signatures: [
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "transition_runtime_run_v1",
      primary_table: "runtime_runs",
      writer_kind: "state_transition",
    }),
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "transition_runtime_start_attempt_v1",
      primary_table: "runtime_start_attempts",
      writer_kind: "state_transition",
    }),
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "cas_runtime_run_lease_v1",
      primary_table: "runtime_run_leases",
      writer_kind: "lease_fence",
    }),
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "cas_tool_permission_profile_current_v1",
      primary_table: "tool_permission_profile_current",
      writer_kind: "pointer_cas",
    }),
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "append_runtime_event_v1",
      primary_table: "runtime_events",
      writer_kind: "immutable_append",
    }),
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "claim_runtime_event_outbox_v1",
      primary_table: "runtime_event_outbox",
      writer_kind: "outbox_claim_ack",
      outbox_operation: "claim",
    }),
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "ack_runtime_event_outbox_v1",
      primary_table: "runtime_event_outbox",
      writer_kind: "outbox_claim_ack",
      outbox_operation: "ack",
    }),
    ],
    append_only_tables: [
      "runtime_policy_input_artifacts",
      "runtime_policy_snapshots",
      "runtime_events",
      "runtime_event_outbox",
      "runtime_event_inbox",
      "runtime_event_dlq",
      "runtime_control_tombstones",
      "tool_permission_profile_revisions",
      "runtime_start_reservation_validations",
    ],
    outbox_tables: ["runtime_event_outbox"],
    inbox_tables: ["runtime_event_inbox"],
    dlq_tables: ["runtime_event_dlq"],
    object_metadata_tables: [
      "runtime_policy_input_artifacts",
      "runtime_policy_snapshots",
      "runtime_artifacts",
    ],
  } as const);

export interface ActionRuntimeRepositoryPortV1
  extends OwnerRepositoryPortV1<typeof ACTION_RUNTIME_REPOSITORY_CONTRACT_V1> {}

export type ActionRuntimeUnitOfWorkPortV1 = OwnerUnitOfWorkPortV1<
  "action_runtime",
  Readonly<{ owner: ActionRuntimeRepositoryPortV1 }>
>;
