import { OWNER_DURABLE_EVENT_TYPES_V1 } from "@pai/contracts";
import {
  defineOwnerRepositoryContractV1,
  ownerForeignKeysV1,
  ownerFunctionSignatureV1,
  type OwnerRepositoryPortV1,
  type OwnerUnitOfWorkPortV1,
} from "@pai/persistence";

export const ACTION_RUNTIME_REPOSITORY_CONTRACT_V1 =
  defineOwnerRepositoryContractV1({
    contract_version: "owner_repository_contract.v1",
    owner_service: "action_runtime",
    schema: "action_runtime",
    app_role: "pai_action_runtime_app",
    fresh_migrations: ["0200_action_runtime"],
    manifest_source: "services/action-runtime/src/db/permission-manifest.v1.ts",
    generated_permission_sql: [
      "pai-infra/supabase/generated/permissions/0200_action_runtime.sql",
    ],
    tables: [
      "runtime_runs",
      "runtime_policy_input_artifacts",
      "runtime_start_attempts",
      "runtime_policy_snapshots",
      "runtime_run_leases",
      "runtime_events",
      "runtime_event_outbox",
      "runtime_event_inbox",
      "runtime_event_dlq",
      "tool_invocations",
      "runtime_control_signals",
      "runtime_control_tombstones",
      "runtime_permissions",
      "runtime_artifacts",
      "tool_permission_profile_revisions",
      "tool_permission_profile_current",
      "runtime_start_reservation_validations",
    ],
    table_permissions: [
    {
      table_name: "runtime_runs",
      select_columns: ["id","trigger_process_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","start_fence_generation","status","cancellation_status","runtime_provider","model","intent_ref","intent_version","structured_intent_hash","structured_intent","context_snapshot_ref","policy_snapshot_id","policy_snapshot_hash","cancel_requested_at","started_at","completed_at","cancelled_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "runtime_policy_input_artifacts",
      select_columns: ["policy_input_ref","trigger_process_id","runtime_run_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","expected_catalog_version","catalog_as_of","policy_canonical_bytes","policy_input_hash","intent_policy_snapshot_ref","intent_policy_snapshot_hash","intent_policy_snapshot_canonical_bytes","tool_permission_profile_ref","tool_permission_profile_revision","tool_permission_profile_hash","tool_policy_epoch","policy_created_at","policy_expires_at","retention_until","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_start_attempts",
      select_columns: ["id","trigger_process_id","runtime_run_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","request_hash","idempotency_key","start_fence_generation","start_fence_token_hash","reservation_validation_stage","reservation_status_snapshot","policy_input_ref","policy_input_hash","policy_input_created_at","policy_expires_at","requested_catalog_version","effective_catalog_version","result_code","response_payload","trace_id","created_at","completed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "runtime_policy_snapshots",
      select_columns: ["id","runtime_run_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","policy_input_ref","policy_input_hash","policy_input_created_at","policy_input","requested_catalog_version","effective_catalog_version","catalog_as_of","tool_permission_profile_ref","tool_permission_profile_revision","tool_permission_profile_hash","tool_policy_epoch","skill_resolution_ids","resolved_skill_digests","resolved_skills","allowed_tools","tool_scopes","resource_scopes","network_scope","filesystem_scope","timer_scope","memory_scope","expires_at","security_revocation_epoch","revocation_policy","policy_snapshot_hash","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_run_leases",
      select_columns: ["runtime_run_id","lease_id","lease_generation","owner_id","lease_expires_at","heartbeat_at","recovery_state","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "lease_fence",
    },
    {
      table_name: "runtime_events",
      select_columns: ["id","runtime_run_id","trigger_process_id","event_type","sequence_no","idempotency_key","envelope","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_event_outbox",
      select_columns: ["id","runtime_run_id","trigger_process_id","source_event_id","source_sequence_no","append_type","payload_ref","payload_hash","idempotency_key","target","status","next_retry_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "runtime_event_inbox",
      select_columns: ["id","source","event_id","scope_fingerprint","idempotency_key","payload_hash","semantic_hash","processed_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_event_dlq",
      select_columns: ["id","source_event_id","event_type","payload","last_error","failed_at","resolved_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "tool_invocations",
      select_columns: ["id","runtime_run_id","adapter_tool_call_id","tool_name","status","idempotency_key","request_hash","normalized_args_hash","input","output","error","side_effect_status","downstream_idempotency_key","external_response_ref","external_error_ref","reconciled_at","started_at","completed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "runtime_control_signals",
      select_columns: ["runtime_signal_id","trigger_process_id","runtime_run_id","start_fence_generation","signal_type","idempotency_key","request_hash","requested_by","reason_code","control_token_hash","control_valid_until","status","handled_status","target_lease_generation","handled_lease_generation","final_fencing_generation","safe_point_reached","late_events_isolated","last_runtime_sequence_no","isolation_proof_ref","trace_id","requested_at","handled_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "runtime_control_tombstones",
      select_columns: ["runtime_run_id","start_fence_generation","signal_type","runtime_signal_id","request_hash","control_token_hash","control_valid_until","reason_code","status","trace_id","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_permissions",
      select_columns: ["id","runtime_run_id","policy_snapshot_id","capability","scope","expires_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "runtime_artifacts",
      select_columns: ["id","runtime_run_id","bot_id","owner_agent_id","artifact_type","status","artifact_ref","content_hash","size_bytes","media_type","redaction_status","retention_until","error","metadata","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "tool_permission_profile_revisions",
      select_columns: ["profile_ref","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","revision","allowed_tools","tool_arg_constraints","resource_scopes","network_scope","filesystem_scope","timer_scope","memory_scope","policy_epoch","profile_hash","effective_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "tool_permission_profile_current",
      select_columns: ["workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","profile_ref","revision","profile_hash","policy_epoch","pointer_version","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "pointer_cas",
    },
    {
      table_name: "runtime_start_reservation_validations",
      select_columns: ["id","runtime_start_attempt_id","validation_stage","validation_sequence_no","validation_result","reservation_status_snapshot","validated_fence_generation","error_code","details","trace_id","validated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    ],
    mutable_writers: [
      "transition_runtime_run_v1",
      "persist_runtime_policy_snapshot_v1",
      "transition_tool_invocation_v1",
      "transition_runtime_control_signal_v1",
      "transition_runtime_artifact_v1",
      "transition_runtime_start_attempt_v1",
      "cas_runtime_run_lease_v1",
      "cas_tool_permission_profile_current_v1",
      "append_runtime_event_v1",
      "claim_runtime_event_outbox_v1",
      "ack_runtime_event_outbox_v1",
    ],
    function_signatures: [
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "transition_runtime_run_v1",
      primary_table: "runtime_runs",
      writer_kind: "state_transition",
      arguments: [
        ["p_runtime_run_id", "text"], ["p_expected_status", "text"],
        ["p_next_status", "text"], ["p_transition", "jsonb"],
        ["p_request_hash", "text"], ["p_trace_id", "text"],
      ],
      reads_tables: ["runtime_runs", "runtime_permissions", "tool_permission_profile_current"],
      writes_tables: ["runtime_runs", "runtime_events", "runtime_event_outbox"],
      effects: [
        { table_name: "runtime_runs", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "runtime_events", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "runtime_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "persist_runtime_policy_snapshot_v1",
      primary_table: "runtime_policy_input_artifacts",
      writer_kind: "immutable_append",
      arguments: [
        ["p_runtime_run_id", "text"], ["p_policy_input_artifact", "jsonb"],
        ["p_policy_snapshot", "jsonb"], ["p_permissions", "jsonb"],
        ["p_expected_permission_version", "bigint"],
        ["p_idempotency_key", "text"], ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["runtime_runs", "runtime_policy_input_artifacts", "runtime_policy_snapshots", "runtime_permissions", "tool_permission_profile_current"],
      writes_tables: ["runtime_policy_input_artifacts", "runtime_policy_snapshots", "runtime_permissions", "runtime_events", "runtime_event_outbox"],
      effects: [
        { table_name: "runtime_policy_input_artifacts", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "runtime_policy_snapshots", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "runtime_permissions", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "runtime_events", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "runtime_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "transition_tool_invocation_v1",
      primary_table: "tool_invocations",
      writer_kind: "state_transition",
      arguments: [
        ["p_tool_invocation_id", "text"], ["p_expected_status", "text"],
        ["p_next_status", "text"], ["p_invocation_result", "jsonb"],
        ["p_idempotency_key", "text"], ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["runtime_runs", "runtime_permissions", "tool_invocations"],
      writes_tables: ["tool_invocations", "runtime_events", "runtime_event_outbox"],
      effects: [
        { table_name: "tool_invocations", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "runtime_events", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "runtime_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "transition_runtime_control_signal_v1",
      primary_table: "runtime_control_signals",
      writer_kind: "state_transition",
      arguments: [
        ["p_runtime_signal_id", "text"], ["p_expected_status", "text"],
        ["p_next_status", "text"], ["p_expected_lease_generation", "bigint"],
        ["p_signal_result", "jsonb"], ["p_idempotency_key", "text"],
        ["p_request_hash", "text"], ["p_trace_id", "text"],
      ],
      reads_tables: ["runtime_runs", "runtime_run_leases", "runtime_control_signals", "runtime_control_tombstones"],
      writes_tables: ["runtime_control_signals", "runtime_control_tombstones", "runtime_events", "runtime_event_outbox"],
      effects: [
        { table_name: "runtime_control_signals", operation: "transition", concurrency_control: "generation_fence" },
        { table_name: "runtime_control_tombstones", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "runtime_events", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "runtime_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "transition_runtime_artifact_v1",
      primary_table: "runtime_artifacts",
      writer_kind: "state_transition",
      arguments: [
        ["p_artifact_id", "text"], ["p_expected_status", "text"],
        ["p_next_status", "text"], ["p_artifact_result", "jsonb"],
        ["p_idempotency_key", "text"], ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["runtime_runs", "runtime_artifacts"],
      writes_tables: ["runtime_artifacts", "runtime_events", "runtime_event_outbox"],
      effects: [
        { table_name: "runtime_artifacts", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "runtime_events", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "runtime_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "transition_runtime_start_attempt_v1",
      primary_table: "runtime_start_attempts",
      writer_kind: "state_transition",
      arguments: [
        ["p_attempt_id", "text"], ["p_expected_status", "text"],
        ["p_next_status", "text"], ["p_reservation_validation", "jsonb"],
        ["p_request_hash", "text"], ["p_trace_id", "text"],
      ],
      reads_tables: ["runtime_start_attempts", "runtime_runs"],
      writes_tables: ["runtime_start_attempts", "runtime_start_reservation_validations", "runtime_events", "runtime_event_outbox"],
      effects: [
        { table_name: "runtime_start_attempts", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "runtime_start_reservation_validations", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "runtime_events", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "runtime_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "cas_runtime_run_lease_v1",
      primary_table: "runtime_run_leases",
      writer_kind: "lease_fence",
      arguments: [
        ["p_runtime_run_id", "text"], ["p_expected_fence_generation", "bigint"],
        ["p_holder_id", "text"], ["p_lease_until", "timestamptz"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["runtime_run_leases"],
      writes_tables: ["runtime_run_leases", "runtime_events", "runtime_event_outbox"],
      effects: [
        { table_name: "runtime_run_leases", operation: "cas", concurrency_control: "generation_fence" },
        { table_name: "runtime_events", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "runtime_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "cas_tool_permission_profile_current_v1",
      primary_table: "tool_permission_profile_current",
      writer_kind: "pointer_cas",
      arguments: [
        ["p_profile_id", "text"], ["p_expected_revision", "bigint"],
        ["p_profile_revision", "jsonb"], ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["tool_permission_profile_current", "tool_permission_profile_revisions"],
      writes_tables: ["tool_permission_profile_revisions", "tool_permission_profile_current", "runtime_events", "runtime_event_outbox"],
      effects: [
        { table_name: "tool_permission_profile_revisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "tool_permission_profile_current", operation: "cas", concurrency_control: "expected_version" },
        { table_name: "runtime_events", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "runtime_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "append_runtime_event_v1",
      primary_table: "runtime_events",
      writer_kind: "immutable_append",
      arguments: [
        ["p_runtime_run_id", "text"], ["p_event", "jsonb"],
        ["p_idempotency_key", "text"], ["p_payload_hash", "text"],
        ["p_semantic_hash", "text"], ["p_scope_fingerprint", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["runtime_event_inbox"],
      writes_tables: ["runtime_events", "runtime_event_inbox", "runtime_event_outbox"],
      effects: [
        { table_name: "runtime_events", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "runtime_event_inbox", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "runtime_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "claim_runtime_event_outbox_v1",
      primary_table: "runtime_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_worker_id", "text"], ["p_limit", "integer"], ["p_lease_seconds", "integer"], ["p_now", "timestamptz"]],
      reads_tables: ["runtime_event_outbox"],
      writes_tables: ["runtime_event_outbox"],
      effects: [
        { table_name: "runtime_event_outbox", operation: "claim", concurrency_control: "lease_fence" },
      ],
      returns: "setof jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "action_runtime",
      function_name: "ack_runtime_event_outbox_v1",
      primary_table: "runtime_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_outbox_id", "text"], ["p_claim_token", "text"], ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"], ["p_error", "jsonb"], ["p_transport_ref", "text"], ["p_transport_epoch", "text"], ["p_now", "timestamptz"]],
      reads_tables: ["runtime_event_outbox"],
      writes_tables: ["runtime_event_outbox", "runtime_event_dlq"],
      effects: [
        { table_name: "runtime_event_outbox", operation: "ack", concurrency_control: "lease_fence" },
        { table_name: "runtime_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ],
  database_checks: [
    {
      constraint_name: "runtime_events_event_type_check",
      table_name: "runtime_events",
      required_definition_fragments: ["event_type"],
      semantic_constraint: {
        kind: "text_enum",
        column_name: "event_type",
        allowed_values: OWNER_DURABLE_EVENT_TYPES_V1.action_runtime,
      },
    },
    {
      constraint_name: "runtime_events_check",
      table_name: "runtime_events",
      required_definition_fragments: [
        "jsonb_typeof",
        "jsonb_object_length",
        "producer",
      ],
      semantic_constraint: {
        kind: "json_event_envelope",
        column_name: "envelope",
        producer_value: "action_runtime",
        required_keys: [
          "event_id",
          "event_type",
          "schema_version",
          "producer",
          "occurred_at",
          "idempotency_key",
          "trace_id",
          "payload",
        ],
        field_bindings: [
          { field_name: "event_id", column_name: "id" },
          { field_name: "event_type", column_name: "event_type" },
          {
            field_name: "idempotency_key",
            column_name: "idempotency_key",
          },
        ],
      },
    },
  ],
  foreign_key_snapshot: {
    status: "complete",
    source: "Database Design revision 466 / fresh 0200_action_runtime canonical DDL applied to PostgreSQL 17",
  },
  foreign_keys: ownerForeignKeysV1("action_runtime", [
    ["runtime_artifacts_runtime_run_id_fkey","runtime_artifacts",["runtime_run_id"],"runtime_runs",["id"]],
    ["runtime_control_signals_runtime_run_id_fkey","runtime_control_signals",["runtime_run_id"],"runtime_runs",["id"]],
    ["runtime_event_outbox_runtime_run_id_fkey","runtime_event_outbox",["runtime_run_id"],"runtime_runs",["id"]],
    ["runtime_event_outbox_source_event_id_fkey","runtime_event_outbox",["source_event_id"],"runtime_events",["id"]],
    ["runtime_events_runtime_run_id_fkey","runtime_events",["runtime_run_id"],"runtime_runs",["id"]],
    ["runtime_permissions_policy_snapshot_id_fkey","runtime_permissions",["policy_snapshot_id"],"runtime_policy_snapshots",["id"]],
    ["runtime_permissions_runtime_run_id_fkey","runtime_permissions",["runtime_run_id"],"runtime_runs",["id"]],
    ["runtime_policy_input_tool_profile_fk","runtime_policy_input_artifacts",["tool_permission_profile_ref","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","tool_permission_profile_revision","tool_permission_profile_hash","tool_policy_epoch"],"tool_permission_profile_revisions",["profile_ref","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","revision","profile_hash","policy_epoch"]],
    ["runtime_policy_snapshot_tool_profile_fk","runtime_policy_snapshots",["tool_permission_profile_ref","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","tool_permission_profile_revision","tool_permission_profile_hash","tool_policy_epoch"],"tool_permission_profile_revisions",["profile_ref","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","revision","profile_hash","policy_epoch"]],
    ["runtime_policy_snapshots_policy_input_ref_fkey","runtime_policy_snapshots",["policy_input_ref"],"runtime_policy_input_artifacts",["policy_input_ref"]],
    ["runtime_policy_snapshots_runtime_run_id_fkey","runtime_policy_snapshots",["runtime_run_id"],"runtime_runs",["id"]],
    ["runtime_run_leases_runtime_run_id_fkey","runtime_run_leases",["runtime_run_id"],"runtime_runs",["id"]],
    ["runtime_start_attempts_policy_input_ref_fkey","runtime_start_attempts",["policy_input_ref"],"runtime_policy_input_artifacts",["policy_input_ref"]],
    ["runtime_start_reservation_validat_runtime_start_attempt_id_fkey","runtime_start_reservation_validations",["runtime_start_attempt_id"],"runtime_start_attempts",["id"],{ on_delete: "cascade" }],
    ["tool_invocations_runtime_run_id_fkey","tool_invocations",["runtime_run_id"],"runtime_runs",["id"]],
    ["tool_permission_profile_curre_profile_ref_workspace_id_bot_fkey","tool_permission_profile_current",["profile_ref","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","revision","profile_hash","policy_epoch"],"tool_permission_profile_revisions",["profile_ref","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","revision","profile_hash","policy_epoch"]],
  ]),
  append_only_tables: [
      "runtime_policy_input_artifacts",
      "runtime_policy_snapshots",
      "runtime_events",
      "runtime_event_outbox",
      "runtime_event_inbox",
      "runtime_event_dlq",
      "runtime_control_tombstones",
      "tool_permission_profile_revisions",
      "runtime_start_reservation_validations",
    ],
    outbox_tables: ["runtime_event_outbox"],
    inbox_tables: ["runtime_event_inbox"],
    dlq_tables: ["runtime_event_dlq"],
    object_metadata_tables: [
      "runtime_policy_input_artifacts",
      "runtime_policy_snapshots",
      "runtime_artifacts",
    ],
  } as const);

export interface ActionRuntimeRepositoryPortV1
  extends OwnerRepositoryPortV1<typeof ACTION_RUNTIME_REPOSITORY_CONTRACT_V1> {}

export type ActionRuntimeUnitOfWorkPortV1 = OwnerUnitOfWorkPortV1<
  "action_runtime",
  Readonly<{ owner: ActionRuntimeRepositoryPortV1 }>
>;
