import {
  ACTION_RUNTIME_DATABASE_COLUMNS_V1,
  ACTION_RUNTIME_DATABASE_INDEXES_V1,
  ACTION_RUNTIME_DATABASE_CHECKS_V1,
  ACTION_RUNTIME_DATABASE_FUNCTIONS_V1,
  ACTION_RUNTIME_DATABASE_TRIGGERS_V1,
  ACTION_RUNTIME_DATABASE_UNIQUE_CONSTRAINTS_V1,
  ACTION_RUNTIME_FOREIGN_KEYS_V1,
} from "./catalog-snapshot.generated.v1.js";
import { ACTION_RUNTIME_WRITER_ARTIFACTS_V1 } from "./writer-artifacts.generated.v1.js";
import { OWNER_DURABLE_EVENT_TYPES_V1 } from "@pai/contracts";
import {
  defineOwnerRepositoryContractV1,
  ownerDlqResolutionContractV1,
  ownerEventingReconciliationContractV1,
  ownerEventingTransportEpochActivationSignatureV1,
  ownerEventingTransportEpochTablePermissionV1,
  ownerFunctionSignatureV1,
  type OwnerRepositoryPortV1,
  type OwnerUnitOfWorkPortV1,
} from "@pai/persistence";

const ACTION_RUNTIME_DLQ_RESOLUTION_V1 = ownerDlqResolutionContractV1(
  "action_runtime",
  "runtime_event_dlq",
);
const ACTION_RUNTIME_EVENT_RECONCILIATION_V1 =
  ownerEventingReconciliationContractV1(
    "action_runtime",
    "runtime_event_outbox",
  );

const ACTION_RUNTIME_EVENT_OUTBOX_PRIVATE_COLUMNS_V1 = [
  ["claimed_by", "text"],
  ["claim_token", "text"],
  ["locked_until", "timestamp with time zone"],
  ["last_error", "jsonb"],
  ["transport_ref", "text"],
  ["transport_epoch", "text"],
  ["transport_generation", "bigint"],
  ["sent_at", "timestamp with time zone"],
] as const;

const ACTION_RUNTIME_EVENT_OUTBOX_REQUIRED_COLUMNS_V1 = [
  ["id", "text", true, null],
  ["status", "text", true, null],
  ["attempt_count", "integer", true, "0"],
  ["updated_at", "timestamp with time zone", true, "now()"],
] as const;

const ACTION_RUNTIME_SAFE_BIGINT_COLUMNS_V1 = [
  ["runtime_runs_start_fence_generation_safe_check", "runtime_runs", "start_fence_generation", 1, false],
  ["runtime_runs_intent_version_safe_check", "runtime_runs", "intent_version", 1, false],
  ["runtime_runs_context_snapshot_version_safe_check", "runtime_runs", "context_snapshot_version", 1, false],
  ["runtime_policy_input_profile_revision_safe_check", "runtime_policy_input_artifacts", "tool_permission_profile_revision", 1, false],
  ["runtime_policy_input_tool_epoch_safe_check", "runtime_policy_input_artifacts", "tool_policy_epoch", 0, false],
  ["runtime_start_attempts_fence_safe_check", "runtime_start_attempts", "start_fence_generation", 1, true],
  ["runtime_policy_snapshot_profile_revision_safe_check", "runtime_policy_snapshots", "tool_permission_profile_revision", 1, false],
  ["runtime_policy_snapshot_tool_epoch_safe_check", "runtime_policy_snapshots", "tool_policy_epoch", 0, false],
  ["runtime_policy_snapshot_security_epoch_safe_check", "runtime_policy_snapshots", "security_revocation_epoch", 0, false],
  ["runtime_run_leases_generation_safe_check", "runtime_run_leases", "lease_generation", 1, false],
  ["runtime_events_sequence_no_safe_check", "runtime_events", "sequence_no", 1, false],
  ["runtime_event_outbox_source_sequence_safe_check", "runtime_event_outbox", "source_sequence_no", 1, false],
  ["runtime_event_outbox_transport_generation_safe_check", "runtime_event_outbox", "transport_generation", 1, true],
  ["runtime_skill_security_projection_epoch_safe_check", "runtime_skill_security_projection", "security_revocation_epoch", 0, false],
  ["runtime_skill_security_projection_stream_generation_safe_check", "runtime_skill_security_projection", "stream_generation", 1, true],
  ["runtime_control_signals_start_fence_safe_check", "runtime_control_signals", "start_fence_generation", 1, false],
  ["runtime_control_signals_target_lease_safe_check", "runtime_control_signals", "target_lease_generation", 1, true],
  ["runtime_control_signals_handled_lease_safe_check", "runtime_control_signals", "handled_lease_generation", 1, true],
  ["runtime_control_signals_final_fence_safe_check", "runtime_control_signals", "final_fencing_generation", 1, true],
  ["runtime_control_signals_last_sequence_safe_check", "runtime_control_signals", "last_runtime_sequence_no", 0, true],
  ["runtime_control_tombstones_start_fence_safe_check", "runtime_control_tombstones", "start_fence_generation", 1, false],
  ["runtime_artifacts_size_bytes_safe_check", "runtime_artifacts", "size_bytes", 0, true],
  ["runtime_artifacts_originating_lease_generation_safe_check", "runtime_artifacts", "originating_lease_generation", 1, false],
  ["runtime_artifacts_reconciliation_generation_safe_check", "runtime_artifacts", "reconciliation_generation", 0, false],
  ["tool_profile_revisions_revision_safe_check", "tool_permission_profile_revisions", "revision", 1, false],
  ["tool_profile_revisions_policy_epoch_safe_check", "tool_permission_profile_revisions", "policy_epoch", 0, false],
  ["tool_profile_current_revision_safe_check", "tool_permission_profile_current", "revision", 1, false],
  ["tool_profile_current_policy_epoch_safe_check", "tool_permission_profile_current", "policy_epoch", 0, false],
  ["tool_profile_current_pointer_version_safe_check", "tool_permission_profile_current", "pointer_version", 1, false],
  ["runtime_start_validation_sequence_safe_check", "runtime_start_reservation_validations", "validation_sequence_no", 1, false],
  ["runtime_start_validation_fence_safe_check", "runtime_start_reservation_validations", "validated_fence_generation", 1, true],
] as const;

const ACTION_RUNTIME_SAFE_BIGINT_CHECKS_V1 =
  ACTION_RUNTIME_SAFE_BIGINT_COLUMNS_V1.map(
    ([constraint_name, table_name, column_name, min, nullable]) => ({
      constraint_name,
      table_name,
      required_definition_fragments: [
        column_name,
        String(min),
        String(Number.MAX_SAFE_INTEGER),
      ],
      semantic_constraint: nullable
        ? {
            kind: "nullable_integer_range" as const,
            column_name,
            min,
            max: Number.MAX_SAFE_INTEGER,
          }
        : {
            kind: "integer_range" as const,
            column_name,
            min,
            max: Number.MAX_SAFE_INTEGER,
          },
    }),
  );

export const ACTION_RUNTIME_REPOSITORY_CONTRACT_V1 =
  defineOwnerRepositoryContractV1({
    contract_version: "owner_repository_contract.v1",
    owner_service: "action_runtime",
    schema: "action_runtime",
    app_role: "pai_action_runtime_app",
    fresh_migrations: ["0200_action_runtime"],
    manifest_source: "services/action-runtime/src/db/permission-manifest.v1.ts",
    generated_permission_sql: [
      "pai-infra/supabase/generated/permissions/0200_action_runtime.sql",
    ],
    tables: [
      "runtime_runs",
      "runtime_policy_input_artifacts",
      "runtime_start_attempts",
      "runtime_policy_snapshots",
      "runtime_run_leases",
      "runtime_events",
      "runtime_event_outbox",
      "runtime_event_outbox_reconciliations",
      "runtime_event_outbox_quarantine",
      "runtime_event_inbox",
      "runtime_skill_security_projection",
      "runtime_event_dlq",
      ACTION_RUNTIME_DLQ_RESOLUTION_V1.resolution_table,
      "eventing_transport_epochs",
      "tool_invocations",
      "runtime_control_signals",
      "runtime_control_tombstones",
      "runtime_permissions",
      "runtime_artifacts",
      "tool_permission_profile_revisions",
      "tool_permission_profile_current",
      "runtime_start_reservation_validation_calls",
      "runtime_start_reservation_validations",
    ],
    table_permissions: [
    {
      table_name: "runtime_runs",
      select_columns: ["id","trigger_process_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","start_attempt_no","start_fence_generation","status","cancellation_status","runtime_provider","model","intent_ref","intent_version","structured_intent_hash","structured_intent","context_snapshot_ref","context_snapshot_version","context_snapshot_hash","policy_snapshot_id","policy_snapshot_hash","terminal_reason","cancel_requested_at","started_at","completed_at","cancelled_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "runtime_policy_input_artifacts",
      select_columns: ["policy_input_ref","trigger_process_id","runtime_run_id","start_attempt_no","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","expected_catalog_version","catalog_as_of","policy_canonical_bytes","policy_input_hash","intent_policy_snapshot_ref","intent_policy_snapshot_hash","intent_policy_snapshot_canonical_bytes","tool_permission_profile_ref","tool_permission_profile_revision","tool_permission_profile_hash","tool_policy_epoch","requested_allowed_tools","policy_created_at","policy_expires_at","retention_until","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_start_attempts",
      select_columns: ["id","trigger_process_id","start_attempt_no","runtime_run_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","request_hash","idempotency_key","start_fence_generation","start_fence_token_hash","request_snapshot","actor_binding","actor_binding_hash","reservation_validation_stage","reservation_status_snapshot","policy_input_ref","policy_input_hash","policy_input_created_at","policy_expires_at","requested_catalog_version","effective_catalog_version","result_code","response_payload","trace_id","created_at","completed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "runtime_policy_snapshots",
      select_columns: ["id","runtime_run_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","policy_input_ref","policy_input_hash","policy_input_created_at","policy_input","requested_catalog_version","effective_catalog_version","catalog_as_of","tool_permission_profile_ref","tool_permission_profile_revision","tool_permission_profile_hash","tool_policy_epoch","requested_allowed_tools","tool_arg_constraints","skill_resolution_ids","resolved_skill_digests","resolved_skills","allowed_tools","tool_scopes","resource_scopes","network_scope","filesystem_scope","timer_scope","memory_scope","expires_at","security_revocation_epoch","revocation_policy","policy_snapshot_hash","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_run_leases",
      select_columns: ["runtime_run_id","lease_id","lease_generation","owner_id","lease_expires_at","heartbeat_at","recovery_state","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "lease_fence",
    },
    {
      table_name: "runtime_events",
      select_columns: ["id","runtime_run_id","trigger_process_id","event_type","sequence_no","idempotency_key","envelope","payload_ref","payload_hash","envelope_canonical_bytes","retention_until","redaction_state","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_event_outbox",
      select_columns: ["id","runtime_run_id","trigger_process_id","source_event_id","source_sequence_no","append_type","payload_ref","payload_hash","idempotency_key","target","status","attempt_count","next_retry_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "runtime_event_outbox_reconciliations",
      select_columns: ["id","outbox_id","source","event_id","transport_epoch","reconciliation_generation","reason","status","probe_ref","probe_result_hash","rematerialized_payload_ref","rematerialized_payload_hash","last_error","detected_at","completed_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "runtime_event_outbox_quarantine",
      select_columns: ["id","canonical_outbox_id","source","event_id","observed_idempotency_key","observed_payload_hash","canonical_payload_hash","reason","details","detected_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_event_inbox",
      select_columns: ["id","source","event_id","scope_fingerprint","idempotency_key","payload_hash","semantic_hash","processed_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_skill_security_projection",
      select_columns: ["singleton_key","security_revocation_epoch","last_event_id","last_event_occurred_at","stream_epoch","stream_generation","synchronized_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "runtime_event_dlq",
      select_columns: ["id","source_event_id","event_type","payload","last_error","failed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    ACTION_RUNTIME_DLQ_RESOLUTION_V1.table_permission,
    ownerEventingTransportEpochTablePermissionV1(),
    {
      table_name: "tool_invocations",
      select_columns: ["id","runtime_run_id","adapter_tool_call_id","tool_name","status","idempotency_key","request_hash","normalized_args_hash","input","output","error","side_effect_status","downstream_idempotency_key","external_response_ref","external_error_ref","reconciled_at","reconciliation_evidence_ref","reconciliation_idempotency_key","reconciliation_request_hash","started_at","completed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "runtime_control_signals",
      select_columns: ["runtime_signal_id","trigger_process_id","runtime_run_id","start_attempt_no","start_fence_generation","signal_type","idempotency_key","request_hash","requested_by","reason_code","control_token_hash","control_valid_until","status","handled_status","target_lease_generation","handled_lease_generation","final_fencing_generation","safe_point_reached","late_events_isolated","last_runtime_sequence_no","isolation_proof_ref","trace_id","requested_at","handled_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "runtime_control_tombstones",
      select_columns: ["runtime_run_id","trigger_process_id","start_attempt_no","start_fence_generation","signal_type","runtime_signal_id","idempotency_key","request_hash","control_token_hash","control_valid_until","reason_code","scope","status","trace_id","requested_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_permissions",
      select_columns: ["id","runtime_run_id","policy_snapshot_id","capability","scope","expires_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "runtime_artifacts",
      select_columns: ["id","runtime_run_id","bot_id","owner_agent_id","artifact_type","status","artifact_ref","content_hash","size_bytes","media_type","redaction_status","retention_until","error","metadata","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "tool_permission_profile_revisions",
      select_columns: ["profile_ref","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","revision","allowed_tools","tool_arg_constraints","resource_scopes","network_scope","filesystem_scope","timer_scope","memory_scope","policy_epoch","profile_hash","effective_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "tool_permission_profile_current",
      select_columns: ["workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","profile_ref","revision","profile_hash","policy_epoch","pointer_version","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "pointer_cas",
    },
    {
      table_name: "runtime_start_reservation_validation_calls",
      select_columns: ["id","runtime_start_attempt_id","validation_call_id","validation_stage","request_hash","trace_id","requested_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "runtime_start_reservation_validations",
      select_columns: ["id","runtime_start_attempt_id","validation_call_id","validation_stage","validation_sequence_no","validation_result","request_hash","start_fence_token_hash","actor_binding_hash","response_source","response_schema_version","response_hash","owner_response","reservation_status_snapshot","validated_fence_generation","error_code","details","trace_id","validated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    ],
    mutable_writers: [
      ...ACTION_RUNTIME_DLQ_RESOLUTION_V1.mutable_writers,
      ...ACTION_RUNTIME_EVENT_RECONCILIATION_V1.mutable_writers,
      "create_runtime_start_attempt_v1",
      "begin_runtime_start_reservation_validation_call_v1",
      "append_runtime_start_reservation_validation_v1",
      "transition_runtime_start_attempt_v1",
      "transition_runtime_run_v1",
      "cas_runtime_run_lease_v1",
      "cas_tool_permission_profile_current_v1",
      "append_runtime_event_v1",
      "record_tool_invocation_v1",
      "mark_tool_invocation_running_v1",
      "finalize_tool_invocation_v1",
      "freeze_unknown_tool_side_effect_v1",
      "reconcile_tool_invocation_v1",
      "record_runtime_control_signal_v1",
      "record_runtime_already_terminal_control_v1",
      "transition_runtime_control_signal_v1",
      "record_runtime_artifact_v1",
      "finalize_runtime_artifact_v1",
      "claim_runtime_artifact_reconciliation_v1",
      "reconcile_runtime_artifact_v1",
      "record_runtime_event_inbox_v1",
      "touch_runtime_skill_security_projection_v1",
      "record_runtime_consumer_dead_letter_v1",
      "claim_runtime_event_outbox_v1",
      "ack_runtime_event_outbox_v1",
      "detect_missing_runtime_event_delivery_v1",
      "claim_runtime_event_reconciliation_v1",
      "ack_runtime_event_reconciliation_v1",
      "rematerialize_runtime_event_outbox_v1",
      "quarantine_runtime_event_outbox_drift_v1",
      "activate_eventing_transport_epoch_v1",
    ],
    function_signatures: [
      ...ACTION_RUNTIME_DLQ_RESOLUTION_V1.function_signatures,
      ...ACTION_RUNTIME_EVENT_RECONCILIATION_V1.function_signatures,
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "create_runtime_start_attempt_v1",
        primary_table: "runtime_start_attempts",
        writer_kind: "state_transition",
        arguments: [
          ["p_attempt_id", "text"],
          ["p_trigger_process_id", "text"],
          ["p_runtime_run_id", "text"],
          ["p_start_attempt_no", "integer"],
          ["p_start_fence_generation", "bigint", { nullable: true }],
          ["p_policy_input_artifact", "jsonb"],
          ["p_idempotency_key", "text"],
          ["p_request_hash", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_start_attempts",
          "runtime_policy_input_artifacts",
          "runtime_control_tombstones",
        ],
        writes_tables: [
          "runtime_policy_input_artifacts",
          "runtime_start_attempts",
        ],
        effects: [
          {
            table_name: "runtime_policy_input_artifacts",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_start_attempts",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_start_attempts",
            operation: "append",
            concurrency_control: "advisory_identity_lock",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name:
          "begin_runtime_start_reservation_validation_call_v1",
        primary_table:
          "runtime_start_reservation_validation_calls",
        writer_kind: "immutable_append",
        arguments: [
          ["p_runtime_run_id", "text"],
          ["p_runtime_start_attempt_id", "text"],
          ["p_expected_start_request_hash", "text"],
          ["p_expected_start_fence_token_hash", "text"],
          ["p_expected_actor_binding_hash", "text"],
          ["p_validation_call_id", "text"],
          ["p_validation_stage", "text"],
          ["p_owner_request_hash", "text"],
          ["p_requested_at", "timestamptz"],
          ["p_idempotency_key", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_start_attempts",
          "runtime_start_reservation_validation_calls",
          "runtime_start_reservation_validations",
        ],
        writes_tables: [
          "runtime_start_reservation_validation_calls",
        ],
        effects: [
          {
            table_name:
              "runtime_start_reservation_validation_calls",
            operation: "append",
            concurrency_control: "expected_state_version",
          },
          {
            table_name:
              "runtime_start_reservation_validation_calls",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_start_attempts",
          },
          {
            table_name:
              "runtime_start_reservation_validation_calls",
            operation: "append",
            concurrency_control: "advisory_identity_lock",
          },
          {
            table_name:
              "runtime_start_reservation_validation_calls",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name:
          "append_runtime_start_reservation_validation_v1",
        primary_table:
          "runtime_start_reservation_validations",
        writer_kind: "immutable_append",
        arguments: [
          ["p_runtime_run_id", "text"],
          ["p_runtime_start_attempt_id", "text"],
          ["p_expected_start_request_hash", "text"],
          ["p_expected_start_fence_token_hash", "text"],
          ["p_expected_actor_binding_hash", "text"],
          ["p_validation_call_id", "text"],
          ["p_validation_stage", "text"],
          ["p_owner_request_hash", "text"],
          ["p_response_source", "text"],
          ["p_response_schema_version", "text"],
          ["p_response_hash", "text"],
          ["p_owner_response", "jsonb"],
          ["p_validated_at", "timestamptz"],
          ["p_idempotency_key", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_start_attempts",
          "runtime_start_reservation_validation_calls",
          "runtime_start_reservation_validations",
        ],
        writes_tables: [
          "runtime_start_attempts",
          "runtime_start_reservation_validations",
        ],
        effects: [
          {
            table_name: "runtime_start_attempts",
            operation: "transition",
            concurrency_control: "database_row_lock",
          },
          {
            table_name:
              "runtime_start_reservation_validations",
            operation: "append",
            concurrency_control: "expected_state_version",
          },
          {
            table_name:
              "runtime_start_reservation_validations",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_start_attempts",
          },
          {
            table_name:
              "runtime_start_reservation_validations",
            operation: "append",
            concurrency_control: "advisory_identity_lock",
          },
          {
            table_name:
              "runtime_start_reservation_validations",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "transition_runtime_start_attempt_v1",
        primary_table: "runtime_start_attempts",
        writer_kind: "state_transition",
        arguments: [
          ["p_attempt_id", "text"],
          ["p_runtime_run_id", "text"],
          ["p_expected_result_code", "text"],
          ["p_expected_start_fence_generation", "bigint"],
          ["p_next_result_code", "text"],
          ["p_reservation_validation", "jsonb"],
          ["p_start_transition", "jsonb"],
          ["p_idempotency_key", "text"],
          ["p_request_hash", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_start_attempts",
          "runtime_start_reservation_validation_calls",
          "runtime_start_reservation_validations",
          "runtime_policy_input_artifacts",
          "tool_permission_profile_revisions",
          "tool_permission_profile_current",
          "runtime_runs",
          "runtime_policy_snapshots",
          "runtime_permissions",
          "runtime_control_tombstones",
        ],
        writes_tables: [
          "runtime_start_attempts",
          "runtime_start_reservation_validations",
          "runtime_runs",
          "runtime_policy_snapshots",
          "runtime_permissions",
        ],
        effects: [
          {
            table_name: "runtime_start_attempts",
            operation: "transition",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "runtime_start_reservation_validations",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_runs",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_runs",
            operation: "append",
            concurrency_control: "advisory_identity_lock",
          },
          {
            table_name: "runtime_policy_snapshots",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_permissions",
            operation: "upsert",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "transition_runtime_run_v1",
        primary_table: "runtime_runs",
        writer_kind: "state_transition",
        arguments: [
          ["p_runtime_run_id", "text"],
          ["p_expected_status", "text"],
          ["p_expected_start_fence_generation", "bigint"],
          ["p_expected_lease_generation", "bigint"],
          ["p_next_status", "text"],
          ["p_transition", "jsonb"],
          ["p_event", "jsonb"],
          ["p_envelope_canonical_bytes", "text"],
          ["p_payload_hash", "text"],
          ["p_outbox", "jsonb"],
          ["p_idempotency_key", "text"],
          ["p_request_hash", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_runs",
          "runtime_run_leases",
          "runtime_start_reservation_validations",
          "runtime_policy_snapshots",
          "runtime_permissions",
        ],
        writes_tables: [
          "runtime_runs",
          "runtime_run_leases",
          "runtime_events",
          "runtime_event_outbox",
        ],
        effects: [
          {
            table_name: "runtime_runs",
            operation: "transition",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "runtime_runs",
            operation: "transition",
            concurrency_control: "advisory_identity_lock",
          },
          {
            table_name: "runtime_runs",
            operation: "transition",
            concurrency_control: "database_row_lock",
          },
          {
            table_name: "runtime_run_leases",
            operation: "cas",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "runtime_run_leases",
            operation: "cas",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_event_outbox",
            operation: "enqueue",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "cas_runtime_run_lease_v1",
        primary_table: "runtime_run_leases",
        writer_kind: "lease_fence",
        arguments: [
          ["p_runtime_run_id", "text"],
          ["p_expected_start_fence_generation", "bigint"],
          ["p_expected_lease_generation", "bigint"],
          ["p_next_lease_generation", "bigint"],
          ["p_expected_recovery_state", "text"],
          ["p_next_recovery_state", "text"],
          ["p_lease_id", "text"],
          ["p_owner_id", "text"],
          ["p_lease_expires_at", "timestamptz"],
          ["p_now", "timestamptz"],
          ["p_request_hash", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_runs",
          "runtime_run_leases",
          "tool_invocations",
          "runtime_artifacts",
        ],
        writes_tables: ["runtime_run_leases"],
        effects: [
          {
            table_name: "runtime_run_leases",
            operation: "cas",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "runtime_run_leases",
            operation: "cas",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "cas_tool_permission_profile_current_v1",
        primary_table: "tool_permission_profile_current",
        writer_kind: "pointer_cas",
        arguments: [
          ["p_workspace_id", "text"],
          ["p_bot_id", "text"],
          ["p_owner_agent_id", "text"],
          ["p_deployment_environment", "text"],
          ["p_release_channel", "text"],
          ["p_expected_revision", "bigint"],
          ["p_expected_pointer_version", "bigint"],
          ["p_next_revision", "bigint"],
          ["p_next_pointer_version", "bigint"],
          ["p_next_policy_epoch", "bigint"],
          ["p_profile_revision", "jsonb"],
          ["p_idempotency_key", "text"],
          ["p_request_hash", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "tool_permission_profile_current",
          "tool_permission_profile_revisions",
        ],
        writes_tables: [
          "tool_permission_profile_revisions",
          "tool_permission_profile_current",
        ],
        effects: [
          {
            table_name: "tool_permission_profile_revisions",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "tool_permission_profile_current",
            operation: "cas",
            concurrency_control: "expected_version",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "append_runtime_event_v1",
        primary_table: "runtime_events",
        writer_kind: "immutable_append",
        arguments: [
          ["p_runtime_run_id", "text"],
          ["p_expected_start_fence_generation", "bigint"],
          ["p_expected_lease_generation", "bigint"],
          ["p_event", "jsonb"],
          ["p_envelope_canonical_bytes", "text"],
          ["p_payload_ref", "text"],
          ["p_payload_hash", "text"],
          ["p_retention_until", "timestamptz"],
          ["p_redaction_state", "text"],
          ["p_outbox", "jsonb"],
          ["p_idempotency_key", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: ["runtime_runs", "runtime_run_leases", "runtime_events"],
        writes_tables: ["runtime_events", "runtime_event_outbox"],
        effects: [
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_event_outbox",
            operation: "enqueue",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "record_tool_invocation_v1",
        primary_table: "tool_invocations",
        writer_kind: "state_transition",
        arguments: [
          ["p_tool_invocation_id", "text"],
          ["p_runtime_run_id", "text"],
          ["p_expected_start_fence_generation", "bigint"],
          ["p_expected_lease_generation", "bigint"],
          ["p_invocation_record", "jsonb"],
          ["p_event", "jsonb"],
          ["p_envelope_canonical_bytes", "text"],
          ["p_payload_hash", "text"],
          ["p_outbox", "jsonb"],
          ["p_idempotency_key", "text"],
          ["p_request_hash", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_runs",
          "runtime_run_leases",
          "runtime_policy_snapshots",
          "runtime_permissions",
          "tool_invocations",
        ],
        writes_tables: [
          "tool_invocations",
          "runtime_events",
          "runtime_event_outbox",
        ],
        effects: [
          {
            table_name: "tool_invocations",
            operation: "append",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "tool_invocations",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "tool_invocations",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_event_outbox",
            operation: "enqueue",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "mark_tool_invocation_running_v1",
        primary_table: "tool_invocations",
        writer_kind: "state_transition",
        arguments: [
          ["p_tool_invocation_id", "text"],
          ["p_runtime_run_id", "text"],
          ["p_expected_status", "text"],
          ["p_expected_side_effect_status", "text"],
          ["p_expected_start_fence_generation", "bigint"],
          ["p_expected_lease_generation", "bigint"],
          ["p_request_hash", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: ["runtime_runs", "runtime_run_leases", "tool_invocations"],
        writes_tables: ["tool_invocations"],
        effects: [
          {
            table_name: "tool_invocations",
            operation: "transition",
            concurrency_control: "expected_state_version",
          },
          {
            table_name: "tool_invocations",
            operation: "transition",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "tool_invocations",
            operation: "transition",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "finalize_tool_invocation_v1",
        primary_table: "tool_invocations",
        writer_kind: "state_transition",
        arguments: [
          ["p_tool_invocation_id", "text"],
          ["p_runtime_run_id", "text"],
          ["p_expected_status", "text"],
          ["p_expected_side_effect_status", "text"],
          ["p_expected_start_fence_generation", "bigint"],
          ["p_expected_lease_generation", "bigint"],
          ["p_terminal_status", "text"],
          ["p_invocation_result", "jsonb"],
          ["p_event", "jsonb"],
          ["p_envelope_canonical_bytes", "text"],
          ["p_payload_hash", "text"],
          ["p_outbox", "jsonb"],
          ["p_idempotency_key", "text"],
          ["p_request_hash", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_runs",
          "runtime_run_leases",
          "tool_invocations",
        ],
        writes_tables: [
          "tool_invocations",
          "runtime_events",
          "runtime_event_outbox",
        ],
        effects: [
          {
            table_name: "tool_invocations",
            operation: "transition",
            concurrency_control: "expected_state_version",
          },
          {
            table_name: "tool_invocations",
            operation: "transition",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "tool_invocations",
            operation: "transition",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_event_outbox",
            operation: "enqueue",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "freeze_unknown_tool_side_effect_v1",
        primary_table: "tool_invocations",
        writer_kind: "state_transition",
        arguments: [
          ["p_tool_invocation_id", "text"],
          ["p_runtime_run_id", "text"],
          ["p_expected_status", "text"],
          ["p_expected_side_effect_status", "text"],
          ["p_expected_start_fence_generation", "bigint"],
          ["p_expected_lease_generation", "bigint"],
          ["p_invocation_failure", "jsonb"],
          ["p_event_batch", "jsonb"],
          ["p_outbox_batch", "jsonb"],
          ["p_idempotency_key", "text"],
          ["p_request_hash", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_runs",
          "runtime_run_leases",
          "tool_invocations",
        ],
        writes_tables: [
          "tool_invocations",
          "runtime_runs",
          "runtime_events",
          "runtime_event_outbox",
        ],
        effects: [
          {
            table_name: "tool_invocations",
            operation: "transition",
            concurrency_control: "expected_state_version",
          },
          {
            table_name: "tool_invocations",
            operation: "transition",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "tool_invocations",
            operation: "transition",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_runs",
            operation: "transition",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "runtime_runs",
            operation: "transition",
            concurrency_control: "database_row_lock",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_event_outbox",
            operation: "enqueue",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "reconcile_tool_invocation_v1",
        primary_table: "tool_invocations",
        writer_kind: "state_transition",
        arguments: [
          ["p_tool_invocation_id", "text"],
          ["p_runtime_run_id", "text"],
          ["p_expected_status", "text"],
          ["p_expected_side_effect_status", "text"],
          ["p_expected_start_fence_generation", "bigint"],
          ["p_expected_invocation_lease_generation", "bigint"],
          ["p_expected_request_hash", "text"],
          ["p_expected_downstream_idempotency_key", "text"],
          ["p_reconciliation_result", "jsonb"],
          ["p_event", "jsonb"],
          ["p_envelope_canonical_bytes", "text"],
          ["p_payload_hash", "text"],
          ["p_outbox", "jsonb"],
          ["p_idempotency_key", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_runs",
          "runtime_run_leases",
          "tool_invocations",
        ],
        writes_tables: [
          "tool_invocations",
          "runtime_events",
          "runtime_event_outbox",
        ],
        effects: [
          {
            table_name: "tool_invocations",
            operation: "transition",
            concurrency_control: "expected_state_version",
          },
          {
            table_name: "tool_invocations",
            operation: "transition",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "tool_invocations",
            operation: "transition",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_event_outbox",
            operation: "enqueue",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "record_runtime_control_signal_v1",
        primary_table: "runtime_control_signals",
        writer_kind: "state_transition",
        arguments: [
          ["p_runtime_signal_id", "text"],
          ["p_runtime_run_id", "text"],
          ["p_trigger_process_id", "text"],
          ["p_start_attempt_no", "integer"],
          ["p_expected_start_fence_generation", "bigint"],
          ["p_request_source", "text"],
          ["p_verified_control_claims", "jsonb", { nullable: true }],
          ["p_policy_checkpoint", "jsonb", { nullable: true }],
          ["p_signal_request", "jsonb"],
          ["p_event", "jsonb", { nullable: true }],
          ["p_envelope_canonical_bytes", "text", { nullable: true }],
          ["p_payload_hash", "text", { nullable: true }],
          ["p_outbox", "jsonb", { nullable: true }],
          ["p_idempotency_key", "text"],
          ["p_request_hash", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_runs",
          "runtime_run_leases",
          "runtime_start_attempts",
          "runtime_control_signals",
          "runtime_control_tombstones",
        ],
        writes_tables: [
          "runtime_control_signals",
          "runtime_control_tombstones",
          "runtime_runs",
          "runtime_events",
          "runtime_event_outbox",
        ],
        effects: [
          {
            table_name: "runtime_control_signals",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_control_signals",
            operation: "append",
            concurrency_control: "advisory_identity_lock",
          },
          {
            table_name: "runtime_control_signals",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_control_tombstones",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_runs",
            operation: "transition",
            concurrency_control: "database_row_lock",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_event_outbox",
            operation: "enqueue",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "record_runtime_already_terminal_control_v1",
        primary_table: "runtime_control_signals",
        writer_kind: "state_transition",
        arguments: [
          ["p_runtime_signal_id", "text"],
          ["p_runtime_run_id", "text"],
          ["p_trigger_process_id", "text"],
          ["p_start_attempt_no", "integer"],
          ["p_expected_start_fence_generation", "bigint"],
          ["p_verified_control_claims", "jsonb"],
          ["p_signal_result", "jsonb"],
          ["p_event_batch", "jsonb"],
          ["p_outbox_batch", "jsonb"],
          ["p_idempotency_key", "text"],
          ["p_request_hash", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_runs",
          "runtime_run_leases",
          "runtime_start_attempts",
          "runtime_control_signals",
          "runtime_events",
          "runtime_event_outbox",
        ],
        writes_tables: [
          "runtime_control_signals",
          "runtime_events",
          "runtime_event_outbox",
        ],
        effects: [
          {
            table_name: "runtime_control_signals",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_control_signals",
            operation: "append",
            concurrency_control: "advisory_identity_lock",
          },
          {
            table_name: "runtime_control_signals",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_event_outbox",
            operation: "enqueue",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "transition_runtime_control_signal_v1",
        primary_table: "runtime_control_signals",
        writer_kind: "state_transition",
        arguments: [
          ["p_runtime_signal_id", "text"],
          ["p_runtime_run_id", "text"],
          ["p_expected_status", "text"],
          ["p_expected_start_fence_generation", "bigint"],
          ["p_worker_lease_id", "text"],
          ["p_worker_id", "text"],
          ["p_next_status", "text"],
          ["p_signal_result", "jsonb"],
          ["p_event_batch", "jsonb"],
          ["p_outbox_batch", "jsonb"],
          ["p_idempotency_key", "text"],
          ["p_request_hash", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_runs",
          "runtime_run_leases",
          "runtime_control_signals",
        ],
        writes_tables: [
          "runtime_control_signals",
          "runtime_runs",
          "runtime_run_leases",
          "runtime_events",
          "runtime_event_outbox",
        ],
        effects: [
          {
            table_name: "runtime_control_signals",
            operation: "transition",
            concurrency_control: "expected_state_version",
          },
          {
            table_name: "runtime_control_signals",
            operation: "transition",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "runtime_control_signals",
            operation: "transition",
            concurrency_control: "advisory_identity_lock",
          },
          {
            table_name: "runtime_control_signals",
            operation: "transition",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_runs",
            operation: "transition",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "runtime_runs",
            operation: "transition",
            concurrency_control: "database_row_lock",
          },
          {
            table_name: "runtime_run_leases",
            operation: "cas",
            concurrency_control: "database_row_lock",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_event_outbox",
            operation: "enqueue",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "record_runtime_artifact_v1",
        primary_table: "runtime_artifacts",
        writer_kind: "state_transition",
        arguments: [
          ["p_artifact_id", "text"],
          ["p_runtime_run_id", "text"],
          ["p_expected_start_fence_generation", "bigint"],
          ["p_expected_lease_generation", "bigint"],
          ["p_artifact_record", "jsonb"],
          ["p_idempotency_key", "text"],
          ["p_request_hash", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_runs",
          "runtime_run_leases",
          "runtime_artifacts",
        ],
        writes_tables: ["runtime_artifacts"],
        effects: [
          {
            table_name: "runtime_artifacts",
            operation: "append",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "runtime_artifacts",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_artifacts",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "finalize_runtime_artifact_v1",
        primary_table: "runtime_artifacts",
        writer_kind: "state_transition",
        arguments: [
          ["p_artifact_id", "text"],
          ["p_runtime_run_id", "text"],
          ["p_expected_status", "text"],
          ["p_expected_start_fence_generation", "bigint"],
          ["p_expected_lease_generation", "bigint"],
          ["p_terminal_status", "text"],
          ["p_artifact_result", "jsonb"],
          ["p_event", "jsonb"],
          ["p_envelope_canonical_bytes", "text"],
          ["p_payload_hash", "text"],
          ["p_outbox", "jsonb"],
          ["p_idempotency_key", "text"],
          ["p_request_hash", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_runs",
          "runtime_run_leases",
          "runtime_artifacts",
        ],
        writes_tables: [
          "runtime_artifacts",
          "runtime_events",
          "runtime_event_outbox",
        ],
        effects: [
          {
            table_name: "runtime_artifacts",
            operation: "transition",
            concurrency_control: "expected_state_version",
          },
          {
            table_name: "runtime_artifacts",
            operation: "transition",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "runtime_artifacts",
            operation: "transition",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_event_outbox",
            operation: "enqueue",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "claim_runtime_artifact_reconciliation_v1",
        primary_table: "runtime_artifacts",
        writer_kind: "state_transition",
        arguments: [
          ["p_worker_id", "text"],
          ["p_limit", "integer"],
          ["p_lease_seconds", "integer"],
          ["p_now", "timestamptz"],
        ],
        reads_tables: [
          "runtime_runs",
          "runtime_run_leases",
          "runtime_artifacts",
        ],
        writes_tables: ["runtime_artifacts"],
        effects: [
          {
            table_name: "runtime_artifacts",
            operation: "claim",
            concurrency_control: "lease_fence",
            claim_locking: "for_update_skip_locked",
            claim_fence: {
              identity_column: "id",
              status_column: "status",
              eligible_status: "creating",
              worker_column: "reconciliation_owner",
              lease_expires_at_column: "reconciliation_expires_at",
              generation_column: "reconciliation_generation",
              order_by_columns: [
                "reconciliation_expires_at",
                "created_at",
                "id",
              ],
            },
            claim_authority: {
              owner_table_name: "runtime_runs",
              owner_identity_column: "id",
              claimed_owner_identity_column: "runtime_run_id",
              originating_lease_generation_column:
                "originating_lease_generation",
              lease_table_name: "runtime_run_leases",
              lease_owner_identity_column: "runtime_run_id",
              lease_generation_column: "lease_generation",
              lease_expires_at_column: "lease_expires_at",
              lease_state_column: "recovery_state",
              active_lease_state: "active",
            },
          },
        ],
        returns: "setof jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "reconcile_runtime_artifact_v1",
        primary_table: "runtime_artifacts",
        writer_kind: "state_transition",
        arguments: [
          ["p_artifact_id", "text"],
          ["p_runtime_run_id", "text"],
          ["p_expected_status", "text"],
          ["p_expected_start_fence_generation", "bigint"],
          ["p_expected_originating_lease_generation", "bigint"],
          ["p_reconciliation_owner", "text"],
          ["p_expected_reconciliation_generation", "bigint"],
          ["p_reconciliation_locked_until", "timestamptz"],
          ["p_now", "timestamptz"],
          ["p_terminal_status", "text"],
          ["p_artifact_result", "jsonb"],
          ["p_event", "jsonb"],
          ["p_envelope_canonical_bytes", "text"],
          ["p_payload_hash", "text"],
          ["p_outbox", "jsonb"],
          ["p_idempotency_key", "text"],
          ["p_request_hash", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_runs",
          "runtime_run_leases",
          "runtime_artifacts",
        ],
        writes_tables: [
          "runtime_artifacts",
          "runtime_events",
          "runtime_event_outbox",
        ],
        effects: [
          {
            table_name: "runtime_artifacts",
            operation: "transition",
            concurrency_control: "expected_state_version",
          },
          {
            table_name: "runtime_artifacts",
            operation: "transition",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "runtime_artifacts",
            operation: "transition",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_events",
            operation: "append",
            concurrency_control: "database_row_lock",
            lock_table_name: "runtime_runs",
          },
          {
            table_name: "runtime_event_outbox",
            operation: "enqueue",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "record_runtime_event_inbox_v1",
        primary_table: "runtime_event_inbox",
        writer_kind: "immutable_append",
        arguments: [
          ["p_event", "jsonb"],
          ["p_idempotency_key", "text"],
          ["p_payload_hash", "text"],
          ["p_semantic_hash", "text"],
          ["p_scope_fingerprint", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: ["runtime_event_inbox", "runtime_skill_security_projection"],
        writes_tables: ["runtime_event_inbox", "runtime_skill_security_projection", "runtime_event_dlq"],
        effects: [
          {
            table_name: "runtime_event_inbox",
            operation: "append",
            concurrency_control: "durable_event_identity",
          },
          {
            table_name: "runtime_event_dlq",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
          {
            table_name: "runtime_skill_security_projection",
            operation: "upsert",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "touch_runtime_skill_security_projection_v1",
        primary_table: "runtime_skill_security_projection",
        writer_kind: "projection_upsert",
        arguments: [
          ["p_singleton_key", "text"],
          ["p_stream_epoch", "text"],
          ["p_stream_generation", "bigint"],
          ["p_trace_id", "text"],
        ],
        reads_tables: ["runtime_skill_security_projection"],
        writes_tables: ["runtime_skill_security_projection"],
        effects: [
          {
            table_name: "runtime_skill_security_projection",
            operation: "upsert",
            concurrency_control: "database_row_lock",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "record_runtime_consumer_dead_letter_v1",
        primary_table: "runtime_event_dlq",
        writer_kind: "immutable_append",
        arguments: [
          ["p_dlq_id", "text"],
          ["p_source_event_id", "text"],
          ["p_event_type", "text"],
          ["p_payload", "jsonb"],
          ["p_last_error", "jsonb"],
          ["p_failed_at", "timestamptz"],
          ["p_idempotency_key", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: ["runtime_event_dlq"],
        writes_tables: ["runtime_event_dlq"],
        effects: [
          {
            table_name: "runtime_event_dlq",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "claim_runtime_event_outbox_v1",
        primary_table: "runtime_event_outbox",
        writer_kind: "outbox_claim_ack",
        arguments: [
          ["p_worker_id", "text"],
          ["p_limit", "integer"],
          ["p_lease_seconds", "integer"],
          ["p_now", "timestamptz"],
          ["p_current_transport_epoch", "text"],
          ["p_current_transport_generation", "bigint"],
        ],
        // Claiming an outbox row returns the immutable source envelope to the
        // dispatcher.  Keep this dependency explicit so the generated writer
        // remains least-privilege and verifier-visible.
        reads_tables: [
          "runtime_event_outbox",
          "runtime_events",
          "eventing_transport_epochs",
        ],
        writes_tables: ["runtime_event_outbox"],
        effects: [
          {
            table_name: "runtime_event_outbox",
            operation: "claim",
            concurrency_control: "lease_fence",
          },
        ],
        returns: "setof jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "ack_runtime_event_outbox_v1",
        primary_table: "runtime_event_outbox",
        writer_kind: "outbox_claim_ack",
        arguments: [
          ["p_outbox_id", "text"],
          ["p_claim_token", "text"],
          ["p_outcome", "text"],
          ["p_next_retry_at", "timestamptz", { nullable: true }],
          ["p_error", "jsonb", { nullable: true }],
          ["p_transport_ref", "text", { nullable: true }],
          ["p_transport_epoch", "text", { nullable: true }],
          ["p_transport_generation", "bigint", { nullable: true }],
          ["p_current_transport_epoch", "text"],
          ["p_current_transport_generation", "bigint"],
          ["p_now", "timestamptz"],
        ],
        reads_tables: ["runtime_event_outbox", "eventing_transport_epochs"],
        writes_tables: ["runtime_event_outbox", "runtime_event_dlq"],
        effects: [
          {
            table_name: "runtime_event_outbox",
            operation: "ack",
            concurrency_control: "lease_fence",
          },
          {
            table_name: "runtime_event_dlq",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "detect_missing_runtime_event_delivery_v1",
        primary_table: "runtime_event_outbox_reconciliations",
        writer_kind: "state_transition",
        arguments: [
          ["p_reconciliation_id", "text"],
          ["p_outbox_id", "text"],
          ["p_expected_transport_epoch", "text"],
          ["p_expected_transport_generation", "bigint"],
          ["p_reason", "text"],
          ["p_detected_at", "timestamptz"],
          ["p_idempotency_key", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: ["runtime_event_outbox", "runtime_event_outbox_reconciliations"],
        writes_tables: ["runtime_event_outbox_reconciliations"],
        effects: [
          {
            table_name: "runtime_event_outbox_reconciliations",
            operation: "append",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "runtime_event_outbox_reconciliations",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "claim_runtime_event_reconciliation_v1",
        primary_table: "runtime_event_outbox_reconciliations",
        writer_kind: "state_transition",
        arguments: [
          ["p_worker_id", "text"],
          ["p_limit", "integer"],
          ["p_lease_seconds", "integer"],
          ["p_now", "timestamptz"],
          ["p_expected_transport_epoch", "text"],
          ["p_expected_transport_generation", "bigint"],
        ],
        reads_tables: ["runtime_event_outbox_reconciliations"],
        writes_tables: ["runtime_event_outbox_reconciliations"],
        effects: [{
          table_name: "runtime_event_outbox_reconciliations",
          operation: "claim",
          concurrency_control: "lease_fence",
          claim_locking: "for_update_skip_locked",
          claim_fence: {
            identity_column: "id",
            status_column: "status",
            eligible_status: "missing_detected",
            worker_column: "claimed_by",
            lease_expires_at_column: "locked_until",
            generation_column: "claim_generation",
            order_by_columns: ["detected_at", "id"],
          },
        }],
        returns: "setof jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "ack_runtime_event_reconciliation_v1",
        primary_table: "runtime_event_outbox_reconciliations",
        writer_kind: "state_transition",
        arguments: [
          ["p_reconciliation_id", "text"],
          ["p_claim_token", "text"],
          ["p_expected_reconciliation_generation", "bigint"],
          ["p_outcome", "text"],
          ["p_probe_ref", "text", { nullable: true }],
          ["p_probe_result_hash", "text", { nullable: true }],
          ["p_error", "jsonb", { nullable: true }],
          ["p_completed_at", "timestamptz"],
          ["p_trace_id", "text"],
        ],
        reads_tables: [
          "runtime_event_outbox_reconciliations",
          "runtime_event_outbox",
          "runtime_events",
          "runtime_event_dlq",
        ],
        writes_tables: [
          "runtime_event_outbox_reconciliations",
          "runtime_event_dlq",
        ],
        effects: [
          {
            table_name: "runtime_event_outbox_reconciliations",
            operation: "transition",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "runtime_event_outbox_reconciliations",
            operation: "transition",
            concurrency_control: "lease_fence",
          },
          {
            table_name: "runtime_event_dlq",
            operation: "append",
            concurrency_control: "idempotency_key",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "rematerialize_runtime_event_outbox_v1",
        primary_table: "runtime_event_outbox",
        writer_kind: "outbox_claim_ack",
        arguments: [
          ["p_reconciliation_id", "text"],
          ["p_claim_token", "text"],
          ["p_expected_reconciliation_generation", "bigint"],
          ["p_outbox_id", "text"],
          ["p_expected_transport_epoch", "text"],
          ["p_expected_transport_generation", "bigint"],
          ["p_rematerialized_payload_ref", "text", { nullable: true }],
          ["p_rematerialized_payload_hash", "text"],
          ["p_now", "timestamptz"],
          ["p_trace_id", "text"],
        ],
        reads_tables: ["runtime_event_outbox", "runtime_event_outbox_reconciliations"],
        writes_tables: ["runtime_event_outbox", "runtime_event_outbox_reconciliations"],
        effects: [
          {
            table_name: "runtime_event_outbox",
            operation: "enqueue",
            concurrency_control: "generation_fence",
          },
          {
            table_name: "runtime_event_outbox_reconciliations",
            operation: "transition",
            concurrency_control: "lease_fence",
          },
        ],
        returns: "jsonb",
      }),
      ownerFunctionSignatureV1({
        schema: "action_runtime",
        function_name: "quarantine_runtime_event_outbox_drift_v1",
        primary_table: "runtime_event_outbox_quarantine",
        writer_kind: "immutable_append",
        arguments: [
          ["p_quarantine_id", "text"],
          ["p_canonical_outbox_id", "text"],
          ["p_source", "text"],
          ["p_event_id", "text"],
          ["p_observed_idempotency_key", "text"],
          ["p_observed_payload_hash", "text"],
          ["p_canonical_payload_hash", "text"],
          ["p_reason", "text"],
          ["p_details", "jsonb"],
          ["p_detected_at", "timestamptz"],
          ["p_idempotency_key", "text"],
          ["p_trace_id", "text"],
        ],
        reads_tables: ["runtime_event_outbox", "runtime_event_outbox_quarantine"],
        writes_tables: ["runtime_event_outbox_quarantine"],
        effects: [{
          table_name: "runtime_event_outbox_quarantine",
          operation: "append",
          concurrency_control: "idempotency_key",
        }],
        returns: "jsonb",
      }),
      ownerEventingTransportEpochActivationSignatureV1("action_runtime"),
    ],
    // The generator imports this module under an explicit cache-busting
    // `?writer=` URL so it can attest a changed signature before the new
    // artifact exists. Normal application imports never carry that marker
    // and therefore remain fail-closed on exact artifact drift.
    ...(new URL(import.meta.url).searchParams.has("writer")
      ? {}
      : { writer_artifacts: ACTION_RUNTIME_WRITER_ARTIFACTS_V1 }),
    database_columns: ACTION_RUNTIME_DATABASE_COLUMNS_V1,
    database_checks: ACTION_RUNTIME_DATABASE_CHECKS_V1,
    database_functions: ACTION_RUNTIME_DATABASE_FUNCTIONS_V1,
    database_triggers: ACTION_RUNTIME_DATABASE_TRIGGERS_V1,
    database_unique_constraints: ACTION_RUNTIME_DATABASE_UNIQUE_CONSTRAINTS_V1,
    database_indexes: ACTION_RUNTIME_DATABASE_INDEXES_V1,
    foreign_key_snapshot: {
      status: "complete",
      source:
        "Database Design revision 520 contract snapshot; pai-infra fresh 0200 must supply the version-pinned owner-writer, safe-bigint and outbox reconciliation artifacts before deployment verification",
    },
  foreign_keys: ACTION_RUNTIME_FOREIGN_KEYS_V1,
  append_only_tables: [
      "runtime_policy_input_artifacts",
      "runtime_policy_snapshots",
      "runtime_events",
      "runtime_event_outbox",
      "runtime_event_inbox",
      "runtime_event_dlq",
      ACTION_RUNTIME_DLQ_RESOLUTION_V1.resolution_table,
      "runtime_event_outbox_quarantine",
      "runtime_control_tombstones",
      "tool_permission_profile_revisions",
      "runtime_start_reservation_validation_calls",
      "runtime_start_reservation_validations",
    ],
    outbox_tables: ["runtime_event_outbox"],
    inbox_tables: ["runtime_event_inbox"],
    dlq_tables: ["runtime_event_dlq"],
    dlq_resolutions: [ACTION_RUNTIME_DLQ_RESOLUTION_V1.binding],
    object_metadata_tables: [
      "runtime_policy_input_artifacts",
      "runtime_policy_snapshots",
      "runtime_artifacts",
    ],
  } as const);

export interface ActionRuntimeRepositoryPortV1
  extends OwnerRepositoryPortV1<typeof ACTION_RUNTIME_REPOSITORY_CONTRACT_V1> {}

export type ActionRuntimeUnitOfWorkPortV1 = OwnerUnitOfWorkPortV1<
  "action_runtime",
  Readonly<{ owner: ActionRuntimeRepositoryPortV1 }>
>;
