import { OWNER_DURABLE_EVENT_TYPES_V1 } from "@pai/contracts";
import {
  defineOwnerRepositoryContractV1,
  ownerForeignKeysV1,
  ownerFunctionSignatureV1,
  type OwnerRepositoryPortV1,
  type OwnerUnitOfWorkPortV1,
} from "@pai/persistence";

export const SKILL_REGISTRY_REPOSITORY_CONTRACT_V1 =
  defineOwnerRepositoryContractV1({
    contract_version: "owner_repository_contract.v1",
    owner_service: "skill_registry",
    schema: "skill_registry",
    app_role: "pai_skill_registry_app",
    fresh_migrations: ["0450_skill_registry"],
    manifest_source:
      "services/skill-registry/src/db/permission-manifest.v1.ts",
    generated_permission_sql: [
      "pai-infra/supabase/generated/permissions/0450_skill_registry.sql",
    ],
    tables: [
      "skills",
      "skill_version_staging",
      "skill_versions",
      "skill_packages",
      "skill_package_retention_transitions",
      "skill_package_retention_holds",
      "skill_activation_revisions",
      "skill_activation_current",
      "skill_permission_revisions",
      "skill_permission_current",
      "skill_resolution_attempts",
      "skill_resolutions",
      "skill_candidate_applications",
      "skill_audit_logs",
      "skill_event_outbox",
      "skill_event_inbox",
      "skill_event_dlq",
      "skill_management_commands",
      "skill_catalog_revisions",
      "skill_catalog_revision_entries",
      "skill_catalog_current",
      "skill_permission_summary_snapshots",
      "skill_permission_summary_entries",
      "skill_security_state",
    ],
    table_permissions: [
    {
      table_name: "skills",
      select_columns: ["id","skill_key","name","title","description","owner_ref","status","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "skill_version_staging",
      select_columns: ["id","skill_id","proposed_version","artifact_ref","package_digest","manifest_digest","provenance","validation_result","scanner_versions","validation_expires_at","status","created_by","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "skill_versions",
      select_columns: ["id","skill_id","version","package_digest","manifest_digest","runtime_target","lifecycle_state","lifecycle_version","provenance","validation_result","scanner_versions","validation_id","published_at","deprecated_at","revoked_at","revocation_epoch","created_by","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "skill_packages",
      select_columns: ["id","version_id","package_ref","media_type","size_bytes","package_digest","manifest_digest","manifest","scan_result","retention_state","retention_until","deletion_requested_at","deleted_at","delete_error","state_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "skill_package_retention_transitions",
      select_columns: ["id","package_id","from_state","to_state","from_state_version","to_state_version","reason_code","actor_principal_id","object_store_deletion_decision_version","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_package_retention_holds",
      select_columns: ["id","package_id","hold_type","reason_code","active","expires_at","actor_principal_id","created_at","released_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "skill_activation_revisions",
      select_columns: ["id","skill_id","workspace_id","bot_id","deployment_environment","release_channel","version_id","state","revision_no","previous_revision_id","actor_principal_id","reason","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_activation_current",
      select_columns: ["skill_id","workspace_id","bot_id","deployment_environment","release_channel","activation_revision_id","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "pointer_cas",
    },
    {
      table_name: "skill_permission_revisions",
      select_columns: ["id","skill_id","workspace_id","bot_id","deployment_environment","release_channel","owner_agent_id","decision","capability_refs","scope_hash","revision_no","previous_revision_id","actor_principal_id","reason","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_permission_current",
      select_columns: ["skill_id","workspace_id","bot_id","deployment_environment","release_channel","scope_hash","permission_revision_id","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "pointer_cas",
    },
    {
      table_name: "skill_resolution_attempts",
      select_columns: ["id","runtime_run_id","start_attempt_no","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","policy_input_ref","policy_input_hash","policy_input_created_at","policy_expires_at","requested_catalog_version","effective_catalog_version","catalog_as_of","security_revocation_epoch","skill_permission_summary_ref","skill_permission_summary_hash","request_hash","idempotency_key","status","error_code","response_payload","valid_until","trace_id","created_at","completed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "skill_resolutions",
      select_columns: ["id","resolution_attempt_id","runtime_run_id","start_attempt_no","skill_id","skill_key","required","version_id","package_digest","manifest_digest","runtime_target","permission_decision","granted_capability_refs","status","resolution_token_hash","valid_until","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_candidate_applications",
      select_columns: ["id","candidate_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","review_version","candidate_type","skill_key","baseline_catalog_version","proposal_ref","proposal_hash","evidence_refs","reviewed_by","schema_version","idempotency_key","request_hash","status","staging_version_id","review_ref","response_ref","response_hash","trace_id","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "skill_audit_logs",
      select_columns: ["id","skill_id","version_id","runtime_run_id","application_id","actor","action","decision","reason_code","evidence_refs","payload","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_event_outbox",
      select_columns: ["id","event_type","schema_version","producer","occurred_at","idempotency_key","trace_id","payload","payload_hash","target","status","next_retry_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "skill_event_inbox",
      select_columns: ["id","source","event_id","scope_fingerprint","idempotency_key","payload_hash","semantic_hash","processed_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_event_dlq",
      select_columns: ["id","source_event_id","event_type","payload","last_error","failed_at","resolved_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_management_commands",
      select_columns: ["id","operation","workspace_id","bot_id","deployment_environment","release_channel","skill_id","version_id","target_version_id","expected_revision","request_hash","idempotency_key","actor_principal_id","actor_role","reason","result_revision","result_catalog_version","result_security_revocation_epoch","response_payload","trace_id","created_at","completed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_catalog_revisions",
      select_columns: ["id","workspace_id","bot_id","deployment_environment","release_channel","catalog_version","catalog_as_of","security_revocation_epoch","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_catalog_revision_entries",
      select_columns: ["catalog_revision_id","workspace_id","bot_id","deployment_environment","release_channel","skill_id","activation_revision_id","version_id","package_digest","manifest_digest","runtime_target"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_catalog_current",
      select_columns: ["workspace_id","bot_id","deployment_environment","release_channel","catalog_revision_id","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "pointer_cas",
    },
    {
      table_name: "skill_permission_summary_snapshots",
      select_columns: ["summary_ref","schema_version","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","catalog_revision_id","catalog_version","catalog_as_of","security_revocation_epoch","canonical_bytes","summary_hash","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_permission_summary_entries",
      select_columns: ["summary_ref","ordinal","skill_id","skill_key","activation_revision_id","version_id","decision","decision_source","permission_revision_id","revision_no","scope_hash","owner_agent_condition","capability_refs"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_security_state",
      select_columns: ["singleton_key","security_revocation_epoch","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    ],
    mutable_writers: [
      "transition_skill_version_lifecycle_v1",
      "cas_skill_activation_current_v1",
      "cas_skill_permission_current_v1",
      "cas_skill_catalog_current_v1",
      "transition_skill_resolution_attempt_v1",
      "transition_skill_candidate_application_v1",
      "transition_skill_package_retention_v1",
      "claim_skill_event_outbox_v1",
      "ack_skill_event_outbox_v1",
    ],
    function_signatures: [
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "transition_skill_version_lifecycle_v1",
      primary_table: "skill_versions",
      writer_kind: "state_transition",
      arguments: [["p_skill_version_id", "text"], ["p_expected_status", "text"], ["p_next_status", "text"], ["p_version", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skills", "skill_versions", "skill_security_state"],
      writes_tables: ["skills", "skill_version_staging", "skill_versions", "skill_packages", "skill_package_retention_transitions", "skill_package_retention_holds", "skill_audit_logs", "skill_security_state", "skill_event_inbox", "skill_event_outbox", "skill_management_commands"],
      effects: [
        { table_name: "skills", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "skill_version_staging", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "skill_versions", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "skill_packages", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "skill_package_retention_transitions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_package_retention_holds", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_security_state", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "skill_event_inbox", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "skill_management_commands", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "cas_skill_activation_current_v1",
      primary_table: "skill_activation_current",
      writer_kind: "pointer_cas",
      arguments: [["p_skill_id", "text"], ["p_expected_revision", "bigint"], ["p_activation_revision", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_activation_current", "skill_activation_revisions"],
      writes_tables: ["skill_activation_revisions", "skill_activation_current", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skill_activation_revisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_activation_current", operation: "cas", concurrency_control: "expected_version" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "cas_skill_permission_current_v1",
      primary_table: "skill_permission_current",
      writer_kind: "pointer_cas",
      arguments: [["p_skill_id", "text"], ["p_expected_revision", "bigint"], ["p_permission_revision", "jsonb"], ["p_summary", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_permission_current", "skill_permission_revisions"],
      writes_tables: ["skill_permission_revisions", "skill_permission_current", "skill_permission_summary_snapshots", "skill_permission_summary_entries", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skill_permission_revisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_permission_current", operation: "cas", concurrency_control: "expected_version" },
        { table_name: "skill_permission_summary_snapshots", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_permission_summary_entries", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "cas_skill_catalog_current_v1",
      primary_table: "skill_catalog_current",
      writer_kind: "pointer_cas",
      arguments: [["p_catalog_key", "text"], ["p_expected_revision", "bigint"], ["p_catalog_revision", "jsonb"], ["p_entries", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_catalog_current", "skill_catalog_revisions"],
      writes_tables: ["skill_catalog_revisions", "skill_catalog_revision_entries", "skill_catalog_current", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skill_catalog_revisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_catalog_revision_entries", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_catalog_current", operation: "cas", concurrency_control: "expected_version" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "transition_skill_resolution_attempt_v1",
      primary_table: "skill_resolution_attempts",
      writer_kind: "state_transition",
      arguments: [["p_attempt_id", "text"], ["p_expected_status", "text"], ["p_next_status", "text"], ["p_resolution", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_resolution_attempts", "skill_versions"],
      writes_tables: ["skill_resolution_attempts", "skill_resolutions", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skill_resolution_attempts", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "skill_resolutions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "transition_skill_candidate_application_v1",
      primary_table: "skill_candidate_applications",
      writer_kind: "state_transition",
      arguments: [["p_application_id", "text"], ["p_expected_status", "text"], ["p_next_status", "text"], ["p_application", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_candidate_applications"],
      writes_tables: ["skill_candidate_applications", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skill_candidate_applications", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "transition_skill_package_retention_v1",
      primary_table: "skill_packages",
      writer_kind: "state_transition",
      arguments: [["p_package_id", "text"], ["p_expected_retention_status", "text"], ["p_next_retention_status", "text"], ["p_retention", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_packages", "skill_package_retention_holds"],
      writes_tables: ["skill_packages", "skill_package_retention_transitions", "skill_package_retention_holds", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skill_packages", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "skill_package_retention_transitions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_package_retention_holds", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "claim_skill_event_outbox_v1",
      primary_table: "skill_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_worker_id", "text"], ["p_limit", "integer"], ["p_lease_seconds", "integer"], ["p_now", "timestamptz"]],
      reads_tables: ["skill_event_outbox"], writes_tables: ["skill_event_outbox"],
      effects: [{ table_name: "skill_event_outbox", operation: "claim", concurrency_control: "lease_fence" }], returns: "setof jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "ack_skill_event_outbox_v1",
      primary_table: "skill_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_outbox_id", "text"], ["p_claim_token", "text"], ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"], ["p_error", "jsonb"], ["p_now", "timestamptz"]],
      reads_tables: ["skill_event_outbox"], writes_tables: ["skill_event_outbox", "skill_event_dlq"],
      effects: [
        { table_name: "skill_event_outbox", operation: "ack", concurrency_control: "lease_fence" },
        { table_name: "skill_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ],
    database_checks: [
      {
        constraint_name: "skill_event_outbox_event_type_check",
        table_name: "skill_event_outbox",
        required_definition_fragments: ["event_type", "skill.candidate.application.updated"],
        semantic_constraint: {
          kind: "text_enum",
          column_name: "event_type",
          allowed_values: OWNER_DURABLE_EVENT_TYPES_V1.skill_registry,
        },
      },
      {
        constraint_name: "skill_event_outbox_producer_check",
        table_name: "skill_event_outbox",
        required_definition_fragments: ["producer", "skill_registry"],
        semantic_constraint: {
          kind: "text_equals",
          column_name: "producer",
          value: "skill_registry",
        },
      },
    ],
    foreign_key_snapshot: {
    status: "complete",
    source: "Database Design revision 466 / fresh 0450_skill_registry canonical DDL applied to PostgreSQL 17",
  },
  foreign_keys: ownerForeignKeysV1("skill_registry", [
    ["skill_activation_current_activation_revision_id_skill_id_w_fkey","skill_activation_current",["activation_revision_id","skill_id","workspace_id","bot_id","deployment_environment","release_channel"],"skill_activation_revisions",["id","skill_id","workspace_id","bot_id","deployment_environment","release_channel"]],
    ["skill_activation_current_skill_id_fkey","skill_activation_current",["skill_id"],"skills",["id"]],
    ["skill_activation_revisions_previous_revision_id_skill_id_w_fkey","skill_activation_revisions",["previous_revision_id","skill_id","workspace_id","bot_id","deployment_environment","release_channel"],"skill_activation_revisions",["id","skill_id","workspace_id","bot_id","deployment_environment","release_channel"]],
    ["skill_activation_revisions_skill_id_fkey","skill_activation_revisions",["skill_id"],"skills",["id"]],
    ["skill_activation_revisions_version_id_skill_id_fkey","skill_activation_revisions",["version_id","skill_id"],"skill_versions",["id","skill_id"]],
    ["skill_audit_logs_application_id_fkey","skill_audit_logs",["application_id"],"skill_candidate_applications",["id"]],
    ["skill_audit_logs_skill_id_fkey","skill_audit_logs",["skill_id"],"skills",["id"]],
    ["skill_audit_logs_version_id_fkey","skill_audit_logs",["version_id"],"skill_versions",["id"]],
    ["skill_candidate_applications_staging_version_id_fkey","skill_candidate_applications",["staging_version_id"],"skill_version_staging",["id"]],
    ["skill_catalog_current_catalog_revision_id_workspace_id_bot_fkey","skill_catalog_current",["catalog_revision_id","workspace_id","bot_id","deployment_environment","release_channel"],"skill_catalog_revisions",["id","workspace_id","bot_id","deployment_environment","release_channel"]],
    ["skill_catalog_revision_entrie_activation_revision_id_skill_fkey","skill_catalog_revision_entries",["activation_revision_id","skill_id","workspace_id","bot_id","deployment_environment","release_channel"],"skill_activation_revisions",["id","skill_id","workspace_id","bot_id","deployment_environment","release_channel"]],
    ["skill_catalog_revision_entrie_catalog_revision_id_workspac_fkey","skill_catalog_revision_entries",["catalog_revision_id","workspace_id","bot_id","deployment_environment","release_channel"],"skill_catalog_revisions",["id","workspace_id","bot_id","deployment_environment","release_channel"],{ on_delete: "cascade" }],
    ["skill_catalog_revision_entries_skill_id_fkey","skill_catalog_revision_entries",["skill_id"],"skills",["id"]],
    ["skill_catalog_revision_entries_version_id_skill_id_fkey","skill_catalog_revision_entries",["version_id","skill_id"],"skill_versions",["id","skill_id"]],
    ["skill_management_commands_skill_id_fkey","skill_management_commands",["skill_id"],"skills",["id"]],
    ["skill_management_commands_target_version_id_fkey","skill_management_commands",["target_version_id"],"skill_versions",["id"]],
    ["skill_management_commands_version_id_fkey","skill_management_commands",["version_id"],"skill_versions",["id"]],
    ["skill_package_retention_holds_package_id_fkey","skill_package_retention_holds",["package_id"],"skill_packages",["id"]],
    ["skill_package_retention_transitions_package_id_fkey","skill_package_retention_transitions",["package_id"],"skill_packages",["id"]],
    ["skill_packages_version_id_fkey","skill_packages",["version_id"],"skill_versions",["id"]],
    ["skill_permission_current_permission_revision_id_skill_id_w_fkey","skill_permission_current",["permission_revision_id","skill_id","workspace_id","bot_id","deployment_environment","release_channel","scope_hash"],"skill_permission_revisions",["id","skill_id","workspace_id","bot_id","deployment_environment","release_channel","scope_hash"]],
    ["skill_permission_current_skill_id_fkey","skill_permission_current",["skill_id"],"skills",["id"]],
    ["skill_permission_revisions_previous_revision_id_skill_id_w_fkey","skill_permission_revisions",["previous_revision_id","skill_id","workspace_id","bot_id","deployment_environment","release_channel","scope_hash"],"skill_permission_revisions",["id","skill_id","workspace_id","bot_id","deployment_environment","release_channel","scope_hash"]],
    ["skill_permission_revisions_skill_id_fkey","skill_permission_revisions",["skill_id"],"skills",["id"]],
    ["skill_permission_summary_entries_skill_id_fkey","skill_permission_summary_entries",["skill_id"],"skills",["id"]],
    ["skill_permission_summary_entries_summary_ref_fkey","skill_permission_summary_entries",["summary_ref"],"skill_permission_summary_snapshots",["summary_ref"],{ on_delete: "restrict" }],
    ["skill_permission_summary_snap_catalog_revision_id_workspac_fkey","skill_permission_summary_snapshots",["catalog_revision_id","workspace_id","bot_id","deployment_environment","release_channel"],"skill_catalog_revisions",["id","workspace_id","bot_id","deployment_environment","release_channel"]],
    ["skill_resolution_attempt_summary_fk","skill_resolution_attempts",["skill_permission_summary_ref","skill_permission_summary_hash"],"skill_permission_summary_snapshots",["summary_ref","summary_hash"]],
    ["skill_resolutions_resolution_attempt_id_runtime_run_id_sta_fkey","skill_resolutions",["resolution_attempt_id","runtime_run_id","start_attempt_no"],"skill_resolution_attempts",["id","runtime_run_id","start_attempt_no"]],
    ["skill_resolutions_skill_id_fkey","skill_resolutions",["skill_id"],"skills",["id"]],
    ["skill_resolutions_version_id_skill_id_fkey","skill_resolutions",["version_id","skill_id"],"skill_versions",["id","skill_id"]],
    ["skill_version_staging_skill_id_fkey","skill_version_staging",["skill_id"],"skills",["id"]],
    ["skill_versions_skill_id_fkey","skill_versions",["skill_id"],"skills",["id"]],
    ["skill_versions_validation_id_skill_id_fkey","skill_versions",["validation_id","skill_id"],"skill_version_staging",["id","skill_id"]],
  ]),
  append_only_tables: [
      "skill_package_retention_transitions",
      "skill_activation_revisions",
      "skill_permission_revisions",
      "skill_resolutions",
      "skill_audit_logs",
      "skill_event_outbox",
      "skill_event_inbox",
      "skill_event_dlq",
      "skill_management_commands",
      "skill_catalog_revisions",
      "skill_catalog_revision_entries",
      "skill_permission_summary_snapshots",
      "skill_permission_summary_entries",
    ],
    outbox_tables: ["skill_event_outbox"],
    inbox_tables: ["skill_event_inbox"],
    dlq_tables: ["skill_event_dlq"],
    object_metadata_tables: [
      "skill_version_staging",
      "skill_packages",
      "skill_package_retention_transitions",
      "skill_package_retention_holds",
    ],
  } as const);

export interface SkillRegistryRepositoryPortV1
  extends OwnerRepositoryPortV1<typeof SKILL_REGISTRY_REPOSITORY_CONTRACT_V1> {}

export type SkillRegistryUnitOfWorkPortV1 = OwnerUnitOfWorkPortV1<
  "skill_registry",
  Readonly<{ owner: SkillRegistryRepositoryPortV1 }>
>;
