import {
  SKILL_REGISTRY_DATABASE_COLUMNS_V1,
  SKILL_REGISTRY_DATABASE_INDEXES_V1,
  SKILL_REGISTRY_DATABASE_CHECKS_V1,
  SKILL_REGISTRY_DATABASE_FUNCTIONS_V1,
  SKILL_REGISTRY_DATABASE_TRIGGERS_V1,
  SKILL_REGISTRY_DATABASE_UNIQUE_CONSTRAINTS_V1,
  SKILL_REGISTRY_FOREIGN_KEYS_V1,
} from "./catalog-snapshot.generated.v1.js";
import { SKILL_REGISTRY_WRITER_ARTIFACTS_V1 } from "./writer-artifacts.generated.v1.js";
import {
  OWNER_DURABLE_EVENT_TYPES_V1,
  SKILL_PERMISSION_SUMMARY_IMMUTABLE_TRIGGER_FUNCTION_BODY_V1,
} from "@pai/contracts";
import {
  defineOwnerRepositoryContractV1,
  ownerDlqResolutionContractV1,
  ownerEventingReconciliationContractV1,
  ownerEventingTransportEpochActivationSignatureV1,
  ownerEventingTransportEpochTablePermissionV1,
  ownerFunctionSignatureV1,
  ownerImmutableTriggerV1,
  type OwnerRepositoryPortV1,
  type OwnerUnitOfWorkPortV1,
} from "@pai/persistence";

const SKILL_REGISTRY_DLQ_RESOLUTION_V1 =
  ownerDlqResolutionContractV1(
    "skill_registry",
    "skill_event_dlq",
  );
const SKILL_EVENT_RECONCILIATION_V1 =
  ownerEventingReconciliationContractV1(
    "skill_registry",
    "skill_event_outbox",
  );

// The catalog predates the event-reconciliation writer promotion and still
// lists these SECURITY DEFINER writers as private helpers. An application
// writer is attested through its exact signature/artifact path, not through
// the private-function catalog; it must never appear in both trust paths.
const SKILL_REGISTRY_PRIVATE_DATABASE_FUNCTIONS_V1 =
  SKILL_REGISTRY_DATABASE_FUNCTIONS_V1.filter(
    ({ function_name }) =>
      !SKILL_EVENT_RECONCILIATION_V1.mutable_writers.includes(function_name),
  );

export const SKILL_REGISTRY_REPOSITORY_CONTRACT_V1 =
  defineOwnerRepositoryContractV1({
    contract_version: "owner_repository_contract.v1",
    owner_service: "skill_registry",
    schema: "skill_registry",
    app_role: "pai_skill_registry_app",
    fresh_migrations: ["0450_skill_registry"],
    manifest_source:
      "services/skill-registry/src/db/permission-manifest.v1.ts",
    generated_permission_sql: [
      "pai-infra/supabase/generated/permissions/0450_skill_registry.sql",
    ],
    tables: [
      "skills",
      "skill_version_staging",
      "skill_validation_attempts",
      "skill_versions",
      "skill_packages",
      "skill_package_retention_transitions",
      "skill_package_retention_holds",
      "skill_activation_revisions",
      "skill_activation_current",
      "skill_permission_revisions",
      "skill_permission_current",
      "skill_resolution_attempts",
      "skill_resolutions",
      "skill_candidate_applications",
      "skill_audit_logs",
      "skill_event_outbox",
      "skill_event_inbox",
      "skill_event_dlq",
      SKILL_REGISTRY_DLQ_RESOLUTION_V1.resolution_table,
      "skill_management_commands",
      "skill_catalog_revisions",
      "skill_catalog_revision_entries",
      "skill_catalog_current",
      "skill_permission_summary_snapshots",
      "skill_permission_summary_entries",
      "skill_object_access_decisions",
      "skill_security_state",
      "eventing_transport_epochs",
    ],
    table_permissions: [
    {
      table_name: "skills",
      select_columns: ["id","skill_key","name","title","description","owner_ref","status","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "skill_version_staging",
      select_columns: ["id","skill_id","skill_name","proposed_version","artifact_ref","object_access_decision_ref","owner_object_id","owner_state_version","package_digest","manifest_digest","manifest","runtime_target","media_type","size_bytes","provenance","validation_result","scanner_versions","validation_expires_at","status","staging_state_version","created_by","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "skill_validation_attempts",
      select_columns: ["attempt_id","idempotency_key","request_hash","request_payload","outcome","validation_id","validation_record","success_payload","error_payload","response_hash","terminal_fingerprint","expires_at","actor_principal_id","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_versions",
      select_columns: ["id","skill_id","version","package_digest","manifest_digest","runtime_target","lifecycle_state","lifecycle_version","provenance","validation_result","scanner_versions","validation_id","published_at","deprecated_at","revoked_at","revocation_epoch","created_by","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "skill_packages",
      select_columns: ["id","version_id","package_ref","object_access_decision_ref","owner_object_id","owner_state_version","media_type","size_bytes","file_count","package_digest","manifest_digest","manifest","scan_result","retention_state","retention_until","deletion_requested_at","deleted_at","delete_error","state_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "skill_package_retention_transitions",
      select_columns: ["id","package_id","from_state","to_state","from_state_version","to_state_version","reason_code","actor_principal_id","object_store_deletion_decision_version","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_package_retention_holds",
      select_columns: ["id","package_id","hold_type","reason_code","active","expires_at","actor_principal_id","created_at","released_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "skill_activation_revisions",
      select_columns: ["id","skill_id","workspace_id","bot_id","deployment_environment","release_channel","version_id","state","revision_no","previous_revision_id","actor_principal_id","reason","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_activation_current",
      select_columns: ["skill_id","workspace_id","bot_id","deployment_environment","release_channel","activation_revision_id","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "pointer_cas",
    },
    {
      table_name: "skill_permission_revisions",
      select_columns: ["id","skill_id","workspace_id","bot_id","deployment_environment","release_channel","owner_agent_id","decision","capability_refs","scope_hash","revision_no","previous_revision_id","actor_principal_id","reason","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_permission_current",
      select_columns: ["skill_id","workspace_id","bot_id","deployment_environment","release_channel","scope_hash","permission_revision_id","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "pointer_cas",
    },
    {
      table_name: "skill_resolution_attempts",
      select_columns: ["id","runtime_run_id","start_attempt_no","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","policy_input_ref","policy_input_hash","policy_input_created_at","policy_expires_at","requested_catalog_version","effective_catalog_version","catalog_as_of","security_revocation_epoch","skill_permission_summary_ref","skill_permission_summary_hash","request_hash","idempotency_key","status","error_code","response_payload","valid_until","trace_id","created_at","completed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "skill_resolutions",
      select_columns: ["id","resolution_attempt_id","runtime_run_id","start_attempt_no","skill_id","skill_key","required","version_id","package_digest","manifest_digest","runtime_target","permission_decision","granted_capability_refs","status","resolution_token_hash","valid_until","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_candidate_applications",
      select_columns: ["id","candidate_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","review_version","candidate_type","skill_key","baseline_catalog_version","proposal_ref","proposal_hash","evidence_refs","reviewed_by","schema_version","idempotency_key","request_hash","status","staging_version_id","review_ref","response_ref","response_hash","trace_id","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "skill_audit_logs",
      select_columns: ["id","skill_id","version_id","runtime_run_id","application_id","actor","action","decision","reason_code","evidence_refs","payload","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_event_outbox",
      select_columns: ["id","event_type","schema_version","producer","occurred_at","idempotency_key","trace_id","payload","payload_hash","target","status","attempt_count","next_retry_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "skill_event_inbox",
      select_columns: ["id","source","event_id","scope_fingerprint","idempotency_key","payload_hash","semantic_hash","processed_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_event_dlq",
      select_columns: ["id","source_event_id","event_type","payload","last_error","failed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    SKILL_REGISTRY_DLQ_RESOLUTION_V1.table_permission,
    {
      table_name: "skill_management_commands",
      select_columns: ["id","operation","scope_kind","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","skill_id","version_id","target_version_id","capability_refs","scope_hash","expected_catalog_version","expected_activation_revision","expected_permission_revision","expected_lifecycle_version","emergency","request_hash","idempotency_key","actor_principal_id","actor_role","reason","status","previous_lifecycle_version","new_lifecycle_version","result_revision","result_catalog_version","result_security_revocation_epoch","response_payload","error","trace_id","created_at","completed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_catalog_revisions",
      select_columns: ["id","workspace_id","bot_id","deployment_environment","release_channel","catalog_version","catalog_as_of","security_revocation_epoch","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_catalog_revision_entries",
      select_columns: ["catalog_revision_id","workspace_id","bot_id","deployment_environment","release_channel","skill_id","activation_revision_id","version_id","package_digest","manifest_digest","runtime_target"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_catalog_current",
      select_columns: ["workspace_id","bot_id","deployment_environment","release_channel","catalog_revision_id","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "pointer_cas",
    },
    {
      table_name: "skill_permission_summary_snapshots",
      select_columns: ["summary_ref","schema_version","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","catalog_revision_id","catalog_version","catalog_as_of","security_revocation_epoch","canonical_bytes","summary_hash","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_permission_summary_entries",
      select_columns: ["summary_ref","ordinal","skill_id","skill_key","activation_revision_id","version_id","decision","decision_source","permission_revision_id","revision_no","scope_hash","owner_agent_condition","capability_refs"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_object_access_decisions",
      select_columns: ["id","owner_object_id","owner_state_version","object_ref","operation","purpose","capability","scope_kind","prior_access_decision_ref","retention_policy_version","redaction_policy_version","decision","expires_at","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "skill_security_state",
      select_columns: ["singleton_key","security_revocation_epoch","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    ownerEventingTransportEpochTablePermissionV1(),
    ],
    mutable_writers: [
      ...SKILL_EVENT_RECONCILIATION_V1.mutable_writers,
      "transition_skill_version_lifecycle_v1",
      "create_skill_version_staging_v1",
      "settle_skill_validation_v1",
      "publish_skill_version_v1",
      "append_skill_management_command_v1",
      "cas_skill_activation_current_v1",
      "cas_skill_permission_current_v1",
      "cas_skill_catalog_current_v1",
      "transition_skill_resolution_attempt_v1",
      "fail_skill_resolution_attempt_v1",
      "complete_empty_skill_resolution_attempt_v1",
      "transition_skill_candidate_application_v1",
      "transition_skill_package_retention_v1",
      "create_skill_package_retention_hold_v1",
      "release_skill_package_retention_hold_v1",
      "create_skill_permission_summary_snapshot_v1",
      "create_skill_resolution_attempt_v1",
      "record_skill_object_access_decision_v1",
      "record_skill_content_audit_v1",
      "claim_skill_event_outbox_v1",
      "ack_skill_event_outbox_v1",
      "activate_eventing_transport_epoch_v1",
      ...SKILL_REGISTRY_DLQ_RESOLUTION_V1.mutable_writers,
    ],
    function_signatures: [
    ...SKILL_EVENT_RECONCILIATION_V1.function_signatures,
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "transition_skill_version_lifecycle_v1",
      primary_table: "skill_versions",
      writer_kind: "state_transition",
      arguments: [["p_skill_version_id", "text"], ["p_expected_lifecycle_state", "text"], ["p_expected_lifecycle_version", "bigint"], ["p_expected_security_revocation_epoch", "bigint"], ["p_next_lifecycle_state", "text"], ["p_version", "jsonb"], ["p_management_command", "jsonb"], ["p_version_event", "jsonb"], ["p_epoch_event", "jsonb", { nullable: true }], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_versions", "skill_security_state", "skill_management_commands"],
      writes_tables: ["skill_versions", "skill_security_state", "skill_management_commands", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skill_versions", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "skill_management_commands", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_security_state", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "create_skill_version_staging_v1",
      primary_table: "skills",
      writer_kind: "state_transition",
      arguments: [["p_skill_id", "text"], ["p_staging_id", "text"], ["p_skill", "jsonb"], ["p_staging", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skills", "skill_version_staging"],
      writes_tables: ["skills", "skill_version_staging", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skills", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_version_staging", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "settle_skill_validation_v1",
      primary_table: "skill_validation_attempts",
      writer_kind: "immutable_append",
      arguments: [
        ["p_attempt_id", "text"],
        ["p_outcome", "text"],
        ["p_request", "jsonb"],
        ["p_request_hash", "text"],
        ["p_validation_record", "jsonb", { nullable: true }],
        ["p_success", "jsonb", { nullable: true }],
        ["p_error", "jsonb", { nullable: true }],
        ["p_response_hash", "text"],
        ["p_terminal_fingerprint", "text"],
        ["p_idempotency_key", "text"],
        ["p_expires_at", "timestamptz"],
        ["p_actor_principal_id", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: [
        "skill_validation_attempts",
        "skill_version_staging",
      ],
      writes_tables: [
        "skill_validation_attempts",
        "skill_version_staging",
        "skill_audit_logs",
      ],
      effects: [
        {
          table_name: "skill_validation_attempts",
          operation: "append",
          concurrency_control: "idempotency_key",
        },
        {
          table_name: "skill_version_staging",
          operation: "append",
          concurrency_control: "idempotency_key",
        },
        {
          table_name: "skill_audit_logs",
          operation: "append",
          concurrency_control: "idempotency_key",
        },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "publish_skill_version_v1",
      primary_table: "skill_versions",
      writer_kind: "state_transition",
      arguments: [["p_skill_version_id", "text"], ["p_package_id", "text"], ["p_staging_id", "text"], ["p_expected_staging_status", "text"], ["p_expected_staging_state_version", "bigint"], ["p_version", "jsonb"], ["p_package", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_version_staging", "skill_versions", "skill_packages"],
      writes_tables: ["skill_version_staging", "skill_versions", "skill_packages", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skill_version_staging", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "skill_versions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_packages", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "append_skill_management_command_v1",
      primary_table: "skill_management_commands",
      writer_kind: "immutable_append",
      arguments: [["p_command_id", "text"], ["p_command", "jsonb"], ["p_source_event", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_payload_hash", "text"], ["p_semantic_hash", "text"], ["p_scope_fingerprint", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_management_commands", "skill_event_inbox"],
      writes_tables: ["skill_management_commands", "skill_event_inbox", "skill_event_dlq", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skill_management_commands", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_inbox", operation: "append", concurrency_control: "durable_event_identity" },
        { table_name: "skill_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "cas_skill_activation_current_v1",
      primary_table: "skill_activation_current",
      writer_kind: "pointer_cas",
      arguments: [["p_skill_id", "text"], ["p_operation", "text"], ["p_expected_activation_revision_id", "text"], ["p_expected_catalog_version", "text"], ["p_activation_revision", "jsonb"], ["p_catalog_revision", "jsonb"], ["p_catalog_entries", "jsonb"], ["p_management_command", "jsonb"], ["p_activation_event", "jsonb"], ["p_catalog_event", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_versions", "skill_activation_current", "skill_activation_revisions", "skill_catalog_current", "skill_catalog_revisions", "skill_catalog_revision_entries"],
      writes_tables: ["skill_activation_revisions", "skill_activation_current", "skill_catalog_revisions", "skill_catalog_revision_entries", "skill_catalog_current", "skill_management_commands", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skill_activation_revisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_activation_current", operation: "cas", concurrency_control: "expected_version" },
        { table_name: "skill_catalog_revisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_catalog_revision_entries", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_catalog_current", operation: "cas", concurrency_control: "expected_version" },
        { table_name: "skill_management_commands", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "cas_skill_permission_current_v1",
      primary_table: "skill_permission_current",
      writer_kind: "pointer_cas",
      arguments: [["p_skill_id", "text"], ["p_operation", "text"], ["p_expected_permission_revision_id", "text"], ["p_expected_catalog_version", "text"], ["p_permission_revision", "jsonb"], ["p_catalog_revision", "jsonb"], ["p_catalog_entries", "jsonb"], ["p_summary", "jsonb"], ["p_management_command", "jsonb"], ["p_permission_event", "jsonb"], ["p_catalog_event", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_permission_current", "skill_permission_revisions", "skill_catalog_current", "skill_catalog_revisions", "skill_catalog_revision_entries", "skill_management_commands"],
      writes_tables: ["skill_permission_revisions", "skill_permission_current", "skill_permission_summary_snapshots", "skill_permission_summary_entries", "skill_catalog_revisions", "skill_catalog_revision_entries", "skill_catalog_current", "skill_management_commands", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skill_permission_revisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_permission_current", operation: "cas", concurrency_control: "expected_version" },
        { table_name: "skill_permission_summary_snapshots", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_permission_summary_entries", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_catalog_revisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_catalog_revision_entries", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_catalog_current", operation: "cas", concurrency_control: "expected_version" },
        { table_name: "skill_management_commands", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "cas_skill_catalog_current_v1",
      primary_table: "skill_catalog_current",
      writer_kind: "pointer_cas",
      arguments: [["p_catalog_key", "text"], ["p_expected_catalog_version", "text"], ["p_catalog_revision", "jsonb"], ["p_entries", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_catalog_current", "skill_catalog_revisions"],
      writes_tables: ["skill_catalog_revisions", "skill_catalog_revision_entries", "skill_catalog_current", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skill_catalog_revisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_catalog_revision_entries", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_catalog_current", operation: "cas", concurrency_control: "expected_version" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "transition_skill_resolution_attempt_v1",
      primary_table: "skill_resolution_attempts",
      writer_kind: "state_transition",
      arguments: [["p_attempt_id", "text"], ["p_expected_status", "text"], ["p_next_status", "text"], ["p_expected_catalog_version", "text"], ["p_catalog_as_of", "timestamptz"], ["p_expected_security_revocation_epoch", "bigint"], ["p_policy_input_hash", "text"], ["p_skill_permission_summary_ref", "text"], ["p_skill_permission_summary_hash", "text"], ["p_resolution", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_resolution_attempts", "skill_versions", "skill_activation_revisions", "skill_activation_current", "skill_permission_revisions", "skill_permission_current", "skill_catalog_revisions", "skill_catalog_revision_entries", "skill_catalog_current", "skill_permission_summary_snapshots", "skill_permission_summary_entries", "skill_security_state"],
      // Resolution is an owner-local, idempotent read decision. It has no
      // contract-approved downstream event, so enqueueing a synthetic outbox
      // row would either violate the event registry or manufacture a false
      // integration signal. Keep the terminal audit durable, but do not make
      // resolution success depend on a non-existent event payload.
      writes_tables: ["skill_resolution_attempts", "skill_resolutions", "skill_audit_logs"],
      effects: [
        { table_name: "skill_resolution_attempts", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "skill_resolutions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    // A failed resolution has no `skill_resolutions` rows when a requested
    // key does not exist.  Keep this terminal state in its own writer so the
    // success writer never has to manufacture a foreign-key-invalid row.
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "fail_skill_resolution_attempt_v1",
      primary_table: "skill_resolution_attempts",
      writer_kind: "state_transition",
      arguments: [["p_attempt_id", "text"], ["p_expected_status", "text"], ["p_expected_catalog_version", "text"], ["p_expected_security_revocation_epoch", "bigint"], ["p_error_code", "text"], ["p_failure", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_resolution_attempts", "skill_catalog_revisions", "skill_security_state"],
      writes_tables: ["skill_resolution_attempts", "skill_audit_logs"],
      effects: [
        { table_name: "skill_resolution_attempts", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    // Optional skills may all be unavailable.  The response is still a
    // successful, durable resolution, but there is intentionally no row to
    // insert into `skill_resolutions` (whose skill_id is required).  Keep the
    // terminal-attempt write distinct from the per-skill success writer.
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "complete_empty_skill_resolution_attempt_v1",
      primary_table: "skill_resolution_attempts",
      writer_kind: "state_transition",
      arguments: [["p_attempt_id", "text"], ["p_expected_status", "text"], ["p_expected_catalog_version", "text"], ["p_expected_security_revocation_epoch", "bigint"], ["p_completion", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_resolution_attempts", "skill_catalog_revisions", "skill_security_state"],
      writes_tables: ["skill_resolution_attempts", "skill_audit_logs"],
      effects: [
        { table_name: "skill_resolution_attempts", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "transition_skill_candidate_application_v1",
      primary_table: "skill_candidate_applications",
      writer_kind: "state_transition",
      arguments: [["p_application_id", "text"], ["p_workspace_id", "text"], ["p_bot_id", "text"], ["p_deployment_environment", "text"], ["p_release_channel", "text"], ["p_baseline_catalog_version", "text"], ["p_application", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_candidate_applications", "skill_catalog_current", "skill_catalog_revisions"],
      writes_tables: ["skill_candidate_applications", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skill_candidate_applications", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_candidate_applications", operation: "append", concurrency_control: "catalog_baseline_fence" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "transition_skill_package_retention_v1",
      primary_table: "skill_packages",
      writer_kind: "state_transition",
      arguments: [["p_package_id", "text"], ["p_expected_state_version", "bigint"], ["p_to_state", "text"], ["p_reason_code", "text"], ["p_actor_principal_id", "text"], ["p_object_store_deletion_decision_version", "bigint", { nullable: true }], ["p_trace_id", "text"]],
      reads_tables: ["skill_packages", "skill_versions", "skill_activation_current", "skill_activation_revisions", "skill_catalog_current", "skill_catalog_revision_entries", "skill_resolutions", "skill_package_retention_holds"],
      writes_tables: ["skill_packages", "skill_package_retention_transitions", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skill_packages", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "skill_package_retention_transitions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "create_skill_package_retention_hold_v1",
      primary_table: "skill_package_retention_holds",
      writer_kind: "state_transition",
      arguments: [["p_hold_id", "text"], ["p_package_id", "text"], ["p_hold", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_packages", "skill_package_retention_holds"],
      writes_tables: ["skill_package_retention_holds", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skill_package_retention_holds", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "release_skill_package_retention_hold_v1",
      primary_table: "skill_package_retention_holds",
      writer_kind: "state_transition",
      arguments: [["p_hold_id", "text"], ["p_expected_active", "boolean"], ["p_expected_created_at", "timestamptz"], ["p_actor_principal_id", "text"], ["p_reason_code", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_package_retention_holds", "skill_packages", "skill_versions"],
      writes_tables: ["skill_package_retention_holds", "skill_audit_logs", "skill_event_outbox"],
      effects: [
        { table_name: "skill_package_retention_holds", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "create_skill_permission_summary_snapshot_v1",
      primary_table: "skill_permission_summary_snapshots",
      writer_kind: "immutable_append",
      arguments: [["p_summary_ref", "text"], ["p_summary", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_permission_summary_snapshots", "skill_permission_summary_entries", "skill_catalog_revisions"],
      writes_tables: ["skill_permission_summary_snapshots", "skill_permission_summary_entries", "skill_audit_logs"],
      effects: [
        { table_name: "skill_permission_summary_snapshots", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_permission_summary_entries", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    // Resolution is a two-step transition by design: persist immutable input
    // first, then fence its terminal resolved/failed transition. Without this
    // writer the transition writer can never satisfy its required `resolving`
    // row fence on a first attempt.
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "create_skill_resolution_attempt_v1",
      primary_table: "skill_resolution_attempts",
      writer_kind: "state_transition",
      arguments: [["p_attempt_id", "text"], ["p_attempt", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_resolution_attempts", "skill_catalog_revisions", "skill_security_state", "skill_permission_summary_snapshots"],
      writes_tables: ["skill_resolution_attempts", "skill_audit_logs"],
      effects: [
        { table_name: "skill_resolution_attempts", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "record_skill_object_access_decision_v1",
      primary_table: "skill_object_access_decisions",
      writer_kind: "immutable_append",
      arguments: [["p_decision_id", "text"], ["p_decision", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_object_access_decisions", "skill_version_staging", "skill_packages"],
      writes_tables: ["skill_object_access_decisions", "skill_audit_logs"],
      effects: [
        { table_name: "skill_object_access_decisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "record_skill_content_audit_v1",
      primary_table: "skill_audit_logs",
      writer_kind: "immutable_append",
      arguments: [["p_audit_id", "text"], ["p_audit", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_audit_logs", "skill_resolutions"],
      writes_tables: ["skill_audit_logs"],
      effects: [
        { table_name: "skill_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "claim_skill_event_outbox_v1",
      primary_table: "skill_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_worker_id", "text"], ["p_limit", "integer"], ["p_lease_seconds", "integer"], ["p_now", "timestamptz"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"]],
      reads_tables: ["skill_event_outbox", "eventing_transport_epochs"], writes_tables: ["skill_event_outbox"],
      effects: [{ table_name: "skill_event_outbox", operation: "claim", concurrency_control: "lease_fence" }], returns: "setof jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "skill_registry",
      function_name: "ack_skill_event_outbox_v1",
      primary_table: "skill_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_outbox_id", "text"], ["p_claim_token", "text"], ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"], ["p_error", "jsonb"], ["p_transport_ref", "text"], ["p_transport_epoch", "text"], ["p_transport_generation", "bigint"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"], ["p_now", "timestamptz"]],
      reads_tables: ["skill_event_outbox", "eventing_transport_epochs"], writes_tables: ["skill_event_outbox", "skill_event_dlq"],
      effects: [
        { table_name: "skill_event_outbox", operation: "ack", concurrency_control: "lease_fence" },
        { table_name: "skill_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ownerEventingTransportEpochActivationSignatureV1("skill_registry"),
    ...SKILL_REGISTRY_DLQ_RESOLUTION_V1.function_signatures,
    ],
    // The generator imports this module under an explicit cache-busting
    // `?writer=` URL so it can attest a changed signature before the new
    // artifact exists. Normal application imports never carry that marker
    // and therefore remain fail-closed on exact artifact drift.
    ...(new URL(import.meta.url).searchParams.has("writer")
      ? {}
      : { writer_artifacts: SKILL_REGISTRY_WRITER_ARTIFACTS_V1 }),
  database_columns: SKILL_REGISTRY_DATABASE_COLUMNS_V1,
  database_checks: SKILL_REGISTRY_DATABASE_CHECKS_V1,
  database_functions: SKILL_REGISTRY_DATABASE_FUNCTIONS_V1,
  database_triggers: SKILL_REGISTRY_DATABASE_TRIGGERS_V1,
  database_unique_constraints: SKILL_REGISTRY_DATABASE_UNIQUE_CONSTRAINTS_V1,
  database_indexes: SKILL_REGISTRY_DATABASE_INDEXES_V1,
  foreign_key_snapshot: {
    status: "complete",
    source:
      "Database Design revision 585 contract target; pai-infra fresh 0450_skill_registry must supply the version-pinned physical and writer artifacts before live verification",
  },
  foreign_keys: SKILL_REGISTRY_FOREIGN_KEYS_V1,
  append_only_tables: [
      "skill_validation_attempts",
      "skill_package_retention_transitions",
      "skill_activation_revisions",
      "skill_permission_revisions",
      "skill_resolutions",
      "skill_audit_logs",
      "skill_event_outbox",
      "skill_event_inbox",
      "skill_event_dlq",
      SKILL_REGISTRY_DLQ_RESOLUTION_V1.resolution_table,
      "skill_management_commands",
      "skill_catalog_revisions",
      "skill_catalog_revision_entries",
      "skill_permission_summary_snapshots",
      "skill_permission_summary_entries",
    ],
    outbox_tables: ["skill_event_outbox"],
    inbox_tables: ["skill_event_inbox"],
    dlq_tables: ["skill_event_dlq"],
    dlq_resolutions: [
      SKILL_REGISTRY_DLQ_RESOLUTION_V1.binding,
    ],
    object_metadata_tables: [
      "skill_version_staging",
      "skill_packages",
      "skill_package_retention_transitions",
      "skill_package_retention_holds",
    ],
  } as const);

export interface SkillRegistryRepositoryPortV1
  extends OwnerRepositoryPortV1<typeof SKILL_REGISTRY_REPOSITORY_CONTRACT_V1> {}

export type SkillRegistryUnitOfWorkPortV1 = OwnerUnitOfWorkPortV1<
  "skill_registry",
  Readonly<{ owner: SkillRegistryRepositoryPortV1 }>
>;
