import { OWNER_DURABLE_EVENT_TYPES_V1 } from "@pai/contracts";
import {
  defineOwnerRepositoryContractV1,
  ownerEventingTransportEpochActivationSignatureV1,
  ownerEventingTransportEpochTablePermissionV1,
  ownerForeignKeysV1,
  ownerFunctionSignatureV1,
  type OwnerRepositoryPortV1,
  type OwnerUnitOfWorkPortV1,
} from "@pai/persistence";

export const META_COGNITION_REPOSITORY_CONTRACT_V1 =
  defineOwnerRepositoryContractV1({
    contract_version: "owner_repository_contract.v1",
    owner_service: "meta_cognition",
    schema: "meta_cognition",
    app_role: "pai_meta_cognition_app",
    fresh_migrations: ["0400_meta_cognition"],
    manifest_source:
      "services/meta-cognition/src/db/permission-manifest.v1.ts",
    generated_permission_sql: [
      "pai-infra/supabase/generated/permissions/0400_meta_cognition.sql",
    ],
    tables: [
      "meta_jobs",
      "meta_job_leases",
      "trigger_process_events",
      "experience_records",
      "meta_results",
      "quality_signals",
      "feedback_requests",
      "skill_candidates",
      "personality_suggestions",
      "meta_event_outbox",
      "meta_event_inbox",
      "meta_event_dlq",
      "meta_job_audit_logs",
      "meta_command_outbox",
      "meta_memory_split_plans",
      "meta_memory_split_chunks",
      "eventing_transport_epochs",
    ],
    table_permissions: [
    {
      table_name: "meta_jobs",
      select_columns: ["id","trigger_process_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","snapshot_ref","snapshot_version","snapshot_hash","snapshot_retention_until","cooldown_until","boundary_system_event_ref","learnable_snapshot_ready","enqueue_reason","idempotency_key","trace_id","request_schema_version","request_hash","input_revision","status","next_retry_at","error","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "meta_job_leases",
      select_columns: ["job_id","lease_id","lease_generation","owner_id","lease_expires_at","heartbeat_at","recovery_state","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "lease_fence",
    },
    {
      table_name: "trigger_process_events",
      select_columns: ["id","trigger_process_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","sequence_no","event_type","idempotency_key","payload","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "experience_records",
      select_columns: ["id","trigger_process_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","summary","execution_summary","reflection_summary","evidence_refs","quality_score","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "meta_results",
      select_columns: ["id","meta_job_id","trigger_process_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","result_version","memory_write_refs","knowthat_write_refs","candidate_review_refs","skill_candidate_refs","personality_suggestion_refs","quality_signal_refs","payload","created_at","updated_at","finalized_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "quality_signals",
      select_columns: ["id","trigger_process_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","signal_type","severity","source_kind","source_service","actor_principal","actor_role","source_ref","evidence_refs","recommended_action","payload","schema_version","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "feedback_requests",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","source_kind","trigger_process_id","meta_job_id","source_service","source_ref","command_id","conflict_id","candidate_id","dedupe_scope_ref","question_key","question_payload","question_payload_hash","status","answered_by_trigger_id","answer_payload","target_actor_ref","target_binding_ref","delivery_mode","delivery_channel","delivery_status","delivery_version","delivery_id","delivery_last_error","delivered_at","expires_at","idempotency_key","payload_schema_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "skill_candidates",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","trigger_process_id","meta_job_id","candidate_type","skill_key","title","proposal_payload","proposal_hash","baseline_catalog_version","reason","evidence_refs","status","downstream_status","idempotency_key","review_version","review_idempotency_key","review_request_hash","review_response_payload","review_owner_service","reviewed_by","reviewed_at","review_reason","registry_application_id","downstream_ref","delivery_last_error","superseded_by_candidate_id","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "personality_suggestions",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","trigger_process_id","meta_job_id","suggestion_type","personality_ref","personality_version","personality_hash","proposed_patch","proposed_patch_hash","reason","evidence_refs","status","downstream_status","idempotency_key","review_owner_service","reviewed_by","reviewed_at","review_reason","superseded_by_suggestion_id","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "meta_event_outbox",
      select_columns: ["id","meta_job_id","trigger_process_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","event_type","idempotency_key","target","payload","payload_hash","lease_generation","request_hash","status","next_retry_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "meta_event_inbox",
      select_columns: ["id","source","event_id","scope_fingerprint","idempotency_key","payload_hash","semantic_hash","processed_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "meta_event_dlq",
      select_columns: ["id","source_event_id","event_type","payload","last_error","failed_at","resolved_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "meta_job_audit_logs",
      select_columns: ["id","meta_job_id","previous_status","next_status","previous_recovery_state","next_recovery_state","owner_id","actor","trace_id","scope","expanded_fields","source_kind","source_service","source_ref","audit_action","reason_code","reason","error","evidence_refs","schema_version","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "meta_command_outbox",
      select_columns: ["id","meta_job_id","command_type","target_service","request_payload","request_payload_ref","request_payload_hash","idempotency_key","lease_generation","status","next_retry_at","last_error","trace_id","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "meta_memory_split_plans",
      select_columns: ["id","meta_job_id","plan_version","source_items_hash","split_profile_version","max_batch_bytes","status","supersedes_plan_id","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "meta_memory_split_chunks",
      select_columns: ["id","split_plan_id","chunk_hash","memory_write_request_id","request_payload_ref","request_payload_hash","idempotency_key","client_item_ids","request_payload","status","memory_write_batch_id","response_payload","failure_ids","compensation_outbox_id","next_retry_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    ownerEventingTransportEpochTablePermissionV1(),
    ],
    mutable_writers: [
      "transition_meta_job_v1",
      "cas_meta_job_lease_v1",
      "transition_feedback_request_v1",
      "transition_skill_candidate_v1",
      "transition_personality_suggestion_v1",
      "claim_meta_event_outbox_v1",
      "ack_meta_event_outbox_v1",
      "claim_meta_command_outbox_v1",
      "ack_meta_command_outbox_v1",
      "activate_eventing_transport_epoch_v1",
    ],
    function_signatures: [
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "transition_meta_job_v1",
      primary_table: "meta_jobs",
      writer_kind: "state_transition",
      arguments: [["p_job_id", "text"], ["p_expected_status", "text"], ["p_next_status", "text"], ["p_result", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["meta_jobs", "trigger_process_events"],
      writes_tables: ["meta_jobs", "trigger_process_events", "experience_records", "meta_results", "quality_signals", "meta_job_audit_logs", "meta_memory_split_plans", "meta_memory_split_chunks", "meta_event_inbox", "meta_event_outbox"],
      effects: [
        { table_name: "meta_jobs", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "trigger_process_events", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "experience_records", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_results", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "quality_signals", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_memory_split_plans", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "meta_memory_split_chunks", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_inbox", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "cas_meta_job_lease_v1",
      primary_table: "meta_job_leases",
      writer_kind: "lease_fence",
      arguments: [["p_job_id", "text"], ["p_expected_fence_generation", "bigint"], ["p_holder_id", "text"], ["p_lease_until", "timestamptz"], ["p_trace_id", "text"]],
      reads_tables: ["meta_job_leases"],
      writes_tables: ["meta_job_leases", "meta_job_audit_logs", "meta_event_outbox"],
      effects: [
        { table_name: "meta_job_leases", operation: "cas", concurrency_control: "generation_fence" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "transition_feedback_request_v1",
      primary_table: "feedback_requests",
      writer_kind: "state_transition",
      arguments: [["p_request_id", "text"], ["p_expected_status", "text"], ["p_next_status", "text"], ["p_feedback", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["feedback_requests"],
      writes_tables: ["feedback_requests", "meta_job_audit_logs", "meta_event_outbox", "meta_command_outbox"],
      effects: [
        { table_name: "feedback_requests", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "meta_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "transition_skill_candidate_v1",
      primary_table: "skill_candidates",
      writer_kind: "state_transition",
      arguments: [["p_candidate_id", "text"], ["p_expected_status", "text"], ["p_next_status", "text"], ["p_candidate", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_candidates"],
      writes_tables: ["skill_candidates", "meta_job_audit_logs", "meta_event_outbox", "meta_command_outbox"],
      effects: [
        { table_name: "skill_candidates", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "meta_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "transition_personality_suggestion_v1",
      primary_table: "personality_suggestions",
      writer_kind: "state_transition",
      arguments: [["p_suggestion_id", "text"], ["p_expected_status", "text"], ["p_next_status", "text"], ["p_suggestion", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["personality_suggestions"],
      writes_tables: ["personality_suggestions", "meta_job_audit_logs", "meta_event_outbox", "meta_command_outbox"],
      effects: [
        { table_name: "personality_suggestions", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "meta_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "claim_meta_event_outbox_v1",
      primary_table: "meta_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_worker_id", "text"], ["p_limit", "integer"], ["p_lease_seconds", "integer"], ["p_now", "timestamptz"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"]],
      reads_tables: ["meta_event_outbox", "eventing_transport_epochs"], writes_tables: ["meta_event_outbox"],
      effects: [{ table_name: "meta_event_outbox", operation: "claim", concurrency_control: "lease_fence" }], returns: "setof jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "ack_meta_event_outbox_v1",
      primary_table: "meta_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_outbox_id", "text"], ["p_claim_token", "text"], ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"], ["p_error", "jsonb"], ["p_transport_ref", "text"], ["p_transport_epoch", "text"], ["p_transport_generation", "bigint"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"], ["p_now", "timestamptz"]],
      reads_tables: ["meta_event_outbox", "eventing_transport_epochs"], writes_tables: ["meta_event_outbox", "meta_event_dlq"],
      effects: [
        { table_name: "meta_event_outbox", operation: "ack", concurrency_control: "lease_fence" },
        { table_name: "meta_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "claim_meta_command_outbox_v1",
      primary_table: "meta_command_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_worker_id", "text"], ["p_limit", "integer"], ["p_lease_seconds", "integer"], ["p_now", "timestamptz"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"]],
      reads_tables: ["meta_command_outbox", "eventing_transport_epochs"], writes_tables: ["meta_command_outbox"],
      effects: [{ table_name: "meta_command_outbox", operation: "claim", concurrency_control: "lease_fence" }], returns: "setof jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "ack_meta_command_outbox_v1",
      primary_table: "meta_command_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_outbox_id", "text"], ["p_claim_token", "text"], ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"], ["p_error", "jsonb"], ["p_transport_ref", "text"], ["p_transport_epoch", "text"], ["p_transport_generation", "bigint"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"], ["p_now", "timestamptz"]],
      reads_tables: ["meta_command_outbox", "eventing_transport_epochs"], writes_tables: ["meta_command_outbox", "meta_event_dlq"],
      effects: [
        { table_name: "meta_command_outbox", operation: "ack", concurrency_control: "lease_fence" },
        { table_name: "meta_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ownerEventingTransportEpochActivationSignatureV1("meta_cognition"),
    ],
    database_checks: [
      {
        constraint_name: "eventing_transport_epochs_active_generation_safe_check",
        table_name: "eventing_transport_epochs",
        required_definition_fragments: [
          "active_generation >= 1",
          "active_generation <= 9007199254740991",
        ],
        semantic_constraint: {
          kind: "integer_range",
          column_name: "active_generation",
          min: 1,
          max: Number.MAX_SAFE_INTEGER,
        },
      },
      {
        constraint_name: "meta_event_outbox_event_type_check",
        table_name: "meta_event_outbox",
        required_definition_fragments: ["event_type", "meta.job.failed"],
        semantic_constraint: {
          kind: "text_enum",
          column_name: "event_type",
          allowed_values: OWNER_DURABLE_EVENT_TYPES_V1.meta_cognition,
        },
      },
      {
        constraint_name: "meta_event_outbox_payload_check",
        table_name: "meta_event_outbox",
        required_definition_fragments: [
          "payload",
          "jsonb_object_length",
          "producer",
          "meta_cognition",
        ],
        semantic_constraint: {
          kind: "json_text_equals",
          column_name: "payload",
          field_name: "producer",
          value: "meta_cognition",
          required_keys: [
            "schema_version",
            "producer",
            "occurred_at",
            "trace_id",
            "payload",
          ],
        },
      },
    ],
    foreign_key_snapshot: {
    status: "complete",
    source: "Database Design revision 466 / fresh 0400_meta_cognition canonical DDL applied to PostgreSQL 17",
  },
  foreign_keys: ownerForeignKeysV1("meta_cognition", [
    ["feedback_requests_meta_job_id_fkey","feedback_requests",["meta_job_id"],"meta_jobs",["id"]],
    ["meta_command_outbox_meta_job_id_fkey","meta_command_outbox",["meta_job_id"],"meta_jobs",["id"]],
    ["meta_job_audit_logs_meta_job_id_fkey","meta_job_audit_logs",["meta_job_id"],"meta_jobs",["id"]],
    ["meta_job_leases_job_id_fkey","meta_job_leases",["job_id"],"meta_jobs",["id"]],
    ["meta_memory_split_chunks_compensation_outbox_id_fkey","meta_memory_split_chunks",["compensation_outbox_id"],"meta_command_outbox",["id"]],
    ["meta_memory_split_chunks_split_plan_id_fkey","meta_memory_split_chunks",["split_plan_id"],"meta_memory_split_plans",["id"]],
    ["meta_memory_split_plans_meta_job_id_fkey","meta_memory_split_plans",["meta_job_id"],"meta_jobs",["id"]],
    ["meta_memory_split_plans_supersedes_plan_id_fkey","meta_memory_split_plans",["supersedes_plan_id"],"meta_memory_split_plans",["id"]],
    ["meta_results_meta_job_id_fkey","meta_results",["meta_job_id"],"meta_jobs",["id"]],
    ["personality_suggestions_meta_job_id_fkey","personality_suggestions",["meta_job_id"],"meta_jobs",["id"]],
    ["personality_suggestions_superseded_by_suggestion_id_fkey","personality_suggestions",["superseded_by_suggestion_id"],"personality_suggestions",["id"]],
    ["skill_candidates_meta_job_id_fkey","skill_candidates",["meta_job_id"],"meta_jobs",["id"]],
    ["skill_candidates_superseded_by_candidate_id_fkey","skill_candidates",["superseded_by_candidate_id"],"skill_candidates",["id"]],
  ]),
  append_only_tables: [
      "trigger_process_events",
      "experience_records",
      "meta_results",
      "quality_signals",
      "meta_event_outbox",
      "meta_event_inbox",
      "meta_event_dlq",
      "meta_job_audit_logs",
      "meta_command_outbox",
      "meta_memory_split_chunks",
    ],
    outbox_tables: ["meta_event_outbox", "meta_command_outbox"],
    inbox_tables: ["meta_event_inbox"],
    dlq_tables: ["meta_event_dlq"],
    object_metadata_tables: [],
  } as const);

export interface MetaCognitionRepositoryPortV1
  extends OwnerRepositoryPortV1<
    typeof META_COGNITION_REPOSITORY_CONTRACT_V1
  > {}

export type MetaCognitionUnitOfWorkPortV1 = OwnerUnitOfWorkPortV1<
  "meta_cognition",
  Readonly<{ owner: MetaCognitionRepositoryPortV1 }>
>;
