import {
  META_COGNITION_DATABASE_COLUMNS_V1,
  META_COGNITION_DATABASE_INDEXES_V1,
  META_COGNITION_DATABASE_CHECKS_V1,
  META_COGNITION_DATABASE_FUNCTIONS_V1,
  META_COGNITION_DATABASE_TRIGGERS_V1,
  META_COGNITION_DATABASE_UNIQUE_CONSTRAINTS_V1,
  META_COGNITION_FOREIGN_KEYS_V1,
} from "./catalog-snapshot.generated.v1.js";
import { META_COGNITION_WRITER_ARTIFACTS_V1 } from "./writer-artifacts.generated.v1.js";
import { OWNER_DURABLE_EVENT_TYPES_V1 } from "@pai/contracts";
import {
  defineOwnerRepositoryContractV1,
  ownerDlqResolutionContractV1,
  ownerEventingReconciliationContractV1,
  ownerEventingTransportEpochActivationSignatureV1,
  ownerEventingTransportEpochTablePermissionV1,
  ownerFunctionSignatureV1,
  type OwnerRepositoryPortV1,
  type OwnerUnitOfWorkPortV1,
} from "@pai/persistence";

const META_COGNITION_DLQ_RESOLUTION_V1 = ownerDlqResolutionContractV1(
  "meta_cognition",
  "meta_event_dlq",
);
const META_EVENT_RECONCILIATION_V1 =
  ownerEventingReconciliationContractV1(
    "meta_cognition",
    "meta_event_outbox",
  );

// The catalog snapshot predates the event-reconciliation writer promotion and
// therefore still lists these SECURITY DEFINER writers among private helper
// functions. A helper is intentionally verified through `database_functions`,
// whereas an app-callable writer is verified through the pinned writer
// signature/artifact path; never let one function occupy both trust paths.
const META_COGNITION_PRIVATE_DATABASE_FUNCTIONS_V1 =
  META_COGNITION_DATABASE_FUNCTIONS_V1.filter(
    ({ function_name }) =>
      !new Set<string>(META_EVENT_RECONCILIATION_V1.mutable_writers).has(
        function_name,
      ),
  );

const META_FEEDBACK_SERVICE_COMMAND_LOCK_V1 = Object.freeze({
  key_prefix: "meta_cognition:feedback_service_command:",
  identity_arguments: ["p_source_service", "p_command_id"],
  separator: ":" as const,
  order: 1,
});

const META_FEEDBACK_OPEN_SCOPE_LOCK_V1 = Object.freeze({
  key_prefix: "meta_cognition:feedback_open_scope:",
  identity_arguments: ["p_bot_id", "p_dedupe_scope_ref", "p_question_key"],
  separator: ":" as const,
  order: 2,
});

export const META_COGNITION_REPOSITORY_CONTRACT_V1 =
  defineOwnerRepositoryContractV1({
    contract_version: "owner_repository_contract.v1",
    owner_service: "meta_cognition",
    schema: "meta_cognition",
    app_role: "pai_meta_cognition_app",
    fresh_migrations: ["0400_meta_cognition"],
    manifest_source:
      "services/meta-cognition/src/db/permission-manifest.v1.ts",
    generated_permission_sql: [
      "pai-infra/supabase/generated/permissions/0400_meta_cognition.sql",
    ],
    tables: [
      "meta_jobs",
      "meta_job_leases",
      "meta_provider_output_checkpoints",
      "trigger_process_events",
      "experience_records",
      "meta_results",
      "quality_signals",
      "feedback_requests",
      "skill_candidates",
      "personality_suggestions",
      "meta_event_outbox",
      "meta_event_inbox",
      "meta_event_dlq",
      META_COGNITION_DLQ_RESOLUTION_V1.resolution_table,
      "meta_job_audit_logs",
      "meta_command_outbox",
      "meta_memory_split_plans",
      "meta_memory_split_chunks",
      "eventing_transport_epochs",
    ],
    table_permissions: [
    {
      table_name: "meta_jobs",
      select_columns: ["id","trigger_process_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","snapshot_ref","snapshot_version","snapshot_hash","snapshot_retention_until","cooldown_until","boundary_system_event_ref","learnable_snapshot_ready","enqueue_reason","idempotency_key","trace_id","request_schema_version","request_hash","input_revision","status","lease_previous_status","attempt_count","next_retry_at","error","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "meta_job_leases",
      select_columns: ["job_id","lease_id","lease_generation","owner_id","lease_expires_at","heartbeat_at","attempt","recovery_state","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "lease_fence",
    },
    {
      table_name: "meta_provider_output_checkpoints",
      select_columns: ["meta_job_id","lease_id","lease_generation","request_hash","output_hash","output","evidence_artifacts","solidified_event_range","llm_run_metadata","solidified_event_refs","provider_binding","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "trigger_process_events",
      select_columns: ["id","trigger_process_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","sequence_no","event_type","idempotency_key","payload","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "experience_records",
      select_columns: ["id","trigger_process_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","summary","execution_summary","reflection_summary","evidence_refs","quality_score","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "meta_results",
      select_columns: ["id","meta_job_id","trigger_process_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","result_version","memory_write_refs","knowthat_write_refs","candidate_review_refs","skill_candidate_refs","personality_suggestion_refs","quality_signal_refs","payload","created_at","updated_at","finalized_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "quality_signals",
      select_columns: ["id","trigger_process_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","signal_type","severity","source_kind","source_service","actor_principal","actor_role","source_ref","evidence_refs","recommended_action","payload","schema_version","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "feedback_requests",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","source_kind","trigger_process_id","meta_job_id","source_service","source_ref","command_id","request_hash","conflict_id","candidate_id","dedupe_scope_ref","question_key","question_payload_ref","question_payload","question_payload_hash","status","answered_by_trigger_id","answer_payload","target_actor_ref","target_binding_ref","delivery_mode","delivery_channel","delivery_status","delivery_version","delivery_id","delivery_attempt_count","delivery_last_error","delivered_at","expires_at","idempotency_key","payload_schema_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "skill_candidates",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","trigger_process_id","meta_job_id","candidate_type","skill_key","title","proposal_payload","proposal_hash","baseline_catalog_version","reason","evidence_refs","evidence_artifacts","status","downstream_status","idempotency_key","review_version","review_idempotency_key","review_request_hash","review_response_payload","review_owner_service","reviewed_by","reviewed_at","review_reason","registry_application_id","downstream_ref","delivery_attempt_count","delivery_last_error","superseded_by_candidate_id","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "personality_suggestions",
      select_columns: ["id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","trigger_process_id","meta_job_id","suggestion_type","personality_ref","personality_version","personality_hash","proposed_patch","proposed_patch_hash","reason","evidence_refs","status","downstream_status","idempotency_key","review_owner_service","reviewed_by","reviewed_at","review_reason","superseded_by_suggestion_id","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "meta_event_outbox",
      select_columns: ["id","meta_job_id","trigger_process_id","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","event_type","idempotency_key","target","payload","payload_hash","lease_generation","request_hash","status","attempt_count","next_retry_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "meta_event_inbox",
      select_columns: ["id","source","event_id","scope_fingerprint","idempotency_key","payload_hash","semantic_hash","processed_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "meta_event_dlq",
      select_columns: ["id","source_event_id","event_type","payload","last_error","failed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    META_COGNITION_DLQ_RESOLUTION_V1.table_permission,
    {
      table_name: "meta_job_audit_logs",
      select_columns: ["id","meta_job_id","previous_status","next_status","previous_recovery_state","next_recovery_state","owner_id","actor","trace_id","scope","expanded_fields","source_kind","source_service","source_ref","audit_action","reason_code","reason","error","evidence_refs","schema_version","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "meta_command_outbox",
      select_columns: ["id","meta_job_id","command_type","target_service","dispatch_mode","owner_request","owner_request_hash","failed_client_item_id","item_hash","source_owner_request_hash","source_idempotency_key","idempotency_key","lease_generation","status","attempt_count","next_retry_at","owner_response_schema_version","owner_response","owner_response_hash","owner_item_set_hash","last_error","trace_id","settled_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "meta_memory_split_plans",
      select_columns: ["id","meta_job_id","plan_version","source_items_hash","split_profile_version","max_batch_bytes","max_batch_items","status","supersedes_plan_id","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "meta_memory_split_chunks",
      select_columns: ["id","split_plan_id","chunk_no","chunk_hash","memory_write_request_id","request_payload_ref","request_payload_hash","idempotency_key","client_item_ids","request_payload","status","attempt_count","memory_write_batch_id","response_payload","failure_ids","compensation_outbox_id","next_retry_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    ownerEventingTransportEpochTablePermissionV1(),
    ],
    mutable_writers: [
      ...META_COGNITION_DLQ_RESOLUTION_V1.mutable_writers,
      ...META_EVENT_RECONCILIATION_V1.mutable_writers,
      "transition_meta_job_v1",
      "enqueue_meta_job_from_trigger_event_v1",
      "finalize_meta_result_v1",
      "upsert_meta_memory_split_plan_v1",
      "transition_meta_memory_split_chunk_v1",
      "cas_meta_job_lease_v1",
      "checkpoint_meta_provider_output_v1",
      "renew_meta_job_lease_v1",
      "record_meta_stale_attempt_v1",
      "create_service_feedback_request_v1",
      "create_feedback_request_v1",
      "transition_feedback_request_v1",
      "create_skill_candidate_v1",
      "transition_skill_candidate_v1",
      "create_personality_suggestion_v1",
      "transition_personality_suggestion_v1",
      "claim_meta_event_outbox_v1",
      "ack_meta_event_outbox_v1",
      "claim_meta_command_outbox_v1",
      "settle_meta_compensation_v1",
      "ack_meta_command_outbox_v1",
      "activate_eventing_transport_epoch_v1",
    ],
    function_signatures: [
      ...META_COGNITION_DLQ_RESOLUTION_V1.function_signatures,
      ...META_EVENT_RECONCILIATION_V1.function_signatures,
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "transition_meta_job_v1",
      primary_table: "meta_jobs",
      writer_kind: "state_transition",
      arguments: [["p_job_id", "text"], ["p_expected_status", "text"], ["p_expected_input_revision", "bigint"], ["p_expected_updated_at", "timestamptz"], ["p_next_status", "text"], ["p_result", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["meta_jobs"],
      writes_tables: ["meta_jobs", "meta_job_audit_logs", "meta_event_outbox"],
      effects: [
        { table_name: "meta_jobs", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "enqueue_meta_job_from_trigger_event_v1",
      primary_table: "meta_jobs",
      writer_kind: "state_transition",
      arguments: [["p_job_id", "text"], ["p_process_event_id", "text"], ["p_job", "jsonb"], ["p_process_event", "jsonb"], ["p_source_event", "jsonb"], ["p_idempotency_key", "text"], ["p_payload_hash", "text"], ["p_semantic_hash", "text"], ["p_scope_fingerprint", "text"], ["p_trace_id", "text"]],
      reads_tables: ["meta_jobs", "trigger_process_events", "meta_event_inbox"],
      writes_tables: ["meta_jobs", "trigger_process_events", "meta_event_inbox", "meta_event_dlq", "meta_job_audit_logs", "meta_event_outbox"],
      effects: [
        { table_name: "meta_jobs", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "trigger_process_events", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_inbox", operation: "append", concurrency_control: "durable_event_identity" },
        { table_name: "meta_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "finalize_meta_result_v1",
      primary_table: "meta_results",
      writer_kind: "state_transition",
      arguments: [["p_result_id", "text"], ["p_job_id", "text"], ["p_expected_job_status", "text"], ["p_expected_job_updated_at", "timestamptz"], ["p_result", "jsonb"], ["p_experience_record", "jsonb"], ["p_quality_signals", "jsonb"], ["p_skill_candidates", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["meta_jobs", "meta_results"],
      writes_tables: ["meta_results", "experience_records", "quality_signals", "skill_candidates", "meta_jobs", "meta_job_audit_logs", "meta_event_outbox"],
      effects: [
        { table_name: "meta_results", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "experience_records", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "quality_signals", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "skill_candidates", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_jobs", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "upsert_meta_memory_split_plan_v1",
      primary_table: "meta_memory_split_plans",
      writer_kind: "projection_upsert",
      arguments: [["p_job_id", "text"], ["p_expected_plan_version", "bigint"], ["p_plan", "jsonb"], ["p_chunks", "jsonb"], ["p_command_batch", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["meta_jobs", "meta_memory_split_plans", "meta_memory_split_chunks"],
      writes_tables: ["meta_memory_split_plans", "meta_memory_split_chunks", "meta_job_audit_logs", "meta_command_outbox", "meta_event_outbox"],
      effects: [
        { table_name: "meta_memory_split_plans", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "meta_memory_split_chunks", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "transition_meta_memory_split_chunk_v1",
      primary_table: "meta_memory_split_chunks",
      writer_kind: "state_transition",
      arguments: [["p_chunk_id", "text"], ["p_expected_status", "text"], ["p_expected_updated_at", "timestamptz"], ["p_next_status", "text"], ["p_result", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["meta_memory_split_chunks", "meta_memory_split_plans"],
      writes_tables: ["meta_memory_split_chunks", "meta_job_audit_logs", "meta_event_outbox"],
      effects: [
        { table_name: "meta_memory_split_chunks", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "cas_meta_job_lease_v1",
      primary_table: "meta_job_leases",
      writer_kind: "lease_fence",
      arguments: [["p_job_id", "text"], ["p_expected_fence_generation", "bigint"], ["p_holder_id", "text"], ["p_lease_until", "timestamptz"], ["p_takeover_grace_ms", "integer"], ["p_trace_id", "text"]],
      reads_tables: ["meta_jobs", "meta_job_leases"],
      writes_tables: ["meta_jobs", "meta_job_leases", "meta_job_audit_logs"],
      effects: [
        { table_name: "meta_jobs", operation: "transition", concurrency_control: "generation_fence" },
        { table_name: "meta_job_leases", operation: "cas", concurrency_control: "generation_fence" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "checkpoint_meta_provider_output_v1",
      primary_table: "meta_provider_output_checkpoints",
      writer_kind: "immutable_append",
      arguments: [
        ["p_job_id", "text"],
        ["p_lease_id", "text"],
        ["p_expected_lease_generation", "bigint"],
        ["p_request_hash", "text"],
        ["p_output_hash", "text"],
        ["p_output", "jsonb"],
        ["p_solidified_event_range", "jsonb"],
        ["p_llm_run_metadata", "jsonb"],
        ["p_solidified_event_refs", "jsonb"],
        ["p_evidence_artifacts", "jsonb"],
        ["p_provider_binding", "jsonb"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["meta_jobs", "meta_job_leases", "meta_provider_output_checkpoints"],
      writes_tables: ["meta_provider_output_checkpoints", "meta_job_audit_logs"],
      effects: [
        { table_name: "meta_provider_output_checkpoints", operation: "append", concurrency_control: "generation_fence" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "renew_meta_job_lease_v1",
      primary_table: "meta_job_leases",
      writer_kind: "lease_fence",
      arguments: [
        ["p_job_id", "text"],
        ["p_lease_id", "text"],
        ["p_expected_fence_generation", "bigint"],
        ["p_holder_id", "text"],
        ["p_lease_until", "timestamptz"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["meta_jobs", "meta_job_leases"],
      writes_tables: ["meta_job_leases", "meta_job_audit_logs"],
      effects: [
        { table_name: "meta_job_leases", operation: "cas", concurrency_control: "generation_fence" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "record_meta_stale_attempt_v1",
      primary_table: "meta_job_audit_logs",
      writer_kind: "immutable_append",
      arguments: [
        ["p_job_id", "text"],
        ["p_owner_id", "text"],
        ["p_observed_lease_generation", "bigint"],
        ["p_reason_code", "text"],
        ["p_idempotency_key", "text"],
        ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: ["meta_jobs", "meta_job_leases", "meta_job_audit_logs"],
      writes_tables: ["meta_job_audit_logs"],
      effects: [
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "create_service_feedback_request_v1",
      primary_table: "feedback_requests",
      writer_kind: "state_transition",
      arguments: [
        ["p_feedback_request_id", "text"],
        ["p_source_service", "text"],
        ["p_command_id", "text"],
        ["p_request_hash", "text"],
        ["p_bot_id", "text"],
        ["p_dedupe_scope_ref", "text"],
        ["p_question_key", "text"],
        ["p_idempotency_key", "text"],
        ["p_feedback_request", "jsonb"],
      ],
      reads_tables: ["feedback_requests"],
      writes_tables: ["feedback_requests"],
      effects: [
        {
          table_name: "feedback_requests",
          operation: "append",
          concurrency_control: "idempotency_key",
        },
        {
          table_name: "feedback_requests",
          operation: "append",
          concurrency_control: "advisory_identity_lock",
          advisory_lock: META_FEEDBACK_SERVICE_COMMAND_LOCK_V1,
        },
        {
          table_name: "feedback_requests",
          operation: "append",
          concurrency_control: "advisory_identity_lock",
          advisory_lock: META_FEEDBACK_OPEN_SCOPE_LOCK_V1,
        },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "create_feedback_request_v1",
      primary_table: "feedback_requests",
      writer_kind: "state_transition",
      arguments: [["p_request_id", "text"], ["p_job_id", "text"], ["p_expected_job_status", "text"], ["p_expected_job_updated_at", "timestamptz"], ["p_feedback_request", "jsonb"], ["p_command", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["meta_jobs", "feedback_requests"],
      writes_tables: ["feedback_requests", "meta_job_audit_logs", "meta_event_outbox", "meta_command_outbox"],
      effects: [
        { table_name: "feedback_requests", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "meta_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "transition_feedback_request_v1",
      primary_table: "feedback_requests",
      writer_kind: "state_transition",
      arguments: [["p_request_id", "text"], ["p_expected_status", "text"], ["p_expected_delivery_version", "bigint"], ["p_expected_updated_at", "timestamptz"], ["p_next_status", "text"], ["p_feedback", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["feedback_requests"],
      writes_tables: ["feedback_requests", "meta_job_audit_logs", "meta_event_outbox", "meta_command_outbox"],
      effects: [
        { table_name: "feedback_requests", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "meta_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "create_skill_candidate_v1",
      primary_table: "skill_candidates",
      writer_kind: "state_transition",
      arguments: [["p_candidate_id", "text"], ["p_job_id", "text"], ["p_expected_job_status", "text"], ["p_expected_job_updated_at", "timestamptz"], ["p_candidate", "jsonb"], ["p_command", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["meta_jobs", "skill_candidates"],
      writes_tables: ["skill_candidates", "meta_job_audit_logs", "meta_event_outbox", "meta_command_outbox"],
      effects: [
        { table_name: "skill_candidates", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "meta_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "transition_skill_candidate_v1",
      primary_table: "skill_candidates",
      writer_kind: "state_transition",
      arguments: [["p_candidate_id", "text"], ["p_expected_status", "text"], ["p_expected_review_version", "bigint"], ["p_expected_updated_at", "timestamptz"], ["p_next_status", "text"], ["p_candidate", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["skill_candidates"],
      writes_tables: ["skill_candidates", "meta_job_audit_logs", "meta_event_outbox", "meta_command_outbox"],
      effects: [
        { table_name: "skill_candidates", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "meta_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "create_personality_suggestion_v1",
      primary_table: "personality_suggestions",
      writer_kind: "state_transition",
      arguments: [["p_suggestion_id", "text"], ["p_job_id", "text"], ["p_expected_job_status", "text"], ["p_expected_job_updated_at", "timestamptz"], ["p_suggestion", "jsonb"], ["p_command", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["meta_jobs", "personality_suggestions"],
      writes_tables: ["personality_suggestions", "meta_job_audit_logs", "meta_event_outbox", "meta_command_outbox"],
      effects: [
        { table_name: "personality_suggestions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "meta_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "transition_personality_suggestion_v1",
      primary_table: "personality_suggestions",
      writer_kind: "state_transition",
      arguments: [["p_suggestion_id", "text"], ["p_expected_status", "text"], ["p_expected_updated_at", "timestamptz"], ["p_next_status", "text"], ["p_suggestion", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["personality_suggestions"],
      writes_tables: ["personality_suggestions", "meta_job_audit_logs", "meta_event_outbox", "meta_command_outbox"],
      effects: [
        { table_name: "personality_suggestions", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "meta_job_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "meta_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "meta_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "claim_meta_event_outbox_v1",
      primary_table: "meta_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_worker_id", "text"], ["p_limit", "integer"], ["p_lease_seconds", "integer"], ["p_now", "timestamptz"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"]],
      reads_tables: ["meta_event_outbox", "eventing_transport_epochs"], writes_tables: ["meta_event_outbox"],
      effects: [{ table_name: "meta_event_outbox", operation: "claim", concurrency_control: "lease_fence" }], returns: "setof jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "ack_meta_event_outbox_v1",
      primary_table: "meta_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_outbox_id", "text"], ["p_claim_token", "text"], ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"], ["p_error", "jsonb"], ["p_transport_ref", "text"], ["p_transport_epoch", "text"], ["p_transport_generation", "bigint"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"], ["p_now", "timestamptz"]],
      reads_tables: ["meta_event_outbox", "eventing_transport_epochs"], writes_tables: ["meta_event_outbox", "meta_event_dlq"],
      effects: [
        { table_name: "meta_event_outbox", operation: "ack", concurrency_control: "lease_fence" },
        { table_name: "meta_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "claim_meta_command_outbox_v1",
      primary_table: "meta_command_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_worker_id", "text"], ["p_limit", "integer"], ["p_lease_seconds", "integer"], ["p_now", "timestamptz"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"]],
      reads_tables: ["meta_command_outbox", "eventing_transport_epochs"], writes_tables: ["meta_command_outbox"],
      effects: [{ table_name: "meta_command_outbox", operation: "claim", concurrency_control: "lease_fence" }], returns: "setof jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "settle_meta_compensation_v1",
      primary_table: "meta_results",
      writer_kind: "state_transition",
      arguments: [
        ["p_command_id", "text"],
        ["p_worker_id", "text"],
        ["p_expected_lease_generation", "bigint"],
        ["p_settlement_id", "text"],
        ["p_settlement_hash", "text"],
        ["p_outcome", "text"],
        ["p_result_ref", "text", { nullable: true }],
        ["p_error_code", "text", { nullable: true }],
        ["p_next_retry_at", "timestamptz", { nullable: true }],
        ["p_expected_target_service", "text"],
        ["p_owner_request", "jsonb", { nullable: true }],
        ["p_owner_request_hash", "text", { nullable: true }],
        ["p_source_owner_request_hash", "text", { nullable: true }],
        ["p_owner_response", "jsonb", { nullable: true }],
        ["p_owner_response_hash", "text", { nullable: true }],
        ["p_expected_result_version", "bigint"],
        ["p_expected_job_status", "text"],
        ["p_expected_job_updated_at", "timestamptz"],
        ["p_trace_id", "text"],
        ["p_now", "timestamptz"],
      ],
      reads_tables: [
        "meta_command_outbox",
        "meta_results",
        "meta_jobs",
      ],
      writes_tables: [
        "meta_command_outbox",
        "meta_results",
        "meta_jobs",
        "meta_job_audit_logs",
        "meta_event_outbox",
      ],
      effects: [
        {
          table_name: "meta_command_outbox",
          operation: "ack",
          concurrency_control: "generation_fence",
        },
        {
          table_name: "meta_results",
          operation: "transition",
          concurrency_control: "expected_state_version",
        },
        {
          table_name: "meta_jobs",
          operation: "transition",
          concurrency_control: "expected_state_version",
        },
        {
          table_name: "meta_job_audit_logs",
          operation: "append",
          concurrency_control: "expected_state_version",
        },
        {
          table_name: "meta_event_outbox",
          operation: "enqueue",
          concurrency_control: "expected_state_version",
        },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "meta_cognition",
      function_name: "ack_meta_command_outbox_v1",
      primary_table: "meta_command_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_outbox_id", "text"], ["p_claim_token", "text"], ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"], ["p_error", "jsonb"], ["p_transport_ref", "text"], ["p_transport_epoch", "text"], ["p_transport_generation", "bigint"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"], ["p_now", "timestamptz"]],
      reads_tables: ["meta_command_outbox", "eventing_transport_epochs"], writes_tables: ["meta_command_outbox", "meta_event_dlq"],
      effects: [
        { table_name: "meta_command_outbox", operation: "ack", concurrency_control: "lease_fence" },
        { table_name: "meta_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
      ], returns: "jsonb",
    }),
    ownerEventingTransportEpochActivationSignatureV1("meta_cognition"),
    ],
    // The generator imports this module under an explicit cache-busting
    // `?writer=` URL so it can attest a changed signature before the new
    // artifact exists. Normal application imports never carry that marker
    // and therefore remain fail-closed on exact artifact drift.
    ...(new URL(import.meta.url).searchParams.has("writer")
      ? {}
      : { writer_artifacts: META_COGNITION_WRITER_ARTIFACTS_V1 }),
    database_columns: META_COGNITION_DATABASE_COLUMNS_V1,
    database_checks: META_COGNITION_DATABASE_CHECKS_V1,
    database_functions: META_COGNITION_DATABASE_FUNCTIONS_V1,
    database_triggers: META_COGNITION_DATABASE_TRIGGERS_V1,
    database_unique_constraints: META_COGNITION_DATABASE_UNIQUE_CONSTRAINTS_V1,
    database_indexes: META_COGNITION_DATABASE_INDEXES_V1,
    foreign_key_snapshot: {
    status: "complete",
    source: "Database Design revision 476 / fresh 0400_meta_cognition canonical DDL applied to PostgreSQL 17",
  },
  foreign_keys: META_COGNITION_FOREIGN_KEYS_V1,
  append_only_tables: [
      "trigger_process_events",
      "meta_provider_output_checkpoints",
      "experience_records",
      "quality_signals",
      "meta_event_outbox",
      "meta_event_inbox",
      "meta_event_dlq",
      META_COGNITION_DLQ_RESOLUTION_V1.resolution_table,
      "meta_job_audit_logs",
      "meta_command_outbox",
    ],
    outbox_tables: ["meta_event_outbox", "meta_command_outbox"],
    inbox_tables: ["meta_event_inbox"],
    dlq_tables: ["meta_event_dlq"],
    dlq_resolutions: [META_COGNITION_DLQ_RESOLUTION_V1.binding],
    object_metadata_tables: [],
  } as const);

export interface MetaCognitionRepositoryPortV1
  extends OwnerRepositoryPortV1<
    typeof META_COGNITION_REPOSITORY_CONTRACT_V1
  > {}

export type MetaCognitionUnitOfWorkPortV1 = OwnerUnitOfWorkPortV1<
  "meta_cognition",
  Readonly<{ owner: MetaCognitionRepositoryPortV1 }>
>;
