import {
  MEMORY_DATABASE_COLUMNS_V1,
  MEMORY_DATABASE_INDEXES_V1,
  MEMORY_DATABASE_CHECKS_V1,
  MEMORY_DATABASE_FUNCTIONS_V1,
  MEMORY_DATABASE_TRIGGERS_V1,
  MEMORY_DATABASE_UNIQUE_CONSTRAINTS_V1,
  MEMORY_FOREIGN_KEYS_V1,
} from "./catalog-snapshot.generated.v1.js";
import { MEMORY_WRITER_ARTIFACTS_V1 } from "./writer-artifacts.generated.v1.js";
import { OWNER_DURABLE_EVENT_TYPES_V1 } from "@pai/contracts";
import {
  defineOwnerRepositoryContractV1,
  ownerDlqResolutionContractV1,
  ownerEventingReconciliationContractV1,
  ownerEventingTransportEpochActivationSignatureV1,
  ownerEventingTransportEpochTablePermissionV1,
  ownerFunctionSignatureV1,
  type OwnerRepositoryPortV1,
  type OwnerUnitOfWorkPortV1,
} from "@pai/persistence";

const MEMORY_EVENT_DLQ_RESOLUTION_V1 = ownerDlqResolutionContractV1(
  "memory",
  "memory_event_dlq",
);
const MEMORY_COMMAND_DLQ_RESOLUTION_V1 = ownerDlqResolutionContractV1(
  "memory",
  "memory_command_dlq",
);
const MEMORY_EVENT_RECONCILIATION_V1 =
  ownerEventingReconciliationContractV1(
    "memory",
    "memory_event_outbox",
  );

export const MEMORY_REPOSITORY_CONTRACT_V1 = defineOwnerRepositoryContractV1({
  contract_version: "owner_repository_contract.v1",
  owner_service: "memory",
  schema: "memory",
  app_role: "pai_memory_app",
  fresh_migrations: ["0600_memory", "0610_memory_vector"],
  manifest_source: "services/memory/src/db/permission-manifest.v1.ts",
  generated_permission_sql: [
    "pai-infra/supabase/generated/permissions/0600_memory.sql",
    "pai-infra/supabase/generated/permissions/0610_memory_vector.sql",
  ],
  tables: [
    "memory_series",
    "memory_write_batches",
    "memory_points",
    "role_memories",
    "relationship_edges",
    "memory_conflicts",
    "memory_linkage_operations",
    "memory_event_outbox",
    "memory_event_inbox",
    "memory_event_dlq",
    MEMORY_EVENT_DLQ_RESOLUTION_V1.resolution_table,
    "memory_write_item_decisions",
    "memory_point_search_index",
    "memory_state_revisions",
    "memory_feedback_events",
    "memory_audit_logs",
    "memory_feedback_revision_refs",
    "memory_feedback_audit_refs",
      "memory_feedback_event_refs",
      "memory_pre_promotion_check_identities",
      "memory_pre_promotion_checks",
    "memory_promotion_reservations",
    "memory_promotion_reservation_targets",
    "memory_graph_builds",
    "memory_integration_jobs",
    "memory_integration_job_leases",
    "memory_integration_change_receipts",
    "memory_command_outbox",
    "memory_command_dlq",
    MEMORY_COMMAND_DLQ_RESOLUTION_V1.resolution_table,
    "topic_key_aliases",
    "topic_family_key_aliases",
    "memory_embedding_profiles",
    "eventing_transport_epochs",
  ],
    table_permissions: [
    {
      table_name: "memory_series",
      select_columns: ["id","bot_id","topic_key","topic_family_key","subject_key","aspect_key","scope_key","merged_into_series_id","title","status","state_version","current_version","canonicalization_version","topic_components_raw","topic_components_normalized","importance_score","last_recalled_at","last_mentioned_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "memory_write_batches",
      select_columns: ["id","bot_id","trigger_process_id","source_meta_job_id","idempotency_key","request_hash","trace_id","request_payload","response_payload","status","payload_schema_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "memory_points",
      select_columns: ["id","bot_id","series_id","version_no","content_summary","human_agent_relation","keyword_tags","scene_tags","emotion_tags","source_info","source_trigger_process_id","content_hash","series_decision","decision_reason","previous_memory_point_id","confidence_score","occurred_at","evidence_valid_until","status","payload_schema_version","state_version","embedding_profile_id","summary_embedding","embedding_backfill_status","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "role_memories",
      select_columns: ["id","bot_id","role_id","role_type","display_name","attributes","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "relationship_edges",
      select_columns: ["id","bot_id","subject_role_id","object_role_id","relation_type","confidence","evidence_memory_point_ids","valid_from","valid_until","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "memory_conflicts",
      select_columns: ["id","bot_id","series_id","conflict_type","conflict_key","conflict_domain","source_priority_policy_version","left_memory_point_id","right_memory_point_id","confidence_delta","evidence_refs","conflict_payload","proposed_resolution","status","state_version","resolution","payload_schema_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "memory_linkage_operations",
      select_columns: ["id","bot_id","source_kind","source_service","actor_principal","actor_role","source_ref","source_fact_id","source_linkage_check_id","source_memory_point_id","affected_query","linked_memory_point_ids","relationship_edge_changes","operation","historical_payload","idempotency_key","attempt_count","next_retry_at","locked_by","locked_until","last_error","reason","evidence_refs","status","payload_schema_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "memory_event_outbox",
      select_columns: ["id","event_type","schema_version","producer","bot_id","aggregate_id","aggregate_type","aggregate_version","occurred_at","idempotency_key","trace_id","target","payload","payload_hash","status","attempt_count","next_retry_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "memory_event_inbox",
      select_columns: ["id","source","event_id","scope_fingerprint","idempotency_key","payload_hash","semantic_hash","processed_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_event_dlq",
      select_columns: ["id","source_event_id","event_type","payload","last_error","failed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    MEMORY_EVENT_DLQ_RESOLUTION_V1.table_permission,
    {
      table_name: "memory_write_item_decisions",
      select_columns: ["id","bot_id","batch_id","client_item_id","source_item_id","source_trigger_process_id","content_hash","decision","target_series_id","target_memory_point_id","conflict_id","candidate_refs","decision_reason","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_point_search_index",
      select_columns: ["memory_point_id","bot_id","series_id","topic_family_key","topic_key","status","state_version","series_state_version","source_revision_ids","ranking_profile_version","content_summary","keyword_tags","scene_tags","emotion_tags","occurred_at","importance_score","last_mentioned_at","content_tsv","evidence_valid_until","embedding_profile_id","summary_embedding","embedding_backfill_status","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "memory_state_revisions",
      select_columns: ["id","bot_id","aggregate_type","aggregate_id","previous_state_version","resulting_state_version","operation","before_payload","after_payload","actor_ref","reason","evidence_refs","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_feedback_events",
      select_columns: ["id","bot_id","target_type","target_id","action","expected_state_version","resulting_state_version","idempotency_key","request_hash","request_payload","response_payload","authenticated_actor_ref","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_audit_logs",
      select_columns: ["id","bot_id","revision_id","feedback_event_id","target_type","target_id","actor_ref","action","reason_code","capability_snapshot","payload","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_feedback_revision_refs",
      select_columns: ["feedback_event_id","revision_id"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_feedback_audit_refs",
      select_columns: ["feedback_event_id","audit_id"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_feedback_event_refs",
      select_columns: ["feedback_event_id","event_id"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_pre_promotion_check_identities",
      select_columns: ["bot_id","idempotency_key","candidate_fact_id","request_hash","current_check_generation","current_check_id","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "memory_pre_promotion_checks",
      select_columns: ["id","bot_id","candidate_fact_id","idempotency_key","request_hash","required_checks","point_state_snapshot","overall_result","blocking_reasons","check_policy_version","check_token_hash","checked_at","expires_at","response_payload","check_generation","generation_status","superseded_at","superseded_reason"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "memory_promotion_reservations",
      select_columns: ["id","check_id","bot_id","candidate_fact_id","idempotency_key","request_hash","fencing_generation","reservation_token_hash","status","expires_at","committed_at","promotion_revision_id","ack_payload","release_reason","created_at","updated_at","check_generation"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "memory_promotion_reservation_targets",
      select_columns: ["reservation_id","aggregate_type","aggregate_id","expected_state_version","expected_state_hash"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_graph_builds",
      select_columns: ["id","bot_id","idempotency_key","request_hash","graph_profile_version","graph_revision","response_payload","expires_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_integration_jobs",
      select_columns: ["id","bot_id","mode","scope","dry_run","idempotency_key","request_hash","expected_policy_version","state_version","status","checkpoint_ref","result_payload","error","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "memory_integration_job_leases",
      select_columns: ["integration_job_id","lease_id","lease_generation","owner_id","lease_expires_at","heartbeat_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "lease_fence",
    },
    {
      table_name: "memory_integration_change_receipts",
      select_columns: ["change_id","integration_job_id","lease_generation","change_kind","target_type","target_id","request_hash","result_payload","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_command_outbox",
      select_columns: ["id","command_id","contract_name","source_service","source_ref","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","dedupe_scope_ref","request_payload","request_hash","trace_id","status","attempt_count","next_retry_at","last_error","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "memory_command_dlq",
      select_columns: ["id","command_outbox_id","payload","payload_hash","last_error","failed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    MEMORY_COMMAND_DLQ_RESOLUTION_V1.table_permission,
    {
      table_name: "topic_key_aliases",
      select_columns: ["id","bot_id","old_canonicalization_version","old_topic_key","new_canonicalization_version","new_topic_key","actor_ref","reason","evidence_refs","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "topic_family_key_aliases",
      select_columns: ["id","bot_id","old_canonicalization_version","old_topic_family_key","new_canonicalization_version","new_topic_family_key","actor_ref","reason","evidence_refs","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_embedding_profiles",
      select_columns: ["id","model_id","model_revision","dimensions","normalized","distance_metric","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    ownerEventingTransportEpochTablePermissionV1(),
    ],
  mutable_writers: [
    ...MEMORY_EVENT_DLQ_RESOLUTION_V1.mutable_writers,
    ...MEMORY_COMMAND_DLQ_RESOLUTION_V1.mutable_writers,
    ...MEMORY_EVENT_RECONCILIATION_V1.mutable_writers,
    "create_memory_series_v1",
    "transition_memory_series_v1",
    "append_memory_point_v1",
    "upsert_memory_relationship_projection_v1",
    "enqueue_memory_linkage_operation_v1",
    "transition_memory_linkage_operation_v1",
    "transition_memory_conflict_v1",
    "append_memory_feedback_v1",
    "append_memory_pre_promotion_check_v1",
    "record_memory_promotion_reservation_v1",
    "transition_memory_promotion_v1",
    "append_memory_graph_build_v1",
    "append_memory_canonicalization_aliases_v1",
    "append_memory_embedding_profile_v1",
    "create_memory_write_batch_v1",
    "commit_memory_write_batch_v1",
    "append_memory_state_revision_v1",
    "create_memory_integration_job_v1",
    "transition_memory_integration_job_v1",
    "cas_memory_integration_job_lease_v1",
    "renew_memory_integration_job_lease_v1",
    "apply_memory_integration_change_v1",
    "claim_memory_event_outbox_v1",
    "ack_memory_event_outbox_v1",
    "claim_memory_command_outbox_v1",
    "ack_memory_command_outbox_v1",
    "activate_eventing_transport_epoch_v1",
  ],
  function_signatures: [
    ...MEMORY_EVENT_DLQ_RESOLUTION_V1.function_signatures,
    ...MEMORY_COMMAND_DLQ_RESOLUTION_V1.function_signatures,
    ...MEMORY_EVENT_RECONCILIATION_V1.function_signatures,
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "create_memory_series_v1",
      primary_table: "memory_series",
      writer_kind: "state_transition",
      arguments: [["p_series_id", "text"], ["p_series", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_series", "memory_promotion_reservations", "memory_promotion_reservation_targets"],
      writes_tables: ["memory_series", "memory_audit_logs", "memory_event_outbox"],
      returns: "jsonb",
      effects: [
        { table_name: "memory_series", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_series", operation: "append", concurrency_control: "promotion_reservation_fence", promotion_reservation_targets: [{ aggregate_type: "memory_series", id_argument: "p_series_id" }] },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "transition_memory_series_v1",
      primary_table: "memory_series",
      writer_kind: "state_transition",
      arguments: [["p_series_id", "text"], ["p_expected_status", "text"], ["p_expected_state_version", "bigint"], ["p_next_status", "text"], ["p_series_change", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_series", "memory_promotion_reservations", "memory_promotion_reservation_targets"],
      writes_tables: ["memory_series", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_series", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "memory_series", operation: "transition", concurrency_control: "promotion_reservation_fence", promotion_reservation_targets: [{ aggregate_type: "memory_series", id_argument: "p_series_id" }] },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "append_memory_point_v1",
      primary_table: "memory_points",
      writer_kind: "state_transition",
      arguments: [["p_point_id", "text"], ["p_series_id", "text"], ["p_expected_series_version", "bigint"], ["p_point", "jsonb"], ["p_item_decision", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_series", "memory_embedding_profiles", "memory_promotion_reservations", "memory_promotion_reservation_targets"],
      writes_tables: ["memory_points", "memory_write_item_decisions", "memory_point_search_index", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_points", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_points", operation: "append", concurrency_control: "promotion_reservation_fence", promotion_reservation_targets: [{ aggregate_type: "memory_point", id_argument: "p_point_id" }, { aggregate_type: "memory_series", id_argument: "p_series_id" }] },
        { table_name: "memory_write_item_decisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_point_search_index", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "upsert_memory_relationship_projection_v1",
      primary_table: "role_memories",
      writer_kind: "projection_upsert",
      arguments: [["p_projection_key", "text"], ["p_projection", "jsonb"], ["p_conflict", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["role_memories", "relationship_edges", "memory_promotion_reservations", "memory_promotion_reservation_targets"],
      writes_tables: ["role_memories", "relationship_edges", "memory_conflicts", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "role_memories", operation: "upsert", concurrency_control: "idempotency_key" },
        { table_name: "relationship_edges", operation: "upsert", concurrency_control: "idempotency_key" },
        { table_name: "memory_conflicts", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "enqueue_memory_linkage_operation_v1",
      primary_table: "memory_linkage_operations",
      writer_kind: "state_transition",
      arguments: [["p_operation_id", "text"], ["p_operation", "jsonb"], ["p_source_event", "jsonb"], ["p_idempotency_key", "text"], ["p_payload_hash", "text"], ["p_semantic_hash", "text"], ["p_scope_fingerprint", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_linkage_operations", "memory_event_inbox"],
      writes_tables: ["memory_linkage_operations", "memory_event_inbox", "memory_event_dlq", "memory_audit_logs", "memory_event_outbox"],
      returns: "jsonb",
      effects: [
        { table_name: "memory_linkage_operations", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_inbox", operation: "append", concurrency_control: "durable_event_identity" },
        { table_name: "memory_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "transition_memory_linkage_operation_v1",
      primary_table: "memory_linkage_operations",
      writer_kind: "state_transition",
      arguments: [["p_operation_id", "text"], ["p_expected_status", "text"], ["p_expected_updated_at", "timestamptz"], ["p_next_status", "text"], ["p_operation", "jsonb"], ["p_source_event", "jsonb"], ["p_idempotency_key", "text"], ["p_payload_hash", "text"], ["p_semantic_hash", "text"], ["p_scope_fingerprint", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_linkage_operations", "memory_event_inbox"],
      writes_tables: ["memory_linkage_operations", "memory_event_inbox", "memory_event_dlq", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_linkage_operations", operation: "transition", concurrency_control: "database_row_lock" },
        { table_name: "memory_event_inbox", operation: "append", concurrency_control: "durable_event_identity" },
        { table_name: "memory_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "transition_memory_conflict_v1",
      primary_table: "memory_conflicts",
      writer_kind: "state_transition",
      arguments: [["p_conflict_id", "text"], ["p_expected_status", "text"], ["p_expected_conflict_version", "bigint"], ["p_expected_versions", "jsonb"], ["p_next_status", "text"], ["p_resolution", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_conflicts", "memory_points", "memory_series", "memory_state_revisions", "memory_point_search_index", "memory_promotion_reservations", "memory_promotion_reservation_targets"],
      writes_tables: ["memory_conflicts", "memory_series", "memory_points", "memory_state_revisions", "memory_point_search_index", "topic_key_aliases", "memory_audit_logs", "memory_event_outbox", "memory_command_outbox"],
      returns: "jsonb",
      effects: [
        { table_name: "memory_conflicts", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "memory_conflicts", operation: "transition", concurrency_control: "promotion_reservation_fence", promotion_reservation_targets: [{ aggregate_type: "memory_conflict", id_argument: "p_conflict_id" }] },
        { table_name: "memory_series", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "memory_points", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "memory_state_revisions", operation: "append", concurrency_control: "expected_version" },
        { table_name: "memory_point_search_index", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "topic_key_aliases", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "memory_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "append_memory_feedback_v1",
      primary_table: "memory_feedback_events",
      writer_kind: "immutable_append",
      arguments: [["p_feedback_id", "text"], ["p_target_type", "text"], ["p_target_id", "text"], ["p_expected_state_version", "bigint"], ["p_feedback", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_feedback_events", "memory_points", "memory_series", "memory_conflicts", "memory_state_revisions", "memory_point_search_index", "memory_promotion_reservations", "memory_promotion_reservation_targets"],
      writes_tables: ["memory_feedback_events", "memory_feedback_revision_refs", "memory_feedback_audit_refs", "memory_feedback_event_refs", "memory_points", "memory_series", "memory_conflicts", "memory_state_revisions", "memory_point_search_index", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_feedback_events", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_feedback_events", operation: "append", concurrency_control: "promotion_reservation_fence", promotion_reservation_targets: [{ aggregate_type_argument: "p_target_type", id_argument: "p_target_id" }] },
        { table_name: "memory_feedback_revision_refs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_feedback_audit_refs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_feedback_event_refs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_points", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "memory_series", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "memory_conflicts", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "memory_state_revisions", operation: "append", concurrency_control: "expected_version" },
        { table_name: "memory_point_search_index", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "append_memory_pre_promotion_check_v1",
      primary_table: "memory_pre_promotion_checks",
      writer_kind: "state_transition",
      arguments: [["p_check_id", "text"], ["p_candidate_fact_id", "text"], ["p_check", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_pre_promotion_check_identities", "memory_points", "memory_series", "memory_conflicts", "memory_promotion_reservations", "memory_promotion_reservation_targets"],
      writes_tables: ["memory_pre_promotion_check_identities", "memory_pre_promotion_checks", "memory_audit_logs"],
      returns: "jsonb",
      effects: [
        { table_name: "memory_pre_promotion_check_identities", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_pre_promotion_check_identities", operation: "transition", concurrency_control: "idempotency_key" },
        { table_name: "memory_pre_promotion_checks", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_pre_promotion_checks", operation: "transition", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "record_memory_promotion_reservation_v1",
      primary_table: "memory_promotion_reservations",
      writer_kind: "state_transition",
      arguments: [["p_reservation_id", "text"], ["p_expected_candidate_state", "jsonb"], ["p_pre_promotion_check", "jsonb"], ["p_reservation", "jsonb"], ["p_targets", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_pre_promotion_check_identities", "memory_pre_promotion_checks", "memory_points", "memory_series", "memory_conflicts", "memory_promotion_reservations", "memory_promotion_reservation_targets"],
      writes_tables: ["memory_promotion_reservations", "memory_promotion_reservation_targets", "memory_audit_logs", "memory_event_outbox"],
      returns: "jsonb",
      effects: [
        { table_name: "memory_promotion_reservations", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_promotion_reservations", operation: "transition", concurrency_control: "idempotency_key" },
        { table_name: "memory_promotion_reservation_targets", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "transition_memory_promotion_v1",
      primary_table: "memory_promotion_reservations",
      writer_kind: "state_transition",
      arguments: [["p_reservation_id", "text"], ["p_expected_status", "text"], ["p_next_status", "text"], ["p_expected_fencing_generation", "bigint"], ["p_promotion", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_pre_promotion_checks", "memory_promotion_reservations", "memory_promotion_reservation_targets"],
      writes_tables: ["memory_promotion_reservations", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_promotion_reservations", operation: "transition", concurrency_control: "generation_fence" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "append_memory_graph_build_v1",
      primary_table: "memory_graph_builds",
      writer_kind: "immutable_append",
      arguments: [["p_build_id", "text"], ["p_build_result", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_graph_builds"],
      writes_tables: ["memory_graph_builds", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_graph_builds", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "append_memory_canonicalization_aliases_v1",
      primary_table: "topic_key_aliases",
      writer_kind: "immutable_append",
      arguments: [["p_aliases", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["topic_key_aliases", "topic_family_key_aliases"],
      writes_tables: ["topic_key_aliases", "topic_family_key_aliases", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "topic_key_aliases", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "topic_family_key_aliases", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "append_memory_embedding_profile_v1",
      primary_table: "memory_embedding_profiles",
      writer_kind: "immutable_append",
      arguments: [["p_profile_id", "text"], ["p_embedding_profile", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_embedding_profiles"],
      writes_tables: ["memory_embedding_profiles", "memory_audit_logs", "memory_event_outbox"],
      returns: "jsonb",
      effects: [
        { table_name: "memory_embedding_profiles", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "create_memory_write_batch_v1",
      primary_table: "memory_write_batches",
      writer_kind: "state_transition",
      arguments: [["p_batch_id", "text"], ["p_batch", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_write_batches"],
      writes_tables: ["memory_write_batches", "memory_audit_logs", "memory_event_outbox"],
      returns: "jsonb",
      effects: [
        { table_name: "memory_write_batches", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "commit_memory_write_batch_v1",
      primary_table: "memory_write_batches",
      writer_kind: "state_transition",
      arguments: [
        ["p_batch_id", "text"],
        ["p_bot_id", "text"],
        ["p_batch_count_fence", "bigint"],
        ["p_series_fences", "jsonb"],
        ["p_point_fences", "jsonb"],
        ["p_batch", "jsonb"],
        ["p_series", "jsonb"],
        ["p_points", "jsonb"],
        ["p_conflicts", "jsonb"],
        ["p_item_decisions", "jsonb"],
        ["p_search_index", "jsonb"],
        ["p_state_revisions", "jsonb"],
        ["p_audit_logs", "jsonb"],
        ["p_event_outbox", "jsonb"],
        ["p_idempotency_key", "text"],
        ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: [
        "memory_write_batches",
        "memory_series",
        "memory_points",
        "memory_conflicts",
        "memory_promotion_reservations",
        "memory_promotion_reservation_targets",
      ],
      writes_tables: [
        "memory_write_batches",
        "memory_series",
        "memory_points",
        "memory_conflicts",
        "memory_write_item_decisions",
        "memory_point_search_index",
        "memory_state_revisions",
        "memory_audit_logs",
        "memory_event_outbox",
      ],
      returns: "jsonb",
      effects: [
        { table_name: "memory_write_batches", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_series", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_series", operation: "transition", concurrency_control: "database_row_lock" },
        { table_name: "memory_points", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_points", operation: "transition", concurrency_control: "database_row_lock" },
        { table_name: "memory_conflicts", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_write_item_decisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_point_search_index", operation: "upsert", concurrency_control: "database_row_lock" },
        { table_name: "memory_state_revisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "append_memory_state_revision_v1",
      primary_table: "memory_state_revisions",
      writer_kind: "immutable_append",
      arguments: [["p_state_key", "text"], ["p_expected_revision", "bigint"], ["p_state_revision", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_state_revisions"],
      writes_tables: ["memory_state_revisions", "memory_point_search_index", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_state_revisions", operation: "append", concurrency_control: "expected_version" },
        { table_name: "memory_point_search_index", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "create_memory_integration_job_v1",
      primary_table: "memory_integration_jobs",
      writer_kind: "state_transition",
      arguments: [["p_job_id", "text"], ["p_job", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_integration_jobs"],
      writes_tables: ["memory_integration_jobs", "memory_audit_logs", "memory_event_outbox", "memory_command_outbox"],
      returns: "jsonb",
      effects: [
        { table_name: "memory_integration_jobs", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "memory_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "transition_memory_integration_job_v1",
      primary_table: "memory_integration_jobs",
      writer_kind: "state_transition",
      arguments: [["p_job_id", "text"], ["p_expected_status", "text"], ["p_expected_state_version", "bigint"], ["p_next_status", "text"], ["p_job_result", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_integration_jobs"],
      writes_tables: ["memory_integration_jobs", "memory_audit_logs", "memory_event_outbox", "memory_command_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_integration_jobs", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "memory_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "cas_memory_integration_job_lease_v1",
      primary_table: "memory_integration_job_leases",
      writer_kind: "lease_fence",
      arguments: [["p_job_id", "text"], ["p_expected_job_status", "text"], ["p_expected_job_state_version", "bigint"], ["p_expected_fence_generation", "bigint"], ["p_holder_id", "text"], ["p_lease_until", "timestamptz"], ["p_trace_id", "text"]],
      reads_tables: ["memory_integration_jobs", "memory_integration_job_leases"],
      writes_tables: ["memory_integration_jobs", "memory_integration_job_leases", "memory_audit_logs"], returns: "jsonb",
      effects: [
        { table_name: "memory_integration_jobs", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "memory_integration_job_leases", operation: "cas", concurrency_control: "generation_fence" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "renew_memory_integration_job_lease_v1",
      primary_table: "memory_integration_job_leases",
      writer_kind: "lease_fence",
      arguments: [["p_job_id", "text"], ["p_lease_id", "text"], ["p_expected_fence_generation", "bigint"], ["p_holder_id", "text"], ["p_lease_until", "timestamptz"], ["p_trace_id", "text"]],
      reads_tables: ["memory_integration_jobs", "memory_integration_job_leases"],
      writes_tables: ["memory_integration_job_leases", "memory_audit_logs"],
      returns: "jsonb",
      effects: [
        { table_name: "memory_integration_job_leases", operation: "cas", concurrency_control: "generation_fence" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "apply_memory_integration_change_v1",
      primary_table: "memory_integration_change_receipts",
      writer_kind: "immutable_append",
      arguments: [
        ["p_job_id", "text"],
        ["p_lease_id", "text"],
        ["p_expected_lease_generation", "bigint"],
        ["p_policy_version", "text"],
        ["p_change_id", "text"],
        ["p_change_kind", "text"],
        ["p_target_type", "text"],
        ["p_target_id", "text"],
        ["p_change", "jsonb"],
        ["p_request_hash", "text"],
        ["p_trace_id", "text"],
      ],
      reads_tables: [
        "memory_integration_jobs",
        "memory_integration_job_leases",
        "memory_integration_change_receipts",
        "memory_series",
        "memory_points",
        "memory_point_search_index",
        "memory_promotion_reservations",
        "memory_promotion_reservation_targets",
      ],
      writes_tables: [
        "memory_integration_change_receipts",
        "memory_series",
        "memory_points",
        "memory_point_search_index",
        "memory_state_revisions",
        "topic_key_aliases",
        "topic_family_key_aliases",
        "memory_audit_logs",
        "memory_event_outbox",
      ],
      returns: "jsonb",
      effects: [
        { table_name: "memory_integration_change_receipts", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_series", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "memory_points", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "memory_point_search_index", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "memory_state_revisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "topic_key_aliases", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "topic_family_key_aliases", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        {
          table_name: "memory_integration_change_receipts",
          operation: "append",
          concurrency_control: "promotion_reservation_fence",
          promotion_reservation_targets: [{
            aggregate_type_argument: "p_target_type",
            id_argument: "p_target_id",
          }],
        },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "claim_memory_event_outbox_v1",
      primary_table: "memory_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_worker_id", "text"], ["p_limit", "integer"], ["p_lease_seconds", "integer"], ["p_now", "timestamptz"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"]], reads_tables: ["memory_event_outbox", "eventing_transport_epochs"], writes_tables: ["memory_event_outbox"], returns: "setof jsonb",
      effects: [{ table_name: "memory_event_outbox", operation: "claim", concurrency_control: "lease_fence" }],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "ack_memory_event_outbox_v1",
      primary_table: "memory_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_outbox_id", "text"], ["p_claim_token", "text"], ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"], ["p_error", "jsonb"], ["p_transport_ref", "text"], ["p_transport_epoch", "text"], ["p_transport_generation", "bigint"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"], ["p_now", "timestamptz"]], reads_tables: ["memory_event_outbox", "eventing_transport_epochs"], writes_tables: ["memory_event_outbox", "memory_event_dlq"], returns: "jsonb",
      effects: [
        { table_name: "memory_event_outbox", operation: "ack", concurrency_control: "lease_fence" },
        { table_name: "memory_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "claim_memory_command_outbox_v1",
      primary_table: "memory_command_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_worker_id", "text"], ["p_limit", "integer"], ["p_lease_seconds", "integer"], ["p_now", "timestamptz"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"]], reads_tables: ["memory_command_outbox", "eventing_transport_epochs"], writes_tables: ["memory_command_outbox"], returns: "setof jsonb",
      effects: [{ table_name: "memory_command_outbox", operation: "claim", concurrency_control: "lease_fence" }],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "ack_memory_command_outbox_v1",
      primary_table: "memory_command_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_outbox_id", "text"], ["p_claim_token", "text"], ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"], ["p_error", "jsonb"], ["p_transport_ref", "text"], ["p_transport_epoch", "text"], ["p_transport_generation", "bigint"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"], ["p_now", "timestamptz"]], reads_tables: ["memory_command_outbox", "eventing_transport_epochs"], writes_tables: ["memory_command_outbox", "memory_command_dlq"], returns: "jsonb",
      effects: [
        { table_name: "memory_command_outbox", operation: "ack", concurrency_control: "lease_fence" },
        { table_name: "memory_command_dlq", operation: "append", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerEventingTransportEpochActivationSignatureV1("memory"),
    ],
  // The generator imports this module with a cache-busting `?writer=` URL so
  // it can attest a changed signature before the replacement artifact exists.
  // Runtime imports remain fail-closed on exact artifact drift.
  ...(new URL(import.meta.url).searchParams.has("writer")
    ? {}
    : { writer_artifacts: MEMORY_WRITER_ARTIFACTS_V1 }),
  database_columns: MEMORY_DATABASE_COLUMNS_V1,
  database_checks: MEMORY_DATABASE_CHECKS_V1,
  database_functions: MEMORY_DATABASE_FUNCTIONS_V1,
  database_triggers: MEMORY_DATABASE_TRIGGERS_V1,
  database_unique_constraints: MEMORY_DATABASE_UNIQUE_CONSTRAINTS_V1,
  database_indexes: MEMORY_DATABASE_INDEXES_V1,
  foreign_key_snapshot: {
    status: "complete",
    source: "Database Design revision 508 / fresh 0600_memory and 0610_memory_vector canonical DDL contract snapshot; version-pinned pai-infra artifacts are required before PostgreSQL deployment verification",
  },
  foreign_keys: MEMORY_FOREIGN_KEYS_V1,
  append_only_tables: [
    "memory_event_outbox",
    "memory_event_inbox",
    "memory_event_dlq",
    MEMORY_EVENT_DLQ_RESOLUTION_V1.resolution_table,
    "memory_write_item_decisions",
    "memory_state_revisions",
    "memory_feedback_events",
    "memory_audit_logs",
    "memory_feedback_revision_refs",
    "memory_feedback_audit_refs",
    "memory_feedback_event_refs",
    "memory_promotion_reservation_targets",
    "memory_graph_builds",
    "memory_integration_change_receipts",
    "memory_command_outbox",
    "memory_command_dlq",
    MEMORY_COMMAND_DLQ_RESOLUTION_V1.resolution_table,
    "topic_key_aliases",
    "topic_family_key_aliases",
    "memory_embedding_profiles",
  ],
  outbox_tables: ["memory_event_outbox", "memory_command_outbox"],
  inbox_tables: ["memory_event_inbox"],
  dlq_tables: ["memory_event_dlq", "memory_command_dlq"],
  dlq_resolutions: [
    MEMORY_EVENT_DLQ_RESOLUTION_V1.binding,
    MEMORY_COMMAND_DLQ_RESOLUTION_V1.binding,
  ],
  object_metadata_tables: [],
} as const);

export interface MemoryRepositoryPortV1
  extends OwnerRepositoryPortV1<typeof MEMORY_REPOSITORY_CONTRACT_V1> {}

export type MemoryUnitOfWorkPortV1 = OwnerUnitOfWorkPortV1<
  "memory",
  Readonly<{ owner: MemoryRepositoryPortV1 }>
>;
