import { OWNER_DURABLE_EVENT_TYPES_V1 } from "@pai/contracts";
import {
  defineOwnerRepositoryContractV1,
  ownerForeignKeysV1,
  ownerFunctionSignatureV1,
  type OwnerRepositoryPortV1,
  type OwnerUnitOfWorkPortV1,
} from "@pai/persistence";

export const MEMORY_REPOSITORY_CONTRACT_V1 = defineOwnerRepositoryContractV1({
  contract_version: "owner_repository_contract.v1",
  owner_service: "memory",
  schema: "memory",
  app_role: "pai_memory_app",
  fresh_migrations: ["0600_memory", "0610_memory_vector"],
  manifest_source: "services/memory/src/db/permission-manifest.v1.ts",
  generated_permission_sql: [
    "pai-infra/supabase/generated/permissions/0600_memory.sql",
    "pai-infra/supabase/generated/permissions/0610_memory_vector.sql",
  ],
  tables: [
    "memory_series",
    "memory_write_batches",
    "memory_points",
    "role_memories",
    "relationship_edges",
    "memory_conflicts",
    "memory_linkage_operations",
    "memory_event_outbox",
    "memory_event_inbox",
    "memory_event_dlq",
    "memory_write_item_decisions",
    "memory_point_search_index",
    "memory_state_revisions",
    "memory_feedback_events",
    "memory_audit_logs",
    "memory_feedback_revision_refs",
    "memory_feedback_audit_refs",
    "memory_feedback_event_refs",
    "memory_pre_promotion_checks",
    "memory_promotion_reservations",
    "memory_promotion_reservation_targets",
    "memory_graph_builds",
    "memory_integration_jobs",
    "memory_integration_job_leases",
    "memory_command_outbox",
    "memory_command_dlq",
    "topic_key_aliases",
    "topic_family_key_aliases",
    "memory_embedding_profiles",
  ],
    table_permissions: [
    {
      table_name: "memory_series",
      select_columns: ["id","bot_id","topic_key","topic_family_key","subject_key","aspect_key","scope_key","merged_into_series_id","title","status","state_version","canonicalization_version","topic_components_raw","topic_components_normalized","importance_score","last_recalled_at","last_mentioned_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "memory_write_batches",
      select_columns: ["id","bot_id","trigger_process_id","source_meta_job_id","idempotency_key","request_hash","trace_id","request_payload","response_payload","status","payload_schema_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "memory_points",
      select_columns: ["id","bot_id","series_id","content_summary","human_agent_relation","keyword_tags","scene_tags","emotion_tags","source_info","source_trigger_process_id","content_hash","series_decision","decision_reason","previous_memory_point_id","confidence_score","occurred_at","status","payload_schema_version","state_version","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "role_memories",
      select_columns: ["id","bot_id","role_id","role_type","display_name","attributes","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "relationship_edges",
      select_columns: ["id","bot_id","subject_role_id","object_role_id","relation_type","confidence","evidence_memory_point_ids","valid_from","valid_until","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "memory_conflicts",
      select_columns: ["id","bot_id","series_id","conflict_type","conflict_key","left_memory_point_id","right_memory_point_id","confidence_delta","evidence_refs","conflict_payload","proposed_resolution","status","state_version","resolution","payload_schema_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_linkage_operations",
      select_columns: ["id","bot_id","source_kind","source_service","actor_principal","actor_role","source_ref","source_fact_id","source_linkage_check_id","source_memory_point_id","affected_query","linked_memory_point_ids","relationship_edge_changes","operation","historical_payload","idempotency_key","next_retry_at","locked_by","locked_until","last_error","reason","evidence_refs","status","payload_schema_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "memory_event_outbox",
      select_columns: ["id","event_type","schema_version","producer","bot_id","aggregate_id","aggregate_type","aggregate_version","occurred_at","idempotency_key","trace_id","target","payload","payload_hash","status","next_retry_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "memory_event_inbox",
      select_columns: ["id","source","event_id","scope_fingerprint","idempotency_key","payload_hash","semantic_hash","processed_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_event_dlq",
      select_columns: ["id","source_event_id","event_type","payload","last_error","failed_at","resolved_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_write_item_decisions",
      select_columns: ["id","bot_id","batch_id","client_item_id","source_item_id","source_trigger_process_id","content_hash","decision","target_series_id","target_memory_point_id","conflict_id","candidate_refs","decision_reason","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_point_search_index",
      select_columns: ["memory_point_id","bot_id","series_id","topic_family_key","topic_key","status","state_version","series_state_version","source_revision_ids","ranking_profile_version","content_summary","keyword_tags","scene_tags","emotion_tags","occurred_at","importance_score","last_mentioned_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "memory_state_revisions",
      select_columns: ["id","bot_id","aggregate_type","aggregate_id","previous_state_version","resulting_state_version","operation","before_payload","after_payload","actor_ref","reason","evidence_refs","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "pointer_cas",
    },
    {
      table_name: "memory_feedback_events",
      select_columns: ["id","bot_id","target_type","target_id","action","expected_state_version","resulting_state_version","idempotency_key","request_hash","request_payload","response_payload","authenticated_actor_ref","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_audit_logs",
      select_columns: ["id","bot_id","revision_id","feedback_event_id","target_type","target_id","actor_ref","action","reason_code","capability_snapshot","payload","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_feedback_revision_refs",
      select_columns: ["feedback_event_id","revision_id"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_feedback_audit_refs",
      select_columns: ["feedback_event_id","audit_id"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_feedback_event_refs",
      select_columns: ["feedback_event_id","event_id"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_pre_promotion_checks",
      select_columns: ["id","bot_id","candidate_fact_id","idempotency_key","request_hash","required_checks","point_state_snapshot","overall_result","blocking_reasons","check_policy_version","check_token_hash","checked_at","expires_at","response_payload"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_promotion_reservations",
      select_columns: ["id","check_id","bot_id","candidate_fact_id","idempotency_key","request_hash","fencing_generation","reservation_token_hash","status","expires_at","committed_at","promotion_revision_id","ack_payload","release_reason","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "memory_promotion_reservation_targets",
      select_columns: ["reservation_id","aggregate_type","aggregate_id","expected_state_version","expected_state_hash"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "memory_graph_builds",
      select_columns: ["id","bot_id","idempotency_key","request_hash","graph_profile_version","graph_revision","response_payload","expires_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "memory_integration_jobs",
      select_columns: ["id","bot_id","mode","scope","dry_run","idempotency_key","request_hash","expected_policy_version","state_version","status","checkpoint_ref","result_payload","error","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "memory_integration_job_leases",
      select_columns: ["integration_job_id","lease_id","lease_generation","owner_id","lease_expires_at","heartbeat_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "lease_fence",
    },
    {
      table_name: "memory_command_outbox",
      select_columns: ["id","command_id","contract_name","source_service","source_ref","workspace_id","bot_id","owner_agent_id","deployment_environment","release_channel","dedupe_scope_ref","request_payload","request_hash","trace_id","status","next_retry_at","last_error","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "memory_command_dlq",
      select_columns: ["id","command_outbox_id","payload","payload_hash","last_error","failed_at","resolved_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "topic_key_aliases",
      select_columns: ["id","bot_id","old_canonicalization_version","old_topic_key","new_canonicalization_version","new_topic_key","actor_ref","reason","evidence_refs","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "topic_family_key_aliases",
      select_columns: ["id","bot_id","old_canonicalization_version","old_topic_family_key","new_canonicalization_version","new_topic_family_key","actor_ref","reason","evidence_refs","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "memory_embedding_profiles",
      select_columns: ["id","model_id","model_revision","normalized","distance_metric","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    ],
  mutable_writers: [
    "transition_memory_series_v1",
    "append_memory_point_v1",
    "upsert_memory_relationship_projection_v1",
    "transition_memory_linkage_operation_v1",
    "append_memory_feedback_v1",
    "transition_memory_promotion_v1",
    "upsert_memory_graph_build_v1",
    "upsert_memory_canonicalization_aliases_v1",
    "finalize_memory_write_batch_v1",
    "cas_memory_state_revision_v1",
    "transition_memory_integration_job_v1",
    "cas_memory_integration_job_lease_v1",
    "claim_memory_event_outbox_v1",
    "ack_memory_event_outbox_v1",
    "claim_memory_command_outbox_v1",
    "ack_memory_command_outbox_v1",
  ],
    function_signatures: [
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "transition_memory_series_v1",
      primary_table: "memory_series",
      writer_kind: "state_transition",
      arguments: [["p_series_id", "text"], ["p_expected_status", "text"], ["p_expected_state_version", "bigint"], ["p_next_status", "text"], ["p_series_change", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_series"],
      writes_tables: ["memory_series", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_series", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "append_memory_point_v1",
      primary_table: "memory_points",
      writer_kind: "immutable_append",
      arguments: [["p_point_id", "text"], ["p_series_id", "text"], ["p_expected_series_version", "bigint"], ["p_point", "jsonb"], ["p_item_decision", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_series", "memory_embedding_profiles"],
      writes_tables: ["memory_points", "memory_write_item_decisions", "memory_point_search_index", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_points", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_write_item_decisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_point_search_index", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "upsert_memory_relationship_projection_v1",
      primary_table: "role_memories",
      writer_kind: "projection_upsert",
      arguments: [["p_projection_key", "text"], ["p_expected_version", "bigint"], ["p_projection", "jsonb"], ["p_conflict", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["role_memories", "relationship_edges"],
      writes_tables: ["role_memories", "relationship_edges", "memory_conflicts", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "role_memories", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "relationship_edges", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "memory_conflicts", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "transition_memory_linkage_operation_v1",
      primary_table: "memory_linkage_operations",
      writer_kind: "state_transition",
      arguments: [["p_operation_id", "text"], ["p_expected_status", "text"], ["p_next_status", "text"], ["p_operation", "jsonb"], ["p_source_event", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_linkage_operations", "memory_event_inbox"],
      writes_tables: ["memory_linkage_operations", "memory_event_inbox", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_linkage_operations", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "memory_event_inbox", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "append_memory_feedback_v1",
      primary_table: "memory_feedback_events",
      writer_kind: "immutable_append",
      arguments: [["p_feedback_id", "text"], ["p_memory_point_id", "text"], ["p_feedback", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_points", "memory_state_revisions"],
      writes_tables: ["memory_feedback_events", "memory_feedback_revision_refs", "memory_feedback_audit_refs", "memory_feedback_event_refs", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_feedback_events", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_feedback_revision_refs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_feedback_audit_refs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_feedback_event_refs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "transition_memory_promotion_v1",
      primary_table: "memory_promotion_reservations",
      writer_kind: "state_transition",
      arguments: [["p_reservation_id", "text"], ["p_expected_status", "text"], ["p_next_status", "text"], ["p_expected_fence", "bigint"], ["p_promotion", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_pre_promotion_checks", "memory_promotion_reservations"],
      writes_tables: ["memory_pre_promotion_checks", "memory_promotion_reservations", "memory_promotion_reservation_targets", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_pre_promotion_checks", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_promotion_reservations", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "memory_promotion_reservation_targets", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "upsert_memory_graph_build_v1",
      primary_table: "memory_graph_builds",
      writer_kind: "projection_upsert",
      arguments: [["p_build_id", "text"], ["p_expected_status", "text"], ["p_next_status", "text"], ["p_build_result", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_graph_builds"],
      writes_tables: ["memory_graph_builds", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_graph_builds", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "upsert_memory_canonicalization_aliases_v1",
      primary_table: "topic_key_aliases",
      writer_kind: "projection_upsert",
      arguments: [["p_expected_canonicalization_version", "bigint"], ["p_aliases", "jsonb"], ["p_embedding_profile", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["topic_key_aliases", "topic_family_key_aliases", "memory_embedding_profiles"],
      writes_tables: ["topic_key_aliases", "topic_family_key_aliases", "memory_embedding_profiles", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "topic_key_aliases", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "topic_family_key_aliases", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "memory_embedding_profiles", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "finalize_memory_write_batch_v1",
      primary_table: "memory_write_batches",
      writer_kind: "state_transition",
      arguments: [["p_batch_id", "text"], ["p_expected_status", "text"], ["p_next_status", "text"], ["p_batch_result", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_write_batches", "memory_write_item_decisions"],
      writes_tables: ["memory_write_batches", "memory_write_item_decisions", "memory_points", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_write_batches", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "memory_write_item_decisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_points", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "cas_memory_state_revision_v1",
      primary_table: "memory_state_revisions",
      writer_kind: "pointer_cas",
      arguments: [["p_state_key", "text"], ["p_expected_revision", "bigint"], ["p_state_revision", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_state_revisions"],
      writes_tables: ["memory_state_revisions", "memory_point_search_index", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_state_revisions", operation: "cas", concurrency_control: "expected_version" },
        { table_name: "memory_point_search_index", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "transition_memory_integration_job_v1",
      primary_table: "memory_integration_jobs",
      writer_kind: "state_transition",
      arguments: [["p_job_id", "text"], ["p_expected_status", "text"], ["p_next_status", "text"], ["p_job_result", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["memory_integration_jobs"],
      writes_tables: ["memory_integration_jobs", "memory_audit_logs", "memory_event_outbox", "memory_command_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_integration_jobs", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "memory_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "cas_memory_integration_job_lease_v1",
      primary_table: "memory_integration_job_leases",
      writer_kind: "lease_fence",
      arguments: [["p_job_id", "text"], ["p_expected_fence_generation", "bigint"], ["p_holder_id", "text"], ["p_lease_until", "timestamptz"], ["p_trace_id", "text"]],
      reads_tables: ["memory_integration_job_leases"],
      writes_tables: ["memory_integration_job_leases", "memory_audit_logs", "memory_event_outbox"], returns: "jsonb",
      effects: [
        { table_name: "memory_integration_job_leases", operation: "cas", concurrency_control: "generation_fence" },
        { table_name: "memory_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "memory_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "claim_memory_event_outbox_v1",
      primary_table: "memory_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_worker_id", "text"], ["p_limit", "integer"], ["p_lease_seconds", "integer"], ["p_now", "timestamptz"]], reads_tables: ["memory_event_outbox"], writes_tables: ["memory_event_outbox"], returns: "setof jsonb",
      effects: [{ table_name: "memory_event_outbox", operation: "claim", concurrency_control: "lease_fence" }],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "ack_memory_event_outbox_v1",
      primary_table: "memory_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_outbox_id", "text"], ["p_claim_token", "text"], ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"], ["p_error", "jsonb"], ["p_transport_ref", "text"], ["p_transport_epoch", "text"], ["p_now", "timestamptz"]], reads_tables: ["memory_event_outbox"], writes_tables: ["memory_event_outbox", "memory_event_dlq"], returns: "jsonb",
      effects: [
        { table_name: "memory_event_outbox", operation: "ack", concurrency_control: "lease_fence" },
        { table_name: "memory_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
      ],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "claim_memory_command_outbox_v1",
      primary_table: "memory_command_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_worker_id", "text"], ["p_limit", "integer"], ["p_lease_seconds", "integer"], ["p_now", "timestamptz"]], reads_tables: ["memory_command_outbox"], writes_tables: ["memory_command_outbox"], returns: "setof jsonb",
      effects: [{ table_name: "memory_command_outbox", operation: "claim", concurrency_control: "lease_fence" }],
    }),
    ownerFunctionSignatureV1({
      schema: "memory",
      function_name: "ack_memory_command_outbox_v1",
      primary_table: "memory_command_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_outbox_id", "text"], ["p_claim_token", "text"], ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"], ["p_error", "jsonb"], ["p_transport_ref", "text"], ["p_transport_epoch", "text"], ["p_now", "timestamptz"]], reads_tables: ["memory_command_outbox"], writes_tables: ["memory_command_outbox", "memory_command_dlq"], returns: "jsonb",
      effects: [
        { table_name: "memory_command_outbox", operation: "ack", concurrency_control: "lease_fence" },
        { table_name: "memory_command_dlq", operation: "append", concurrency_control: "idempotency_key" },
      ],
    }),
    ],
  database_checks: [
    {
      constraint_name: "memory_event_outbox_event_type_check",
      table_name: "memory_event_outbox",
      required_definition_fragments: ["event_type", "memory.integration.finished"],
      semantic_constraint: {
        kind: "text_enum",
        column_name: "event_type",
        allowed_values: OWNER_DURABLE_EVENT_TYPES_V1.memory,
      },
    },
    {
      constraint_name: "memory_event_outbox_producer_check",
      table_name: "memory_event_outbox",
      required_definition_fragments: ["producer", "memory"],
      semantic_constraint: {
        kind: "text_equals",
        column_name: "producer",
        value: "memory",
      },
    },
  ],
  foreign_key_snapshot: {
    status: "complete",
    source: "Database Design revision 466 / fresh 0600_memory and 0610_memory_vector canonical DDL applied to PostgreSQL 17",
  },
  foreign_keys: ownerForeignKeysV1("memory", [
    ["memory_audit_logs_feedback_event_id_fkey","memory_audit_logs",["feedback_event_id"],"memory_feedback_events",["id"]],
    ["memory_audit_logs_revision_id_fkey","memory_audit_logs",["revision_id"],"memory_state_revisions",["id"]],
    ["memory_command_dlq_command_outbox_id_fkey","memory_command_dlq",["command_outbox_id"],"memory_command_outbox",["id"]],
    ["memory_conflicts_left_memory_point_id_fkey","memory_conflicts",["left_memory_point_id"],"memory_points",["id"]],
    ["memory_conflicts_right_memory_point_id_fkey","memory_conflicts",["right_memory_point_id"],"memory_points",["id"]],
    ["memory_conflicts_series_id_fkey","memory_conflicts",["series_id"],"memory_series",["id"]],
    ["memory_feedback_audit_refs_audit_id_fkey","memory_feedback_audit_refs",["audit_id"],"memory_audit_logs",["id"]],
    ["memory_feedback_audit_refs_feedback_event_id_fkey","memory_feedback_audit_refs",["feedback_event_id"],"memory_feedback_events",["id"],{ on_delete: "cascade" }],
    ["memory_feedback_event_refs_event_id_fkey","memory_feedback_event_refs",["event_id"],"memory_event_outbox",["id"]],
    ["memory_feedback_event_refs_feedback_event_id_fkey","memory_feedback_event_refs",["feedback_event_id"],"memory_feedback_events",["id"],{ on_delete: "cascade" }],
    ["memory_feedback_revision_refs_feedback_event_id_fkey","memory_feedback_revision_refs",["feedback_event_id"],"memory_feedback_events",["id"],{ on_delete: "cascade" }],
    ["memory_feedback_revision_refs_revision_id_fkey","memory_feedback_revision_refs",["revision_id"],"memory_state_revisions",["id"]],
    ["memory_integration_job_leases_integration_job_id_fkey","memory_integration_job_leases",["integration_job_id"],"memory_integration_jobs",["id"]],
    ["memory_linkage_operations_source_memory_point_id_fkey","memory_linkage_operations",["source_memory_point_id"],"memory_points",["id"]],
    ["memory_point_search_index_memory_point_id_fkey","memory_point_search_index",["memory_point_id"],"memory_points",["id"],{ on_delete: "cascade" }],
    ["memory_point_search_index_series_id_fkey","memory_point_search_index",["series_id"],"memory_series",["id"]],
    ["memory_points_series_id_fkey","memory_points",["series_id"],"memory_series",["id"]],
    ["memory_promotion_reservation_targets_reservation_id_fkey","memory_promotion_reservation_targets",["reservation_id"],"memory_promotion_reservations",["id"],{ on_delete: "cascade" }],
    ["memory_promotion_reservations_check_id_fkey","memory_promotion_reservations",["check_id"],"memory_pre_promotion_checks",["id"]],
    ["memory_write_item_decisions_batch_id_fkey","memory_write_item_decisions",["batch_id"],"memory_write_batches",["id"]],
    ["memory_write_item_decisions_conflict_id_fkey","memory_write_item_decisions",["conflict_id"],"memory_conflicts",["id"]],
    ["memory_write_item_decisions_target_memory_point_id_fkey","memory_write_item_decisions",["target_memory_point_id"],"memory_points",["id"]],
    ["memory_write_item_decisions_target_series_id_fkey","memory_write_item_decisions",["target_series_id"],"memory_series",["id"]],
    ["relationship_edges_object_role_id_fkey","relationship_edges",["object_role_id"],"role_memories",["id"]],
    ["relationship_edges_subject_role_id_fkey","relationship_edges",["subject_role_id"],"role_memories",["id"]],
  ]),
  append_only_tables: [
    "memory_points",
    "memory_conflicts",
    "memory_event_outbox",
    "memory_event_inbox",
    "memory_event_dlq",
    "memory_write_item_decisions",
    "memory_feedback_events",
    "memory_audit_logs",
    "memory_feedback_revision_refs",
    "memory_feedback_audit_refs",
    "memory_feedback_event_refs",
    "memory_pre_promotion_checks",
    "memory_promotion_reservation_targets",
    "memory_command_outbox",
    "memory_command_dlq",
  ],
  outbox_tables: ["memory_event_outbox", "memory_command_outbox"],
  inbox_tables: ["memory_event_inbox"],
  dlq_tables: ["memory_event_dlq", "memory_command_dlq"],
  object_metadata_tables: [],
} as const);

export interface MemoryRepositoryPortV1
  extends OwnerRepositoryPortV1<typeof MEMORY_REPOSITORY_CONTRACT_V1> {}

export type MemoryUnitOfWorkPortV1 = OwnerUnitOfWorkPortV1<
  "memory",
  Readonly<{ owner: MemoryRepositoryPortV1 }>
>;
