import { OWNER_DURABLE_EVENT_TYPES_V1 } from "@pai/contracts";
import {
  defineOwnerRepositoryContractV1,
  ownerEventingTransportEpochActivationSignatureV1,
  ownerEventingTransportEpochTablePermissionV1,
  ownerForeignKeysV1,
  ownerFunctionSignatureV1,
  type OwnerRepositoryPortV1,
  type OwnerUnitOfWorkPortV1,
} from "@pai/persistence";

export const KNOWTHAT_REPOSITORY_CONTRACT_V1 =
  defineOwnerRepositoryContractV1({
    contract_version: "owner_repository_contract.v1",
    owner_service: "knowthat",
    schema: "knowthat",
    app_role: "pai_knowthat_app",
    fresh_migrations: ["0500_knowthat"],
    manifest_source: "services/knowthat/src/db/permission-manifest.v1.ts",
    generated_permission_sql: [
      "pai-infra/supabase/generated/permissions/0500_knowthat.sql",
    ],
    tables: [
      "knowthat_facts",
      "knowthat_write_batches",
      "knowthat_fact_revisions",
      "knowthat_candidate_reviews",
      "knowthat_conflicts",
      "knowthat_linkage_checks",
      "knowthat_feedback_events",
      "knowthat_event_outbox",
      "knowthat_event_inbox",
      "knowthat_event_dlq",
      "knowthat_query_revisions",
      "knowthat_fact_query_versions",
      "semantic_key_aliases",
      "semantic_key_synonyms",
      "knowthat_memory_command_outbox",
      "eventing_transport_epochs",
    ],
    table_permissions: [
    {
      table_name: "knowthat_facts",
      select_columns: ["id","bot_id","text","subject","predicate","object","normalized_object","object_hash","canonicalization_version","semantic_key_display","semantic_components_raw","semantic_components_normalized","semantic_key","category","status","confidence","source","source_ref","evidence_refs","valid_from","valid_until","payload_schema_version","state_version","candidate_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "knowthat_write_batches",
      select_columns: ["id","bot_id","trigger_process_id","source_meta_job_id","idempotency_key","request_hash","trace_id","request_payload","response_payload","status","payload_schema_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "knowthat_fact_revisions",
      select_columns: ["id","fact_id","revision_no","patch","reason","actor","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "knowthat_candidate_reviews",
      select_columns: ["id","fact_id","target_candidate_version","decision","reason","evidence_refs","evidence_set_hash","source_meta_job_id","suggestion_id","suggested_action","idempotency_key","request_hash","outcome","reason_code","response_payload","reviewed_by","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "knowthat_conflicts",
      select_columns: ["id","bot_id","conflict_key","semantic_key","left_fact_id","right_fact_id","conflict_type","field_path","source_priority_snapshot","confidence_delta","evidence_refs","proposed_resolution","status","resolution","payload_schema_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "knowthat_linkage_checks",
      select_columns: ["id","bot_id","fact_id","check_type","target_service","change_type","affected_query","target_memory_point_ids","action","reason","evidence_refs","idempotency_key","attempt_count","next_retry_at","locked_by","locked_until","last_error","status","result","payload_schema_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "knowthat_feedback_events",
      select_columns: ["id","bot_id","fact_id","feedback_type","payload","evidence_ref","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "knowthat_event_outbox",
      select_columns: ["id","bot_id","aggregate_id","event_type","schema_version","producer","occurred_at","idempotency_key","trace_id","payload","payload_hash","target","status","attempt_count","next_retry_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "knowthat_event_inbox",
      select_columns: ["id","source","event_id","scope_fingerprint","idempotency_key","payload_hash","semantic_hash","processed_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "knowthat_event_dlq",
      select_columns: ["id","source_event_id","event_type","payload","last_error","failed_at","resolved_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "knowthat_query_revisions",
      select_columns: ["bot_id","current_revision","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "pointer_cas",
    },
    {
      table_name: "knowthat_fact_query_versions",
      select_columns: ["bot_id","fact_id","visible_from_revision","visible_until_revision","status","category","semantic_key","updated_at","valid_from","valid_until","projection_payload","search_vector","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "semantic_key_aliases",
      select_columns: ["id","bot_id","old_canonicalization_version","old_semantic_key","new_canonicalization_version","new_semantic_key","target_fact_id","actor_ref","reason","evidence_refs","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "semantic_key_synonyms",
      select_columns: ["segment","synonym","canonical"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "knowthat_memory_command_outbox",
      select_columns: ["id","command_type","reservation_id","candidate_fact_id","fencing_generation","reservation_token_hash","promotion_revision_id","committed_at","idempotency_key","request_hash","payload","status","next_retry_at","last_error","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    ownerEventingTransportEpochTablePermissionV1(),
    ],
    mutable_writers: [
      "create_knowthat_fact_v1",
      "transition_knowthat_fact_v1",
      "append_knowthat_conflict_v1",
      "append_knowthat_candidate_review_v1",
      "transition_knowthat_conflict_v1",
      "enqueue_knowthat_linkage_check_v1",
      "transition_knowthat_linkage_check_v1",
      "append_knowthat_feedback_v1",
      "create_knowthat_write_batch_v1",
      "finalize_knowthat_write_batch_v1",
      "cas_knowthat_query_revision_v1",
      "claim_knowthat_event_outbox_v1",
      "ack_knowthat_event_outbox_v1",
      "claim_knowthat_memory_command_outbox_v1",
      "ack_knowthat_memory_command_outbox_v1",
      "activate_eventing_transport_epoch_v1",
    ],
    function_signatures: [
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "create_knowthat_fact_v1",
      primary_table: "knowthat_facts",
      writer_kind: "state_transition",
      arguments: [["p_fact_id", "text"], ["p_fact", "jsonb"], ["p_initial_revision", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_facts"],
      writes_tables: ["knowthat_facts", "knowthat_fact_revisions", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_facts", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_fact_revisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "transition_knowthat_fact_v1",
      primary_table: "knowthat_facts",
      writer_kind: "state_transition",
      arguments: [["p_fact_id", "text"], ["p_expected_status", "text"], ["p_expected_state_version", "bigint"], ["p_expected_updated_at", "timestamptz"], ["p_next_status", "text"], ["p_fact_revision", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_facts", "knowthat_fact_revisions"],
      writes_tables: ["knowthat_facts", "knowthat_fact_revisions", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_facts", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "knowthat_fact_revisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "append_knowthat_conflict_v1",
      primary_table: "knowthat_conflicts",
      writer_kind: "state_transition",
      arguments: [["p_conflict_id", "text"], ["p_fact_id", "text"], ["p_conflict", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_facts", "knowthat_conflicts"],
      writes_tables: ["knowthat_conflicts", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_conflicts", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "append_knowthat_candidate_review_v1",
      primary_table: "knowthat_candidate_reviews",
      writer_kind: "immutable_append",
      arguments: [["p_review_id", "text"], ["p_fact_id", "text"], ["p_source_meta_job_id", "text"], ["p_suggestion_id", "text"], ["p_expected_candidate_version", "integer"], ["p_suggested_action", "text"], ["p_review", "jsonb"], ["p_source_event", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_payload_hash", "text"], ["p_semantic_hash", "text"], ["p_scope_fingerprint", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_facts", "knowthat_candidate_reviews", "knowthat_event_inbox"],
      writes_tables: ["knowthat_candidate_reviews", "knowthat_event_inbox", "knowthat_event_dlq", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_candidate_reviews", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_inbox", operation: "append", concurrency_control: "durable_event_identity" },
        { table_name: "knowthat_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "transition_knowthat_conflict_v1",
      primary_table: "knowthat_conflicts",
      writer_kind: "state_transition",
      arguments: [["p_conflict_id", "text"], ["p_expected_status", "text"], ["p_expected_updated_at", "timestamptz"], ["p_next_status", "text"], ["p_resolution", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_conflicts", "knowthat_facts"],
      writes_tables: ["knowthat_conflicts", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_conflicts", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "enqueue_knowthat_linkage_check_v1",
      primary_table: "knowthat_linkage_checks",
      writer_kind: "state_transition",
      arguments: [["p_linkage_check_id", "text"], ["p_fact_id", "text"], ["p_linkage_check", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_facts", "knowthat_linkage_checks"],
      writes_tables: ["knowthat_linkage_checks", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_linkage_checks", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "transition_knowthat_linkage_check_v1",
      primary_table: "knowthat_linkage_checks",
      writer_kind: "state_transition",
      arguments: [["p_linkage_check_id", "text"], ["p_expected_status", "text"], ["p_expected_updated_at", "timestamptz"], ["p_claim_token", "text"], ["p_next_status", "text"], ["p_result", "jsonb"], ["p_memory_command", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_linkage_checks", "knowthat_facts"],
      writes_tables: ["knowthat_linkage_checks", "knowthat_memory_command_outbox", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_linkage_checks", operation: "transition", concurrency_control: "lease_fence" },
        { table_name: "knowthat_memory_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "append_knowthat_feedback_v1",
      primary_table: "knowthat_feedback_events",
      writer_kind: "immutable_append",
      arguments: [["p_feedback_event_id", "text"], ["p_fact_id", "text"], ["p_feedback", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_facts"],
      writes_tables: ["knowthat_feedback_events", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_feedback_events", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "create_knowthat_write_batch_v1",
      primary_table: "knowthat_write_batches",
      writer_kind: "state_transition",
      arguments: [["p_batch_id", "text"], ["p_batch", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_write_batches"],
      writes_tables: ["knowthat_write_batches", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_write_batches", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "finalize_knowthat_write_batch_v1",
      primary_table: "knowthat_write_batches",
      writer_kind: "state_transition",
      arguments: [["p_batch_id", "text"], ["p_expected_status", "text"], ["p_next_status", "text"], ["p_batch_result", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_write_batches", "knowthat_facts"],
      writes_tables: ["knowthat_write_batches", "knowthat_event_outbox", "knowthat_memory_command_outbox"],
      effects: [
        { table_name: "knowthat_write_batches", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_memory_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "cas_knowthat_query_revision_v1",
      primary_table: "knowthat_query_revisions",
      writer_kind: "pointer_cas",
      arguments: [["p_query_key", "text"], ["p_expected_revision", "bigint"], ["p_query_revision", "jsonb"], ["p_aliases", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_query_revisions", "knowthat_fact_query_versions"],
      writes_tables: ["knowthat_query_revisions", "knowthat_fact_query_versions", "semantic_key_aliases", "semantic_key_synonyms", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_query_revisions", operation: "cas", concurrency_control: "expected_version" },
        { table_name: "knowthat_fact_query_versions", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "semantic_key_aliases", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "semantic_key_synonyms", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "claim_knowthat_event_outbox_v1",
      primary_table: "knowthat_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_worker_id", "text"], ["p_limit", "integer"], ["p_lease_seconds", "integer"], ["p_now", "timestamptz"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"]], reads_tables: ["knowthat_event_outbox", "eventing_transport_epochs"], writes_tables: ["knowthat_event_outbox"],
      effects: [{ table_name: "knowthat_event_outbox", operation: "claim", concurrency_control: "lease_fence" }],
      returns: "setof jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "ack_knowthat_event_outbox_v1",
      primary_table: "knowthat_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_outbox_id", "text"], ["p_claim_token", "text"], ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"], ["p_error", "jsonb"], ["p_transport_ref", "text"], ["p_transport_epoch", "text"], ["p_transport_generation", "bigint"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"], ["p_now", "timestamptz"]], reads_tables: ["knowthat_event_outbox", "eventing_transport_epochs"], writes_tables: ["knowthat_event_outbox", "knowthat_event_dlq"],
      effects: [
        { table_name: "knowthat_event_outbox", operation: "ack", concurrency_control: "lease_fence" },
        { table_name: "knowthat_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "claim_knowthat_memory_command_outbox_v1",
      primary_table: "knowthat_memory_command_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_worker_id", "text"], ["p_limit", "integer"], ["p_lease_seconds", "integer"], ["p_now", "timestamptz"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"]], reads_tables: ["knowthat_memory_command_outbox", "eventing_transport_epochs"], writes_tables: ["knowthat_memory_command_outbox"],
      effects: [{ table_name: "knowthat_memory_command_outbox", operation: "claim", concurrency_control: "lease_fence" }],
      returns: "setof jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "ack_knowthat_memory_command_outbox_v1",
      primary_table: "knowthat_memory_command_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_outbox_id", "text"], ["p_claim_token", "text"], ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"], ["p_error", "jsonb"], ["p_transport_ref", "text"], ["p_transport_epoch", "text"], ["p_transport_generation", "bigint"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"], ["p_now", "timestamptz"]], reads_tables: ["knowthat_memory_command_outbox", "eventing_transport_epochs"], writes_tables: ["knowthat_memory_command_outbox"],
      effects: [{ table_name: "knowthat_memory_command_outbox", operation: "ack", concurrency_control: "lease_fence" }],
      returns: "jsonb",
    }),
    ownerEventingTransportEpochActivationSignatureV1("knowthat"),
    ],
    database_checks: [
      {
        constraint_name: "eventing_transport_epochs_active_generation_safe_check",
        table_name: "eventing_transport_epochs",
        required_definition_fragments: [
          "active_generation >= 1",
          "9007199254740991",
        ],
        semantic_constraint: {
          kind: "integer_range",
          column_name: "active_generation",
          min: 1,
          max: Number.MAX_SAFE_INTEGER,
        },
      },
      {
        constraint_name: "knowthat_event_outbox_event_type_check",
        table_name: "knowthat_event_outbox",
        required_definition_fragments: ["event_type", "knowthat.linkage_check.requested"],
        semantic_constraint: {
          kind: "text_enum",
          column_name: "event_type",
          allowed_values: OWNER_DURABLE_EVENT_TYPES_V1.knowthat,
        },
      },
      {
        constraint_name: "knowthat_event_outbox_producer_check",
        table_name: "knowthat_event_outbox",
        required_definition_fragments: ["producer", "knowthat"],
        semantic_constraint: {
          kind: "text_equals",
          column_name: "producer",
          value: "knowthat",
        },
      },
    ],
    foreign_key_snapshot: {
      status: "complete",
      source: "Database Design revision 476 / fresh 0500_knowthat canonical DDL applied to PostgreSQL 17",
    },
  foreign_keys: ownerForeignKeysV1("knowthat", [
      ["knowthat_candidate_reviews_fact_id_fkey","knowthat_candidate_reviews",["fact_id"],"knowthat_facts",["id"]],
      ["knowthat_conflicts_left_fact_id_fkey","knowthat_conflicts",["left_fact_id"],"knowthat_facts",["id"]],
      ["knowthat_conflicts_right_fact_id_fkey","knowthat_conflicts",["right_fact_id"],"knowthat_facts",["id"]],
      ["knowthat_fact_query_versions_fact_id_fkey","knowthat_fact_query_versions",["fact_id"],"knowthat_facts",["id"]],
      ["knowthat_fact_revisions_fact_id_fkey","knowthat_fact_revisions",["fact_id"],"knowthat_facts",["id"]],
      ["knowthat_feedback_events_fact_id_fkey","knowthat_feedback_events",["fact_id"],"knowthat_facts",["id"]],
      ["knowthat_linkage_checks_fact_id_fkey","knowthat_linkage_checks",["fact_id"],"knowthat_facts",["id"]],
      ["semantic_key_aliases_target_fact_id_fkey","semantic_key_aliases",["target_fact_id"],"knowthat_facts",["id"]],
    ]),
    append_only_tables: [
      "knowthat_fact_revisions",
      "knowthat_candidate_reviews",
      "knowthat_feedback_events",
      "knowthat_event_outbox",
      "knowthat_event_inbox",
      "knowthat_event_dlq",
      "knowthat_memory_command_outbox",
      "semantic_key_aliases",
    ],
    outbox_tables: [
      "knowthat_event_outbox",
      "knowthat_memory_command_outbox",
    ],
    inbox_tables: ["knowthat_event_inbox"],
    dlq_tables: ["knowthat_event_dlq"],
    object_metadata_tables: [],
  } as const);

export interface KnowThatRepositoryPortV1
  extends OwnerRepositoryPortV1<typeof KNOWTHAT_REPOSITORY_CONTRACT_V1> {}

export type KnowThatUnitOfWorkPortV1 = OwnerUnitOfWorkPortV1<
  "knowthat",
  Readonly<{ owner: KnowThatRepositoryPortV1 }>
>;
