import {
  KNOWTHAT_DATABASE_COLUMNS_V1,
  KNOWTHAT_DATABASE_INDEXES_V1,
  KNOWTHAT_DATABASE_CHECKS_V1,
  KNOWTHAT_DATABASE_FUNCTIONS_V1,
  KNOWTHAT_DATABASE_TRIGGERS_V1,
  KNOWTHAT_DATABASE_UNIQUE_CONSTRAINTS_V1,
  KNOWTHAT_FOREIGN_KEYS_V1,
} from "./catalog-snapshot.generated.v1.js";
import { KNOWTHAT_WRITER_ARTIFACTS_V1 } from "./writer-artifacts.generated.v1.js";
import { OWNER_DURABLE_EVENT_TYPES_V1 } from "@pai/contracts";
import {
  defineOwnerRepositoryContractV1,
  ownerDlqResolutionContractV1,
  ownerEventingReconciliationContractV1,
  ownerEventingTransportEpochActivationSignatureV1,
  ownerEventingTransportEpochTablePermissionV1,
  ownerFunctionSignatureV1,
  type OwnerRepositoryPortV1,
  type OwnerUnitOfWorkPortV1,
} from "@pai/persistence";

const KNOWTHAT_DLQ_RESOLUTION_V1 = ownerDlqResolutionContractV1(
  "knowthat",
  "knowthat_event_dlq",
);
const KNOWTHAT_EVENT_RECONCILIATION_V1 =
  ownerEventingReconciliationContractV1(
    "knowthat",
    "knowthat_event_outbox",
  );

export const KNOWTHAT_REPOSITORY_CONTRACT_V1 =
  defineOwnerRepositoryContractV1({
    contract_version: "owner_repository_contract.v1",
    owner_service: "knowthat",
    schema: "knowthat",
    app_role: "pai_knowthat_app",
    fresh_migrations: ["0500_knowthat"],
    manifest_source: "services/knowthat/src/db/permission-manifest.v1.ts",
    generated_permission_sql: [
      "pai-infra/supabase/generated/permissions/0500_knowthat.sql",
    ],
    tables: [
      "knowthat_facts",
      "knowthat_write_batches",
      "knowthat_fact_revisions",
      "knowthat_candidate_reviews",
      "knowthat_audit_logs",
    "knowthat_conflicts",
    "knowthat_linkage_checks",
    "knowthat_linkage_recovery_receipts",
    "knowthat_feedback_events",
      "knowthat_event_outbox",
      "knowthat_event_inbox",
      "knowthat_event_dlq",
      KNOWTHAT_DLQ_RESOLUTION_V1.resolution_table,
      "knowthat_query_revisions",
      "knowthat_fact_query_versions",
      "semantic_key_aliases",
      "semantic_key_synonyms",
      "knowthat_memory_command_outbox",
      "eventing_transport_epochs",
    ],
    table_permissions: [
    {
      table_name: "knowthat_facts",
      select_columns: ["id","bot_id","text","subject","predicate","object","normalized_object","object_hash","canonicalization_version","semantic_key_display","semantic_components_raw","semantic_components_normalized","semantic_key","category","status","confidence","source","source_ref","evidence_refs","valid_from","valid_until","payload_schema_version","state_version","candidate_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "knowthat_write_batches",
      select_columns: ["id","bot_id","trigger_process_id","source_meta_job_id","idempotency_key","request_hash","trace_id","request_payload","response_payload","status","payload_schema_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "knowthat_fact_revisions",
      select_columns: ["id","fact_id","revision_no","patch","reason","actor","promotion_reservation_id","promotion_fence_generation","promotion_reservation_token_hash","promotion_committed_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "knowthat_candidate_reviews",
      select_columns: ["id","fact_id","target_candidate_version","decision","reason","evidence_refs","evidence_set_hash","source_meta_job_id","suggestion_id","suggested_action","idempotency_key","request_hash","outcome","reason_code","response_payload","reviewed_by","promotion_reservation_id","promotion_fence_generation","promotion_reservation_token_hash","promotion_reservation_expires_at","promotion_committed_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "knowthat_audit_logs",
      select_columns: ["id","bot_id","aggregate_type","aggregate_id","action","actor","reason","state_version","payload","trace_id","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "knowthat_conflicts",
      select_columns: ["id","bot_id","conflict_key","semantic_key","left_fact_id","right_fact_id","conflict_type","field_path","source_priority_snapshot","confidence_delta","evidence_refs","proposed_resolution","status","resolution","payload_schema_version","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "knowthat_linkage_checks",
      select_columns: ["id","bot_id","fact_id","check_type","target_service","change_type","affected_query","target_memory_point_ids","action","reason","evidence_refs","idempotency_key","attempt_count","next_retry_at","locked_by","locked_until","last_error","status","result","payload_schema_version","created_at","updated_at","lease_generation","claim_token","job_version"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "state_transition",
    },
    {
      table_name: "knowthat_linkage_recovery_receipts",
      select_columns: ["id","bot_id","linkage_check_id","idempotency_key","request_hash","response_payload","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "knowthat_feedback_events",
      select_columns: ["id","bot_id","fact_id","feedback_type","payload","evidence_ref","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "knowthat_event_outbox",
      select_columns: ["id","bot_id","aggregate_id","event_type","schema_version","producer","occurred_at","idempotency_key","trace_id","payload","payload_hash","target","status","attempt_count","next_retry_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    {
      table_name: "knowthat_event_inbox",
      select_columns: ["id","source","event_id","scope_fingerprint","idempotency_key","payload_hash","semantic_hash","processed_at","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "knowthat_event_dlq",
      select_columns: ["id","source_event_id","event_type","payload","last_error","failed_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    KNOWTHAT_DLQ_RESOLUTION_V1.table_permission,
    {
      table_name: "knowthat_query_revisions",
      select_columns: ["bot_id","current_revision","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "pointer_cas",
    },
    {
      table_name: "knowthat_fact_query_versions",
      select_columns: ["bot_id","fact_id","visible_from_revision","visible_until_revision","status","category","semantic_key","updated_at","valid_from","valid_until","projection_payload","search_vector","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "semantic_key_aliases",
      select_columns: ["id","bot_id","old_canonicalization_version","old_semantic_key","new_canonicalization_version","new_semantic_key","target_fact_id","actor_ref","reason","evidence_refs","created_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "immutable_append",
    },
    {
      table_name: "semantic_key_synonyms",
      select_columns: ["segment","synonym","canonical"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "projection_upsert",
    },
    {
      table_name: "knowthat_memory_command_outbox",
      select_columns: ["id","bot_id","command_type","reservation_id","candidate_fact_id","fencing_generation","reservation_token_hash","reservation_expires_at","promotion_revision_id","committed_at","release_reason","released_at","idempotency_key","request_hash","payload","status","attempt_count","next_retry_at","claim_token","locked_by","locked_until","last_error","transport_ref","transport_epoch","transport_generation","sent_at","created_at","updated_at"],
      insert_columns: [],
      update_columns: [],
      delete_allowed: false,
      writer_kind: "outbox_claim_ack",
    },
    ownerEventingTransportEpochTablePermissionV1(),
    ],
    mutable_writers: [
      ...KNOWTHAT_DLQ_RESOLUTION_V1.mutable_writers,
      ...KNOWTHAT_EVENT_RECONCILIATION_V1.mutable_writers,
      "create_knowthat_fact_v1",
      "transition_knowthat_fact_v1",
      "append_knowthat_conflict_v1",
      "record_knowthat_candidate_review_v1",
      "transition_knowthat_conflict_v1",
      "enqueue_knowthat_linkage_check_v1",
      "transition_knowthat_linkage_check_v1",
      "claim_knowthat_linkage_check_v1",
      "recover_knowthat_linkage_check_v1",
      "append_knowthat_feedback_v1",
      "create_knowthat_write_batch_v1",
      "cas_knowthat_query_revision_v1",
      "claim_knowthat_event_outbox_v1",
      "ack_knowthat_event_outbox_v1",
      "enqueue_knowthat_promotion_release_v1",
      "claim_knowthat_memory_command_outbox_v1",
      "ack_knowthat_memory_command_outbox_v1",
      "activate_eventing_transport_epoch_v1",
    ],
    function_signatures: [
      ...KNOWTHAT_DLQ_RESOLUTION_V1.function_signatures,
      ...KNOWTHAT_EVENT_RECONCILIATION_V1.function_signatures,
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "create_knowthat_fact_v1",
      primary_table: "knowthat_facts",
      writer_kind: "state_transition",
      arguments: [["p_fact_id", "text"], ["p_fact", "jsonb"], ["p_initial_revision", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_facts"],
      writes_tables: ["knowthat_facts", "knowthat_fact_revisions", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_facts", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_fact_revisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "transition_knowthat_fact_v1",
      primary_table: "knowthat_facts",
      writer_kind: "state_transition",
      arguments: [["p_fact_id", "text"], ["p_expected_status", "text"], ["p_expected_state_version", "bigint"], ["p_expected_updated_at", "timestamptz"], ["p_next_status", "text"], ["p_fact_revision", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_facts", "knowthat_fact_revisions"],
      writes_tables: ["knowthat_facts", "knowthat_fact_revisions", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_facts", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "knowthat_fact_revisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "append_knowthat_conflict_v1",
      primary_table: "knowthat_conflicts",
      writer_kind: "state_transition",
      arguments: [["p_conflict_id", "text"], ["p_fact_id", "text"], ["p_conflict", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_facts", "knowthat_conflicts"],
      writes_tables: ["knowthat_conflicts", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_conflicts", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "record_knowthat_candidate_review_v1",
      primary_table: "knowthat_candidate_reviews",
      writer_kind: "immutable_append",
      arguments: [["p_review_id", "text"], ["p_fact_id", "text"], ["p_source_meta_job_id", "text"], ["p_suggestion_id", "text"], ["p_expected_candidate_version", "integer"], ["p_suggested_action", "text"], ["p_review", "jsonb"], ["p_promotion_evidence", "jsonb", { nullable: true }], ["p_promotion_reservation", "jsonb", { nullable: true }], ["p_memory_ack_command", "jsonb", { nullable: true }], ["p_memory_release_command", "jsonb", { nullable: true }], ["p_source_event", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_payload_hash", "text"], ["p_semantic_hash", "text"], ["p_scope_fingerprint", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_facts", "knowthat_candidate_reviews", "knowthat_conflicts", "knowthat_event_inbox", "knowthat_memory_command_outbox"],
      writes_tables: ["knowthat_facts", "knowthat_fact_revisions", "knowthat_candidate_reviews", "knowthat_linkage_checks", "knowthat_event_inbox", "knowthat_event_dlq", "knowthat_audit_logs", "knowthat_query_revisions", "knowthat_fact_query_versions", "knowthat_memory_command_outbox", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_facts", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "knowthat_fact_revisions", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_candidate_reviews", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_linkage_checks", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_inbox", operation: "append", concurrency_control: "durable_event_identity" },
        { table_name: "knowthat_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_query_revisions", operation: "cas", concurrency_control: "expected_version" },
        { table_name: "knowthat_fact_query_versions", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "knowthat_memory_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "transition_knowthat_conflict_v1",
      primary_table: "knowthat_conflicts",
      writer_kind: "state_transition",
      arguments: [["p_conflict_id", "text"], ["p_expected_status", "text"], ["p_expected_updated_at", "timestamptz"], ["p_next_status", "text"], ["p_resolution", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_conflicts", "knowthat_facts"],
      writes_tables: ["knowthat_conflicts", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_conflicts", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "enqueue_knowthat_linkage_check_v1",
      primary_table: "knowthat_linkage_checks",
      writer_kind: "state_transition",
      arguments: [["p_linkage_check_id", "text"], ["p_fact_id", "text"], ["p_linkage_check", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_facts", "knowthat_linkage_checks"],
      writes_tables: ["knowthat_linkage_checks", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_linkage_checks", operation: "enqueue", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "transition_knowthat_linkage_check_v1",
      primary_table: "knowthat_linkage_checks",
      writer_kind: "state_transition",
      arguments: [["p_linkage_check_id", "text"], ["p_expected_lease_generation", "bigint"], ["p_claim_token", "text"], ["p_worker_id", "text"], ["p_next_status", "text"], ["p_result", "jsonb"], ["p_memory_command", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_linkage_checks"],
      writes_tables: ["knowthat_linkage_checks", "knowthat_audit_logs"],
      effects: [
        { table_name: "knowthat_linkage_checks", operation: "transition", concurrency_control: "lease_fence" },
        { table_name: "knowthat_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "claim_knowthat_linkage_check_v1",
      primary_table: "knowthat_linkage_checks",
      writer_kind: "state_transition",
      arguments: [["p_linkage_check_id", "text"], ["p_expected_status", "text"], ["p_expected_job_version", "bigint"], ["p_expected_updated_at", "timestamptz"], ["p_worker_id", "text"], ["p_lease_seconds", "integer"], ["p_now", "timestamptz"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_linkage_checks"],
      writes_tables: ["knowthat_linkage_checks"],
      effects: [
        { table_name: "knowthat_linkage_checks", operation: "transition", concurrency_control: "lease_fence" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "recover_knowthat_linkage_check_v1",
      primary_table: "knowthat_linkage_checks",
      writer_kind: "state_transition",
      arguments: [["p_linkage_check_id", "text"], ["p_expected_job_version", "bigint"], ["p_recovery_action", "text"], ["p_reason", "text"], ["p_receipt", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_linkage_checks", "knowthat_linkage_recovery_receipts"],
      writes_tables: ["knowthat_linkage_checks", "knowthat_linkage_recovery_receipts", "knowthat_audit_logs"],
      effects: [
        { table_name: "knowthat_linkage_checks", operation: "transition", concurrency_control: "expected_state_version" },
        { table_name: "knowthat_linkage_recovery_receipts", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_audit_logs", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "append_knowthat_feedback_v1",
      primary_table: "knowthat_feedback_events",
      writer_kind: "immutable_append",
      arguments: [["p_feedback_event_id", "text"], ["p_fact_id", "text"], ["p_feedback", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_facts"],
      writes_tables: ["knowthat_feedback_events", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_feedback_events", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "create_knowthat_write_batch_v1",
      primary_table: "knowthat_write_batches",
      writer_kind: "state_transition",
      arguments: [["p_batch_id", "text"], ["p_batch", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_write_batches"],
      writes_tables: ["knowthat_write_batches", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_write_batches", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "cas_knowthat_query_revision_v1",
      primary_table: "knowthat_query_revisions",
      writer_kind: "pointer_cas",
      arguments: [["p_query_key", "text"], ["p_expected_revision", "bigint"], ["p_query_revision", "jsonb"], ["p_aliases", "jsonb"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_query_revisions", "knowthat_fact_query_versions"],
      writes_tables: ["knowthat_query_revisions", "knowthat_fact_query_versions", "semantic_key_aliases", "semantic_key_synonyms", "knowthat_event_outbox"],
      effects: [
        { table_name: "knowthat_query_revisions", operation: "cas", concurrency_control: "expected_version" },
        { table_name: "knowthat_fact_query_versions", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "semantic_key_aliases", operation: "append", concurrency_control: "idempotency_key" },
        { table_name: "semantic_key_synonyms", operation: "upsert", concurrency_control: "expected_version" },
        { table_name: "knowthat_event_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "claim_knowthat_event_outbox_v1",
      primary_table: "knowthat_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_worker_id", "text"], ["p_limit", "integer"], ["p_lease_seconds", "integer"], ["p_now", "timestamptz"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"]], reads_tables: ["knowthat_event_outbox", "eventing_transport_epochs"], writes_tables: ["knowthat_event_outbox"],
      effects: [{ table_name: "knowthat_event_outbox", operation: "claim", concurrency_control: "lease_fence" }],
      returns: "setof jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "ack_knowthat_event_outbox_v1",
      primary_table: "knowthat_event_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_outbox_id", "text"], ["p_claim_token", "text"], ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"], ["p_error", "jsonb"], ["p_transport_ref", "text"], ["p_transport_epoch", "text"], ["p_transport_generation", "bigint"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"], ["p_now", "timestamptz"]], reads_tables: ["knowthat_event_outbox", "eventing_transport_epochs"], writes_tables: ["knowthat_event_outbox", "knowthat_event_dlq"],
      effects: [
        { table_name: "knowthat_event_outbox", operation: "ack", concurrency_control: "lease_fence" },
        { table_name: "knowthat_event_dlq", operation: "append", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "enqueue_knowthat_promotion_release_v1",
      primary_table: "knowthat_memory_command_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_command", "jsonb"], ["p_idempotency_key", "text"], ["p_request_hash", "text"], ["p_trace_id", "text"]],
      reads_tables: ["knowthat_memory_command_outbox", "knowthat_facts", "knowthat_candidate_reviews"],
      writes_tables: ["knowthat_memory_command_outbox"],
      effects: [
        { table_name: "knowthat_memory_command_outbox", operation: "enqueue", concurrency_control: "idempotency_key" },
      ],
      returns: "jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "claim_knowthat_memory_command_outbox_v1",
      primary_table: "knowthat_memory_command_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_worker_id", "text"], ["p_limit", "integer"], ["p_lease_seconds", "integer"], ["p_now", "timestamptz"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"]], reads_tables: ["knowthat_memory_command_outbox", "eventing_transport_epochs"], writes_tables: ["knowthat_memory_command_outbox"],
      effects: [{ table_name: "knowthat_memory_command_outbox", operation: "claim", concurrency_control: "lease_fence" }],
      returns: "setof jsonb",
    }),
    ownerFunctionSignatureV1({
      schema: "knowthat",
      function_name: "ack_knowthat_memory_command_outbox_v1",
      primary_table: "knowthat_memory_command_outbox",
      writer_kind: "outbox_claim_ack",
      arguments: [["p_outbox_id", "text"], ["p_claim_token", "text"], ["p_outcome", "text"], ["p_next_retry_at", "timestamptz"], ["p_error", "jsonb"], ["p_transport_ref", "text"], ["p_transport_epoch", "text"], ["p_transport_generation", "bigint"], ["p_current_transport_epoch", "text"], ["p_current_transport_generation", "bigint"], ["p_now", "timestamptz"]], reads_tables: ["knowthat_memory_command_outbox", "eventing_transport_epochs"], writes_tables: ["knowthat_memory_command_outbox"],
      effects: [{ table_name: "knowthat_memory_command_outbox", operation: "ack", concurrency_control: "lease_fence" }],
      returns: "jsonb",
    }),
    ownerEventingTransportEpochActivationSignatureV1("knowthat"),
    ],
    // The generator imports this module under an explicit cache-busting
    // `?writer=` URL so it can attest a changed signature before the new
    // artifact exists. Normal application imports never carry that marker
    // and therefore remain fail-closed on exact artifact drift.
    ...(new URL(import.meta.url).searchParams.has("writer")
      ? {}
      : { writer_artifacts: KNOWTHAT_WRITER_ARTIFACTS_V1 }),
    database_columns: KNOWTHAT_DATABASE_COLUMNS_V1,
    database_checks: KNOWTHAT_DATABASE_CHECKS_V1,
    database_functions: KNOWTHAT_DATABASE_FUNCTIONS_V1,
    database_triggers: KNOWTHAT_DATABASE_TRIGGERS_V1,
    database_unique_constraints: KNOWTHAT_DATABASE_UNIQUE_CONSTRAINTS_V1,
    database_indexes: KNOWTHAT_DATABASE_INDEXES_V1,
    foreign_key_snapshot: {
      status: "complete",
      source: "Database Design revision 508 / fresh 0500_knowthat canonical DDL contract snapshot; version-pinned pai-infra artifacts are required before PostgreSQL deployment verification",
    },
  foreign_keys: KNOWTHAT_FOREIGN_KEYS_V1,
    append_only_tables: [
      "knowthat_fact_revisions",
      "knowthat_candidate_reviews",
      "knowthat_feedback_events",
      "knowthat_event_outbox",
      "knowthat_event_inbox",
      "knowthat_event_dlq",
      KNOWTHAT_DLQ_RESOLUTION_V1.resolution_table,
      "knowthat_audit_logs",
      "knowthat_linkage_recovery_receipts",
      "knowthat_memory_command_outbox",
      "semantic_key_aliases",
    ],
    outbox_tables: [
      "knowthat_event_outbox",
      "knowthat_memory_command_outbox",
    ],
    inbox_tables: ["knowthat_event_inbox"],
    dlq_tables: ["knowthat_event_dlq"],
    dlq_resolutions: [KNOWTHAT_DLQ_RESOLUTION_V1.binding],
    object_metadata_tables: [],
  } as const);

export interface KnowThatRepositoryPortV1
  extends OwnerRepositoryPortV1<typeof KNOWTHAT_REPOSITORY_CONTRACT_V1> {}

export type KnowThatUnitOfWorkPortV1 = OwnerUnitOfWorkPortV1<
  "knowthat",
  Readonly<{ owner: KnowThatRepositoryPortV1 }>
>;
